import 'package:flutter/material.dart';
import 'package:cached_network_image/cached_network_image.dart';
import '../../../../core/theme/app_colors.dart';
import '../../data/models/voting_bloc.dart';
import 'flyer_generator.dart';
import 'share_bloc.dart';

/// Bloc banner image + info section displayed above the tabs.
class BlocHeader extends StatelessWidget {
  final VotingBloc bloc;
  const BlocHeader({super.key, required this.bloc});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        // ── Banner Image ──────────────────────────────────────
        if (bloc.bannerImageUrl != null &&
            bloc.bannerImageUrl!.isNotEmpty)
          CachedNetworkImage(
            imageUrl: bloc.bannerImageUrl!,
            height: 180,
            width: double.infinity,
            fit: BoxFit.cover,
            placeholder: (_, __) => Container(
              height: 180,
              color: theme.colorScheme.onSurface.withOpacity(0.05),
            ),
            errorWidget: (_, __, ___) => Container(
              height: 180,
              color: theme.colorScheme.onSurface.withOpacity(0.05),
              child: Icon(
                Icons.image_outlined,
                size: 32,
                color: theme.colorScheme.onSurface.withOpacity(0.12),
              ),
            ),
          )
        else
          Container(
            height: 120,
            width: double.infinity,
            decoration: BoxDecoration(
              gradient: LinearGradient(
                colors: [
                  AppColors.primary.withOpacity(0.15),
                  AppColors.primary.withOpacity(0.05),
                ],
                begin: Alignment.topLeft,
                end: Alignment.bottomRight,
              ),
            ),
            child: Center(
              child: Icon(
                Icons.groups_rounded,
                size: 48,
                color: AppColors.primary.withOpacity(0.3),
              ),
            ),
          ),

        // ── Info Section ──────────────────────────────────────
        Padding(
          padding: const EdgeInsets.fromLTRB(20, 16, 20, 0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Title row
              Row(
                children: [
                  Expanded(
                    child: Text(
                      bloc.name,
                      style: TextStyle(
                        fontSize: 20,
                        fontWeight: FontWeight.w800,
                        letterSpacing: -0.4,
                        color: theme.colorScheme.onSurface,
                      ),
                    ),
                  ),
                  if (bloc.isAutoGenerated == true)
                    Container(
                      padding: const EdgeInsets.symmetric(
                          horizontal: 8, vertical: 3),
                      decoration: BoxDecoration(
                        color: AppColors.primary.withOpacity(0.1),
                        borderRadius: BorderRadius.circular(6),
                      ),
                      child: const Text(
                        'Auto',
                        style: TextStyle(
                          fontSize: 11,
                          fontWeight: FontWeight.w600,
                          color: AppColors.primary,
                        ),
                      ),
                    ),
                ],
              ),
              const SizedBox(height: 8),

              // Description
              if (bloc.description.isNotEmpty)
                Text(
                  bloc.description,
                  maxLines: 3,
                  overflow: TextOverflow.ellipsis,
                  style: TextStyle(
                    fontSize: 14,
                    height: 1.5,
                    color:
                        theme.colorScheme.onSurface.withOpacity(0.55),
                  ),
                ),

              const SizedBox(height: 12),

              // Meta chips (target + location + members)
              Wrap(
                spacing: 8,
                runSpacing: 8,
                children: [
                  if (bloc.targetCandidate != null &&
                      bloc.targetCandidate!.isNotEmpty)
                    _MetaChip(
                      icon: Icons.flag_rounded,
                      label: bloc.targetCandidate!,
                      theme: theme,
                    ),
                  if (bloc.location != null)
                    _MetaChip(
                      icon: Icons.location_on_outlined,
                      label: _formatLocation(bloc.location!),
                      theme: theme,
                    ),
                  _MetaChip(
                    icon: Icons.people_outline_rounded,
                    label:
                        '${bloc.totalMembers ?? bloc.memberCount ?? 0} members',
                    theme: theme,
                  ),
                ],
              ),

              const SizedBox(height: 16),

              // Action buttons
              Row(
                children: [
                  Expanded(
                    child: _ActionButton(
                      icon: Icons.share_rounded,
                      label: 'Share to Invite',
                      onTap: () {
                        showShareBloc(context, bloc);
                      },
                      theme: theme,
                      isPrimary: true,
                    ),
                  ),
                  const SizedBox(width: 10),
                  Expanded(
                    child: _ActionButton(
                      icon: Icons.image_rounded,
                      label: 'Share Flyer',
                      onTap: () {
                        showFlyerGenerator(context);
                      },
                      theme: theme,
                      isPrimary: false,
                    ),
                  ),
                ],
              ),

              const SizedBox(height: 16),
              Divider(
                color: theme.colorScheme.outline.withOpacity(0.1),
                height: 1,
              ),
            ],
          ),
        ),
      ],
    );
  }

  String _formatLocation(BlocLocation loc) {
    final parts = <String>[];
    if (loc.ward.isNotEmpty) parts.add(loc.ward);
    if (loc.lga.isNotEmpty) parts.add(loc.lga);
    if (loc.state.isNotEmpty) parts.add(loc.state);
    return parts.join(', ');
  }
}

// ── Meta Chip ────────────────────────────────────────────────

class _MetaChip extends StatelessWidget {
  final IconData icon;
  final String label;
  final ThemeData theme;

  const _MetaChip({
    required this.icon,
    required this.label,
    required this.theme,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 5),
      decoration: BoxDecoration(
        color: theme.colorScheme.onSurface.withOpacity(0.05),
        borderRadius: BorderRadius.circular(8),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(
            icon,
            size: 14,
            color: theme.colorScheme.onSurface.withOpacity(0.4),
          ),
          const SizedBox(width: 5),
          Flexible(
            child: Text(
              label,
              maxLines: 1,
              overflow: TextOverflow.ellipsis,
              style: TextStyle(
                fontSize: 12,
                fontWeight: FontWeight.w500,
                color: theme.colorScheme.onSurface.withOpacity(0.55),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

// ── Action Button ────────────────────────────────────────────

class _ActionButton extends StatelessWidget {
  final IconData icon;
  final String label;
  final VoidCallback onTap;
  final ThemeData theme;
  final bool isPrimary;

  const _ActionButton({
    required this.icon,
    required this.label,
    required this.onTap,
    required this.theme,
    required this.isPrimary,
  });

  @override
  Widget build(BuildContext context) {
    return Material(
      color: isPrimary
          ? AppColors.primary
          : theme.colorScheme.onSurface.withOpacity(0.06),
      borderRadius: BorderRadius.circular(10),
      child: InkWell(
        onTap: onTap,
        borderRadius: BorderRadius.circular(10),
        child: Padding(
          padding: const EdgeInsets.symmetric(vertical: 11),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Icon(
                icon,
                size: 16,
                color: isPrimary
                    ? Colors.white
                    : theme.colorScheme.onSurface.withOpacity(0.6),
              ),
              const SizedBox(width: 6),
              Text(
                label,
                style: TextStyle(
                  fontSize: 13,
                  fontWeight: FontWeight.w600,
                  color: isPrimary
                      ? Colors.white
                      : theme.colorScheme.onSurface.withOpacity(0.6),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
