#!/bin/bash

echo "=============================================="
echo "PVC Status Migration SQL"
echo "=============================================="
echo ""
echo "Please run the following SQL commands in your PostgreSQL database:"
echo ""
echo "-- Add PVC Status column to voting bloc member metadata"
echo "-- This adds a new member tag for tracking PVC (Permanent Voter Card) status"
echo ""
echo "ALTER TABLE \"votingBlocMemberMetadata\""
echo "ADD COLUMN \"pvcStatus\" VARCHAR(30) DEFAULT 'Unregistered'"
echo "CHECK (\"pvcStatus\" IN ('Unregistered', 'Registered but no PVC', 'Registered with PVC'));"
echo ""
echo "-- Create an index for the new column for better query performance"
echo "CREATE INDEX \"idx_votingBlocMemberMetadata_pvcStatus\" ON \"votingBlocMemberMetadata\"(\"pvcStatus\");"
echo ""
echo "-- Update existing records to have the default value"
echo "UPDATE \"votingBlocMemberMetadata\" SET \"pvcStatus\" = 'Unregistered' WHERE \"pvcStatus\" IS NULL;"
echo ""
echo "=============================================="
echo "After running the SQL, you can test the backend API endpoints:"
echo "=============================================="
