import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router';
import {
  Box,
  Typography,
  Card,
  CardActionArea,
  Avatar,
  Chip,
  Grid,
  Alert,
  Button,
  Skeleton,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  CircularProgress,
} from '@mui/material';
import {
  Users,
  Trophy,
  CreditCard,
  MapPin,
  ShieldCheck,
  Bell,
  ExternalLink,
  Package,
  Upload,
  CheckCircle,
  X,
  Heart,
  Vote,
  MessageSquare,
  UserPlus,
  ArrowUpRight,
} from 'lucide-react';
import axios from 'axios';
import { useUser } from '../../context/UserContext';
import {
  getOwnedVotingBlocs,
  getJoinedVotingBlocs,
} from '../../services/votingBlocService';
import { getNotifications } from '../../services/notificationService';
import { submitAdcCard } from '../../services/adcService';
import type { ChatContact } from '../../services/conversationService';
import { useMyLeaders } from './overview/hooks/useMyLeaders';
import LeaderInfoModal from './components/LeaderInfoModal';

const FONT = '"Poppins", sans-serif';
const PRIMARY = '#006837';
const API = import.meta.env.VITE_API_BASE_URL || 'http://localhost:5000';

interface BlocSummary {
  _id: string;
  name: string;
  location?: { state?: string; lga?: string };
  metrics?: { totalMembers?: number; engagementScore?: number };
  isAutoGenerated?: boolean;
  status?: string;
}

export default function DashboardHome() {
  const { profile } = useUser();
  const navigate = useNavigate();
  const [ownedBlocs, setOwnedBlocs] = useState<BlocSummary[]>([]);
  const [joinedBlocs, setJoinedBlocs] = useState<BlocSummary[]>([]);
  const [notifications, setNotifications] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [mobilizationUrl, setMobilizationUrl] = useState('');
  const [ctaLinks, setCtaLinks] = useState<Record<string, string>>({});

  // ADC Registration
  const [adcModalOpen, setAdcModalOpen] = useState(false);
  const [adcStep, setAdcStep] = useState<'ask' | 'upload' | 'done'>('ask');
  const [adcUploading, setAdcUploading] = useState(false);
  const [adcPreview, setAdcPreview] = useState<string | null>(null);
  const [adcBase64, setAdcBase64] = useState<string | null>(null);
  const [adcError, setAdcError] = useState('');

  // Leadership
  const { leaders, loading: leadersLoading } = useMyLeaders();
  const [selectedLeader, setSelectedLeader] = useState<ChatContact | null>(null);
  const [peterObiOpen, setPeterObiOpen] = useState(false);

  const levelLocationFor = (leader: ChatContact) => {
    // Coordinators are scoped to the current user's voting jurisdiction
    switch (leader.level) {
      case 'state': return profile?.votingState || '';
      case 'lga': return profile?.votingLGA || '';
      case 'ward': return profile?.votingWard || '';
      default: return '';
    }
  };

  const isCoordinator =
    profile?.designation &&
    [
      'National Coordinator',
      'State Coordinator',
      'LGA Coordinator',
      'Ward Coordinator',
    ].includes(profile.designation);

  useEffect(() => {
    const ctaKeys = ['cta_volunteer_url', 'cta_run_for_office_url', 'cta_donate_url', 'cta_feedback_url'];
    const ctaFetch = Promise.all(
      ctaKeys.map(key =>
        axios.get(`${API}/api/settings/${key}`).then(r => ({ key, value: r.data.value || '' })).catch(() => ({ key, value: '' }))
      )
    ).then(results => {
      const links: Record<string, string> = {};
      results.forEach(r => { if (r.value) links[r.key] = r.value; });
      setCtaLinks(links);
    });

    Promise.all([
      getOwnedVotingBlocs().then((d) => setOwnedBlocs(d.votingBlocs || [])),
      getJoinedVotingBlocs().then((d) => setJoinedBlocs(d.votingBlocs || [])),
      getNotifications().then((d) => setNotifications(Array.isArray(d) ? d.slice(0, 5) : [])),
      axios.get(`${API}/api/settings/mobilization_pack_url`).then((r) => setMobilizationUrl(r.data.value || '')).catch(() => {}),
      ctaFetch,
    ])
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  /* ─── ADC Handlers ─── */
  const openAdcModal = () => {
    setAdcStep('ask');
    setAdcPreview(null);
    setAdcBase64(null);
    setAdcError('');
    setAdcModalOpen(true);
  };

  const handleAdcFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    if (file.size > 5 * 1024 * 1024) {
      setAdcError('File must be under 5MB');
      return;
    }
    setAdcError('');
    const reader = new FileReader();
    reader.onload = () => {
      setAdcPreview(reader.result as string);
      setAdcBase64(reader.result as string);
    };
    reader.readAsDataURL(file);
  };

  const handleAdcSubmit = async () => {
    if (!adcBase64) return;
    setAdcUploading(true);
    setAdcError('');
    try {
      await submitAdcCard(adcBase64);
      setAdcStep('done');
    } catch (err: any) {
      setAdcError(err.response?.data?.message || 'Upload failed');
    } finally {
      setAdcUploading(false);
    }
  };

  /* ─── Quick Actions Config ─── */
  const quickActions = [
    { label: 'My Voting Bloc', icon: Users, path: '/dashboard/voting-bloc', color: PRIMARY },
    { label: 'Leaderboard', icon: Trophy, path: '/dashboard/leaderboard', color: '#D97706' },
    { label: 'Membership Card', icon: CreditCard, path: '/dashboard/card', color: '#7C3AED' },
    ...(profile?.role === 'admin' || isCoordinator
      ? [{ label: 'State Dashboard', icon: MapPin, path: '/dashboard/state', color: '#2563EB' }]
      : []),
    ...(profile?.role === 'admin' || isCoordinator
      ? [{ label: 'Admin Panel', icon: ShieldCheck, path: '/pbx/dashboard', color: '#DC2626', external: true }]
      : []),
    { label: 'Notifications', icon: Bell, path: '/dashboard/notifications', color: '#0891B2' },
  ];

  return (
    <Box sx={{ display: 'flex', flexDirection: 'column', gap: { xs: 3, md: 5 }, fontFamily: FONT }}>
      {/* ═══ Welcome Hero ═══ */}
      <Card
        elevation={0}
        sx={{
          borderRadius: { xs: 4, md: 5 },
          overflow: 'hidden',
          position: 'relative',
          background: `linear-gradient(135deg, ${PRIMARY} 0%, #006b3e 100%)`,
        }}
      >
        {/* Subtle SVG curve decorative element */}
        <Box
          sx={{
            position: 'absolute',
            inset: 0,
            opacity: 0.1,
            pointerEvents: 'none',
          }}
        >
          <svg width="100%" height="100%" preserveAspectRatio="none" viewBox="0 0 100 100">
            <path d="M0 100 C 20 0 50 0 100 100" fill="none" stroke="white" strokeWidth="0.5" />
          </svg>
        </Box>

        <Box
          sx={{
            display: 'flex',
            flexDirection: { xs: 'column', sm: 'row' },
            alignItems: { xs: 'flex-start', sm: 'center' },
            justifyContent: 'space-between',
            gap: { xs: 3, sm: 4 },
            p: { xs: 4, sm: 5, md: 6 },
            position: 'relative',
            zIndex: 1,
          }}
        >
          <Box sx={{ display: 'flex', alignItems: 'center', gap: { xs: 2.5, sm: 3 } }}>
            <Box sx={{ position: 'relative' }}>
              <Avatar
                src={profile?.profileImage || undefined}
                alt={profile?.name}
                imgProps={{ referrerPolicy: 'no-referrer' }}
                sx={{
                  width: { xs: 72, sm: 96 },
                  height: { xs: 72, sm: 96 },
                  border: '4px solid rgba(255,255,255,0.2)',
                  bgcolor: '#555',
                  fontSize: { xs: 28, sm: 36 },
                  boxShadow: '0 8px 24px rgba(0,0,0,0.2)',
                  borderRadius: { xs: 3, sm: 4 },
                }}
              >
                {profile?.name?.[0]}
              </Avatar>
              <Box
                sx={{
                  position: 'absolute',
                  bottom: -4,
                  right: -4,
                  width: 20,
                  height: 20,
                  borderRadius: '50%',
                  bgcolor: '#4ade80',
                  border: `4px solid ${PRIMARY}`,
                  boxShadow: '0 0 0 3px rgba(74,222,128,0.2)',
                }}
              />
            </Box>
            <Box sx={{ color: '#fff' }}>
              <Typography
                sx={{
                  fontFamily: FONT,
                  fontSize: { xs: '0.65rem', sm: '0.7rem' },
                  fontWeight: 500,
                  color: 'rgba(134,239,172,0.9)',
                  letterSpacing: '0.1em',
                  textTransform: 'uppercase',
                  mb: 0.5,
                }}
              >
                {profile?.designation || 'Electoral Member'}
              </Typography>
              <Typography
                sx={{
                  fontFamily: FONT,
                  fontWeight: 800,
                  fontSize: { xs: '1.5rem', sm: '2rem' },
                  letterSpacing: '-0.02em',
                  lineHeight: 1.2,
                }}
              >
                Welcome back, {profile?.name?.split(' ')[0]}!
              </Typography>
              <Typography
                sx={{
                  fontFamily: FONT,
                  color: 'rgba(255,255,255,0.7)',
                  fontSize: { xs: '0.8rem', sm: '0.85rem' },
                  mt: 0.5,
                  fontWeight: 300,
                }}
              >
                Your civic activity is making a difference today.
              </Typography>
            </Box>
          </Box>

          <Button
            component={Link}
            to="/dashboard/profile"
            sx={{
              bgcolor: '#fff',
              color: PRIMARY,
              borderRadius: 3,
              textTransform: 'none',
              fontFamily: FONT,
              fontWeight: 700,
              fontSize: '0.85rem',
              px: { xs: 4, sm: 5 },
              py: 1.5,
              boxShadow: '0 4px 12px rgba(0,0,0,0.1)',
              '&:hover': { bgcolor: '#f0fdf4', transform: 'scale(0.97)' },
              transition: 'all 0.15s',
              flexShrink: 0,
              alignSelf: { xs: 'stretch', sm: 'center' },
              textAlign: 'center',
            }}
          >
            View Profile
          </Button>
        </Box>

        {/* ─ Status Pills ─ */}
        <Box
          sx={{
            display: 'flex',
            gap: 1.5,
            flexWrap: 'wrap',
            px: { xs: 4, sm: 5, md: 6 },
            pb: { xs: 3, sm: 4 },
          }}
        >
          <Chip
            size="small"
            label={`KYC: ${profile?.kycStatus === 'approved' ? 'Verified' : profile?.kycStatus === 'pending' ? 'Pending' : profile?.kycStatus === 'rejected' ? 'Rejected' : 'Not Submitted'}`}
            sx={{
              fontFamily: FONT,
              fontWeight: 700,
              fontSize: '0.65rem',
              letterSpacing: '0.02em',
              height: 28,
              borderRadius: 2,
              bgcolor:
                profile?.kycStatus === 'approved' ? 'rgba(74,222,128,0.2)'
                : profile?.kycStatus === 'pending' ? 'rgba(250,204,21,0.25)'
                : profile?.kycStatus === 'rejected' ? 'rgba(248,113,113,0.2)'
                : 'rgba(255,255,255,0.15)',
              color:
                profile?.kycStatus === 'approved' ? '#bbf7d0'
                : profile?.kycStatus === 'pending' ? '#fef08a'
                : profile?.kycStatus === 'rejected' ? '#fecaca'
                : 'rgba(255,255,255,0.7)',
              border: '1px solid',
              borderColor:
                profile?.kycStatus === 'approved' ? 'rgba(74,222,128,0.3)'
                : profile?.kycStatus === 'pending' ? 'rgba(250,204,21,0.3)'
                : profile?.kycStatus === 'rejected' ? 'rgba(248,113,113,0.3)'
                : 'rgba(255,255,255,0.2)',
            }}
          />
          <Chip
            size="small"
            label={`ADC: ${profile?.adcStatus === 'verified' ? 'Verified' : profile?.adcStatus === 'pending' ? 'Pending' : profile?.adcStatus === 'rejected' ? 'Rejected' : 'Not Registered'}`}
            sx={{
              fontFamily: FONT,
              fontWeight: 700,
              fontSize: '0.65rem',
              letterSpacing: '0.02em',
              height: 28,
              borderRadius: 2,
              bgcolor:
                profile?.adcStatus === 'verified' ? 'rgba(74,222,128,0.2)'
                : profile?.adcStatus === 'pending' ? 'rgba(250,204,21,0.25)'
                : profile?.adcStatus === 'rejected' ? 'rgba(248,113,113,0.2)'
                : 'rgba(255,255,255,0.15)',
              color:
                profile?.adcStatus === 'verified' ? '#bbf7d0'
                : profile?.adcStatus === 'pending' ? '#fef08a'
                : profile?.adcStatus === 'rejected' ? '#fecaca'
                : 'rgba(255,255,255,0.7)',
              border: '1px solid',
              borderColor:
                profile?.adcStatus === 'verified' ? 'rgba(74,222,128,0.3)'
                : profile?.adcStatus === 'pending' ? 'rgba(250,204,21,0.3)'
                : profile?.adcStatus === 'rejected' ? 'rgba(248,113,113,0.3)'
                : 'rgba(255,255,255,0.2)',
            }}
          />
        </Box>
      </Card>

      {/* ═══ Voting Location Chips ═══ */}
      {profile?.votingState && (
        <Box
          sx={{
            display: 'flex',
            alignItems: 'center',
            flexWrap: 'wrap',
            gap: { xs: 1, sm: 1.25 },
          }}
        >
          <Typography
            sx={{
              fontFamily: FONT,
              fontWeight: 700,
              fontSize: '0.7rem',
              color: 'text.secondary',
              letterSpacing: '0.08em',
              textTransform: 'uppercase',
              mr: 0.5,
            }}
          >
            Active Jurisdictions:
          </Typography>
          {[
            profile.votingState,
            profile.votingLGA,
            profile.votingWard,
            profile.votingPU,
          ]
            .filter(Boolean)
            .map((loc) => (
              <Chip
                key={loc}
                label={loc}
                size="small"
                icon={
                  <Box
                    sx={{
                      width: 6,
                      height: 6,
                      borderRadius: '50%',
                      bgcolor: PRIMARY,
                      ml: 1,
                    }}
                  />
                }
                sx={{
                  fontFamily: FONT,
                  fontWeight: 600,
                  fontSize: '0.7rem',
                  bgcolor: '#f3f4f6',
                  color: '#111827',
                  borderRadius: 6,
                  border: '1px solid',
                  borderColor: 'rgba(0,0,0,0.06)',
                  height: 32,
                  '& .MuiChip-icon': { ml: 0.5 },
                }}
              />
            ))}
          {!profile.votingLGA && (
            <Typography
              component={Link}
              to="/dashboard/profile"
              sx={{
                fontFamily: FONT,
                fontSize: '0.7rem',
                fontWeight: 500,
                color: PRIMARY,
                ml: 0.5,
                textDecoration: 'none',
                '&:hover': { textDecoration: 'underline' },
              }}
            >
              Complete →
            </Typography>
          )}
        </Box>
      )}

      {/* ═══ KYC Verification Banner ═══ */}
      {profile?.kycStatus !== 'approved' && (
        <Card
          elevation={0}
          sx={{
            bgcolor: '#fef3c7',
            borderRadius: 4,
            border: '1px solid rgba(217,119,6,0.15)',
            overflow: 'hidden',
          }}
        >
          <Box
            sx={{
              display: 'flex',
              alignItems: { xs: 'flex-start', sm: 'center' },
              justifyContent: 'space-between',
              flexDirection: { xs: 'column', sm: 'row' },
              gap: 2,
              p: { xs: 2.5, sm: 3 },
            }}
          >
            <Box sx={{ display: 'flex', alignItems: 'flex-start', gap: 2 }}>
              <Box
                sx={{
                  width: 40,
                  height: 40,
                  borderRadius: '50%',
                  bgcolor: 'rgba(217,119,6,0.1)',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  flexShrink: 0,
                }}
              >
                <ShieldCheck size={20} color="#d97706" />
              </Box>
              <Box>
                <Typography sx={{ fontFamily: FONT, fontWeight: 700, fontSize: '0.9rem', color: '#92400e' }}>
                  Identity Verification Needed
                </Typography>
                <Typography sx={{ fontFamily: FONT, fontSize: '0.8rem', color: '#a16207', mt: 0.25 }}>
                  To access voting blocs and premium analytics, please complete your KYC profile.
                </Typography>
              </Box>
            </Box>
            <Button
              component={Link}
              to="/dashboard/profile"
              sx={{
                fontFamily: FONT,
                fontWeight: 700,
                fontSize: '0.8rem',
                textTransform: 'none',
                color: '#92400e',
                px: 2,
                borderRadius: 2,
                whiteSpace: 'nowrap',
                '&:hover': { bgcolor: 'rgba(217,119,6,0.08)' },
              }}
            >
              Verify Now
            </Button>
          </Box>
        </Card>
      )}

      {/* ═══ ADC Membership Banner ═══ */}
      {profile?.adcStatus !== 'verified' && (
        <Card
          elevation={0}
          sx={{
            bgcolor: profile?.adcStatus === 'rejected' ? '#fee2e2' : profile?.adcStatus === 'pending' ? '#eff6ff' : '#f0fdf4',
            borderRadius: 4,
            border: '1px solid',
            borderColor: profile?.adcStatus === 'rejected' ? 'rgba(220,38,38,0.15)' : profile?.adcStatus === 'pending' ? 'rgba(59,130,246,0.15)' : 'rgba(0,104,55,0.12)',
            overflow: 'hidden',
          }}
        >
          <Box
            sx={{
              display: 'flex',
              alignItems: { xs: 'flex-start', sm: 'center' },
              justifyContent: 'space-between',
              flexDirection: { xs: 'column', sm: 'row' },
              gap: 2,
              p: { xs: 2.5, sm: 3 },
            }}
          >
            <Box sx={{ display: 'flex', alignItems: 'flex-start', gap: 2 }}>
              <Box
                sx={{
                  width: 40,
                  height: 40,
                  borderRadius: '50%',
                  bgcolor: profile?.adcStatus === 'rejected' ? 'rgba(220,38,38,0.1)' : profile?.adcStatus === 'pending' ? 'rgba(59,130,246,0.1)' : `${PRIMARY}0D`,
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  flexShrink: 0,
                }}
              >
                <CreditCard size={20} color={profile?.adcStatus === 'rejected' ? '#dc2626' : profile?.adcStatus === 'pending' ? '#2563eb' : PRIMARY} />
              </Box>
              <Box>
                <Typography sx={{ fontFamily: FONT, fontWeight: 700, fontSize: '0.9rem', color: profile?.adcStatus === 'rejected' ? '#991b1b' : profile?.adcStatus === 'pending' ? '#1e40af' : '#14532d' }}>
                  {profile?.adcStatus === 'rejected'
                    ? 'ADC Card Rejected'
                    : profile?.adcStatus === 'pending'
                    ? 'ADC Verification In Progress'
                    : 'ADC Membership Required'}
                </Typography>
                <Typography sx={{ fontFamily: FONT, fontSize: '0.8rem', color: profile?.adcStatus === 'rejected' ? '#b91c1c' : profile?.adcStatus === 'pending' ? '#3b82f6' : '#15803d', mt: 0.25 }}>
                  {profile?.adcStatus === 'rejected'
                    ? 'Your membership card was rejected. Please re-upload a valid card.'
                    : profile?.adcStatus === 'pending'
                    ? 'Your ADC card is being reviewed. You\'ll be notified once verified.'
                    : 'Register as an ADC member and upload your membership card to unlock full access.'}
                </Typography>
              </Box>
            </Box>
            {profile?.adcStatus !== 'pending' && (
              <Button
                onClick={openAdcModal}
                sx={{
                  fontFamily: FONT,
                  fontWeight: 700,
                  fontSize: '0.8rem',
                  textTransform: 'none',
                  color: profile?.adcStatus === 'rejected' ? '#991b1b' : '#14532d',
                  px: 2,
                  borderRadius: 2,
                  whiteSpace: 'nowrap',
                  '&:hover': { bgcolor: profile?.adcStatus === 'rejected' ? 'rgba(220,38,38,0.08)' : 'rgba(0,104,55,0.08)' },
                }}
              >
                {profile?.adcStatus === 'rejected' ? 'Re-upload Card' : 'Get Started'}
              </Button>
            )}
          </Box>
        </Card>
      )}

      {/* ═══ Your Leadership ═══ */}
      <Box>
        <Typography
          sx={{
            fontFamily: FONT,
            fontWeight: 800,
            fontSize: { xs: '1.25rem', md: '1.4rem' },
            letterSpacing: '-0.02em',
            mb: 2.5,
          }}
        >
          Your Leadership
        </Typography>
        {leadersLoading ? (
          <Box
            sx={{
              display: 'flex',
              gap: 1.5,
              overflowX: 'auto',
              pb: 1,
              '&::-webkit-scrollbar': { display: 'none' },
            }}
          >
            {[1, 2, 3].map((i) => (
              <Skeleton
                key={i}
                variant="rounded"
                width={160}
                height={200}
                sx={{ borderRadius: 4, flexShrink: 0 }}
              />
            ))}
          </Box>
        ) : (
          <Box
            sx={{
              display: 'flex',
              gap: { xs: 1.5, md: 2 },
              overflowX: 'auto',
              pb: 1,
              '&::-webkit-scrollbar': { display: 'none' },
              scrollbarWidth: 'none',
            }}
          >
            {/* Peter Obi — always first */}
            <LeaderCard
              name="Peter Obi"
              subtitle="FOUNDER"
              image="/Peter-Obi.webp"
              onClick={() => setPeterObiOpen(true)}
            />
            {leaders.map((leader) => {
              const loc = levelLocationFor(leader);
              const subtitle = (loc
                ? `${loc} ${leader.designation}`
                : leader.designation
              ).toUpperCase();
              return (
                <LeaderCard
                  key={leader.id}
                  name={leader.name}
                  subtitle={subtitle}
                  image={leader.profileImage}
                  onClick={() => setSelectedLeader(leader)}
                />
              );
            })}
          </Box>
        )}
      </Box>

      {/* ═══ Quick Actions ═══ */}
      <Box>
        <Typography
          sx={{
            fontFamily: FONT,
            fontWeight: 800,
            fontSize: { xs: '1.25rem', md: '1.4rem' },
            letterSpacing: '-0.02em',
            mb: 2.5,
          }}
        >
          Quick Actions
        </Typography>
        <Grid container spacing={2}>
          {quickActions.map((action) => {
            const Icon = action.icon;
            const isExternal = 'external' in action && action.external;
            return (
              <Grid size={{ xs: 6, sm: 4, md: 2 }} key={action.label}>
                <Card
                  elevation={0}
                  sx={{
                    border: '1px solid',
                    borderColor: 'rgba(0,0,0,0.06)',
                    borderRadius: 4,
                    transition: 'all 0.2s',
                    '&:hover': {
                      borderColor: `${action.color}40`,
                      boxShadow: `0 8px 24px ${action.color}12`,
                      transform: 'translateY(-2px)',
                    },
                  }}
                >
                  <CardActionArea
                    {...(isExternal
                      ? { component: 'a', href: action.path, target: '_blank', rel: 'noopener noreferrer' }
                      : { component: Link, to: action.path })}
                    sx={{ p: { xs: 2.5, md: 3 }, textAlign: 'center' }}
                  >
                    <Box
                      sx={{
                        width: 48,
                        height: 48,
                        borderRadius: 3,
                        bgcolor: `${action.color}0D`,
                        color: action.color,
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        mx: 'auto',
                        mb: 1.5,
                        transition: 'all 0.2s',
                        '.MuiCardActionArea-root:hover &': {
                          bgcolor: action.color,
                          color: '#fff',
                        },
                      }}
                    >
                      <Icon size={22} />
                    </Box>
                    <Typography
                      sx={{
                        fontFamily: FONT,
                        fontWeight: 700,
                        fontSize: { xs: '0.75rem', md: '0.8rem' },
                      }}
                      noWrap
                    >
                      {action.label}
                    </Typography>
                    {isExternal && (
                      <ExternalLink size={10} style={{ position: 'absolute', top: 8, right: 8, opacity: 0.3 }} />
                    )}
                  </CardActionArea>
                </Card>
              </Grid>
            );
          })}
        </Grid>
      </Box>

      {/* ═══ Call-to-Action Cards ═══ */}
      {(() => {
        const ctaCards = [
          {
            key: 'cta_volunteer_url',
            title: 'Volunteer',
            desc: 'Join a directorate — help build the New Nigeria from your community.',
            icon: UserPlus,
            gradient: 'linear-gradient(135deg, #059669 0%, #10b981 100%)',
            shadow: 'rgba(5,150,105,0.25)',
          },
          {
            key: 'cta_run_for_office_url',
            title: 'Run for Office',
            desc: 'Ready to serve? Submit your interest for 2027 elections.',
            icon: Vote,
            gradient: 'linear-gradient(135deg, #2563eb 0%, #3b82f6 100%)',
            shadow: 'rgba(37,99,235,0.25)',
          },
          {
            key: 'cta_donate_url',
            title: 'Donate',
            desc: 'Support the movement — every contribution fuels change.',
            icon: Heart,
            gradient: 'linear-gradient(135deg, #7c3aed 0%, #8b5cf6 100%)',
            shadow: 'rgba(124,58,237,0.25)',
          },
          {
            key: 'cta_feedback_url',
            title: 'Give Feedback',
            desc: 'Your voice matters — share ideas, report issues, shape direction.',
            icon: MessageSquare,
            gradient: 'linear-gradient(135deg, #d97706 0%, #f59e0b 100%)',
            shadow: 'rgba(217,119,6,0.25)',
          },
        ].filter(c => ctaLinks[c.key]);

        if (ctaCards.length === 0) return null;

        return (
          <Box>
            <Typography
              sx={{
                fontFamily: FONT,
                fontWeight: 800,
                fontSize: { xs: '1.25rem', md: '1.4rem' },
                letterSpacing: '-0.02em',
                mb: 2.5,
              }}
            >
              Get Involved
            </Typography>
            <Box
              sx={{
                display: 'grid',
                gridTemplateColumns: {
                  xs: '1fr',
                  sm: ctaCards.length === 1 ? '1fr' : 'repeat(2, 1fr)',
                  md: `repeat(${Math.min(ctaCards.length, 4)}, 1fr)`,
                },
                gap: { xs: 1.5, md: 2 },
              }}
            >
              {ctaCards.map((cta) => {
                const Icon = cta.icon;
                return (
                  <Card
                    key={cta.key}
                    elevation={0}
                    component="a"
                    href={ctaLinks[cta.key]}
                    target="_blank"
                    rel="noopener noreferrer"
                    sx={{
                      textDecoration: 'none',
                      background: cta.gradient,
                      color: '#fff',
                      borderRadius: 4,
                      position: 'relative',
                      overflow: 'hidden',
                      cursor: 'pointer',
                      transition: 'all 0.25s cubic-bezier(0.16, 1, 0.3, 1)',
                      '&:hover': {
                        transform: 'translateY(-3px)',
                        boxShadow: `0 16px 40px ${cta.shadow}`,
                        '& .cta-arrow': {
                          transform: 'translate(2px, -2px)',
                        },
                        '& .cta-bg-glow': {
                          opacity: 0.18,
                        },
                      },
                      '&:active': {
                        transform: 'translateY(-1px) scale(0.985)',
                      },
                    }}
                  >
                    {/* Decorative arc */}
                    <Box
                      className="cta-bg-glow"
                      sx={{
                        position: 'absolute',
                        top: -40,
                        right: -40,
                        width: 130,
                        height: 130,
                        borderRadius: '50%',
                        background: 'rgba(255,255,255,0.12)',
                        transition: 'opacity 0.3s',
                        pointerEvents: 'none',
                      }}
                    />
                    <Box sx={{ p: { xs: 2.5, md: 3 }, position: 'relative', zIndex: 1 }}>
                      <Box
                        sx={{
                          display: 'flex',
                          alignItems: 'flex-start',
                          justifyContent: 'space-between',
                          mb: 2,
                        }}
                      >
                        <Box
                          sx={{
                            width: 40,
                            height: 40,
                            borderRadius: 2.5,
                            bgcolor: 'rgba(255,255,255,0.2)',
                            backdropFilter: 'blur(8px)',
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'center',
                          }}
                        >
                          <Icon size={20} strokeWidth={2.2} />
                        </Box>
                        <Box
                          className="cta-arrow"
                          sx={{
                            transition: 'transform 0.25s cubic-bezier(0.16, 1, 0.3, 1)',
                            opacity: 0.7,
                          }}
                        >
                          <ArrowUpRight size={18} />
                        </Box>
                      </Box>
                      <Typography
                        sx={{
                          fontFamily: FONT,
                          fontWeight: 800,
                          fontSize: { xs: '1rem', md: '1.05rem' },
                          letterSpacing: '-0.01em',
                          lineHeight: 1.2,
                          mb: 0.5,
                        }}
                      >
                        {cta.title}
                      </Typography>
                      <Typography
                        sx={{
                          fontFamily: FONT,
                          fontSize: { xs: '0.72rem', md: '0.78rem' },
                          fontWeight: 400,
                          lineHeight: 1.5,
                          opacity: 0.82,
                          display: '-webkit-box',
                          WebkitLineClamp: 2,
                          WebkitBoxOrient: 'vertical',
                          overflow: 'hidden',
                        }}
                      >
                        {cta.desc}
                      </Typography>
                    </Box>
                  </Card>
                );
              })}
            </Box>
          </Box>
        );
      })()}

      {/* ═══ Mobilization Pack Banner ═══ */}
      {mobilizationUrl && (
        <Card
          elevation={0}
          component="a"
          href={mobilizationUrl}
          target="_blank"
          rel="noopener noreferrer"
          sx={{
            display: 'flex',
            alignItems: 'center',
            gap: { xs: 2, md: 3 },
            p: { xs: 2.5, md: 3.5 },
            borderRadius: 5,
            cursor: 'pointer',
            textDecoration: 'none',
            background: `linear-gradient(135deg, ${PRIMARY} 0%, #00944d 50%, #8cc63f 100%)`,
            color: '#fff',
            transition: 'all 0.2s',
            '&:hover': {
              transform: 'translateY(-1px)',
              boxShadow: '0 12px 32px rgba(0,104,55,0.22)',
            },
          }}
        >
          <Box
            sx={{
              width: { xs: 48, md: 56 },
              height: { xs: 48, md: 56 },
              borderRadius: '50%',
              bgcolor: 'rgba(255,255,255,0.18)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              flexShrink: 0,
            }}
          >
            <Package size={26} />
          </Box>
          <Box sx={{ flex: 1, minWidth: 0 }}>
            <Typography
              sx={{
                fontFamily: FONT,
                fontWeight: 800,
                fontSize: { xs: '1rem', md: '1.15rem' },
                lineHeight: 1.3,
                letterSpacing: '-0.01em',
              }}
            >
              Mobilization Pack
            </Typography>
            <Typography
              sx={{
                fontFamily: FONT,
                fontSize: { xs: '0.75rem', md: '0.82rem' },
                opacity: 0.8,
                mt: 0.25,
              }}
            >
              Access campaign materials, flyers &amp; resources
            </Typography>
          </Box>
          <Box
            sx={{
              display: { xs: 'none', sm: 'flex' },
              alignItems: 'center',
              gap: 0.75,
              bgcolor: 'rgba(255,255,255,0.2)',
              borderRadius: 3,
              px: 2.5,
              py: 1,
              fontFamily: FONT,
              fontWeight: 700,
              fontSize: '0.8rem',
              flexShrink: 0,
              whiteSpace: 'nowrap',
              transition: 'background 0.15s',
              '&:hover': { bgcolor: 'rgba(255,255,255,0.3)' },
            }}
          >
            Open <ExternalLink size={14} />
          </Box>
        </Card>
      )}

      {/* ═══ Voting Blocs ═══ */}
      <Box>
            <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', mb: 2.5 }}>
              <Typography sx={{ fontFamily: FONT, fontWeight: 800, fontSize: { xs: '1.25rem', md: '1.4rem' }, letterSpacing: '-0.02em' }}>
                My Voting Blocs
              </Typography>
              <Button
                component={Link}
                to="/dashboard/voting-bloc"
                size="small"
                sx={{ textTransform: 'none', color: PRIMARY, fontFamily: FONT, fontWeight: 700, fontSize: '0.8rem' }}
              >
                View All
              </Button>
            </Box>

            {loading ? (
              <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1.5 }}>
                {[1, 2, 3].map((i) => (
                  <Skeleton key={i} variant="rounded" height={80} sx={{ borderRadius: 4 }} />
                ))}
              </Box>
            ) : ownedBlocs.length === 0 && joinedBlocs.length === 0 ? (
              <Card
                elevation={0}
                sx={{
                  border: '1px solid',
                  borderColor: 'rgba(0,0,0,0.06)',
                  borderRadius: 5,
                  p: { xs: 5, md: 7 },
                  textAlign: 'center',
                }}
              >
                <Box
                  sx={{
                    width: 64,
                    height: 64,
                    borderRadius: '50%',
                    bgcolor: '#f4f4f5',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    mx: 'auto',
                    mb: 2,
                  }}
                >
                  <Users size={28} color="#d4d4d8" />
                </Box>
                <Typography sx={{ fontFamily: FONT, fontWeight: 700, fontSize: '1.1rem', mb: 1 }}>
                  My Voting Blocs
                </Typography>
                <Typography sx={{ fontFamily: FONT, color: 'text.secondary', fontSize: '0.85rem', maxWidth: 280, mx: 'auto', mb: 3 }}>
                  You haven't joined or created any voting blocs yet. Start organizing your community today.
                </Typography>
                <Button
                  component={Link}
                  to="/dashboard/voting-bloc"
                  sx={{
                    fontFamily: FONT,
                    fontWeight: 700,
                    textTransform: 'none',
                    background: `linear-gradient(135deg, ${PRIMARY} 0%, #006b3e 100%)`,
                    color: '#fff',
                    borderRadius: 3,
                    px: 5,
                    py: 1.5,
                    boxShadow: `0 4px 16px ${PRIMARY}33`,
                    '&:hover': { transform: 'scale(1.02)' },
                    transition: 'all 0.15s',
                  }}
                >
                  Get Started
                </Button>
              </Card>
            ) : (
              <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1.5 }}>
                {[...ownedBlocs, ...joinedBlocs].slice(0, 6).map((bloc) => (
                  <Card
                    key={bloc._id}
                    elevation={0}
                    sx={{
                      bgcolor: '#f9fafb',
                      borderRadius: 4,
                      transition: 'all 0.2s',
                      cursor: 'pointer',
                      '&:hover': { bgcolor: '#f3f4f6' },
                    }}
                    onClick={() => navigate(`/dashboard/manage-voting-bloc/${bloc._id}`)}
                  >
                    <Box
                      sx={{
                        display: 'flex',
                        alignItems: 'center',
                        gap: 2,
                        p: { xs: 2, sm: 2.5 },
                      }}
                    >
                      <Box
                        sx={{
                          width: 48,
                          height: 48,
                          borderRadius: 3,
                          bgcolor: `${PRIMARY}0D`,
                          display: 'flex',
                          alignItems: 'center',
                          justifyContent: 'center',
                          flexShrink: 0,
                        }}
                      >
                        <Users size={20} color={PRIMARY} />
                      </Box>
                      <Box sx={{ flex: 1, minWidth: 0 }}>
                        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                          <Typography sx={{ fontFamily: FONT, fontWeight: 700, fontSize: '0.9rem' }} noWrap>
                            {bloc.name}
                          </Typography>
                          {bloc.isAutoGenerated && (
                            <Chip label="Auto" size="small" variant="outlined" sx={{ fontSize: '0.6rem', height: 20, borderRadius: 1 }} />
                          )}
                        </Box>
                        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5, mt: 0.75 }}>
                          <Box sx={{ width: 48, height: 5, bgcolor: '#e5e7eb', borderRadius: 4, overflow: 'hidden' }}>
                            <Box
                              sx={{
                                height: '100%',
                                width: `${Math.min(bloc.metrics?.engagementScore || 0, 100)}%`,
                                bgcolor: PRIMARY,
                                borderRadius: 4,
                              }}
                            />
                          </Box>
                          <Typography sx={{ fontFamily: FONT, fontSize: '0.65rem', fontWeight: 700, color: 'text.secondary' }}>
                            {bloc.metrics?.engagementScore || 0}% Active
                          </Typography>
                        </Box>
                      </Box>
                      <Box sx={{ textAlign: 'right', flexShrink: 0 }}>
                        <Typography sx={{ fontFamily: FONT, fontWeight: 800, fontSize: '0.85rem' }}>
                          {bloc.metrics?.totalMembers || 0}
                        </Typography>
                        <Typography sx={{ fontFamily: FONT, fontSize: '0.6rem', fontWeight: 700, color: 'text.disabled', textTransform: 'uppercase', letterSpacing: '0.02em' }}>
                          Members
                        </Typography>
                      </Box>
                    </Box>
                  </Card>
                ))}
              </Box>
            )}
      </Box>

      {/* ═══ Recent Notifications ═══ */}
      <Box>
            <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', mb: 2.5 }}>
              <Typography sx={{ fontFamily: FONT, fontWeight: 800, fontSize: { xs: '1.25rem', md: '1.4rem' }, letterSpacing: '-0.02em' }}>
                Recent Notifications
              </Typography>
              <Button
                component={Link}
                to="/dashboard/notifications"
                size="small"
                sx={{ textTransform: 'none', color: PRIMARY, fontFamily: FONT, fontWeight: 700, fontSize: '0.8rem' }}
              >
                View All
              </Button>
            </Box>

            {loading ? (
              <Skeleton variant="rounded" height={200} sx={{ borderRadius: 4 }} />
            ) : notifications.length === 0 ? (
              <Card
                elevation={0}
                sx={{
                  border: '1px solid',
                  borderColor: 'rgba(0,0,0,0.06)',
                  borderRadius: 4,
                  p: 5,
                  textAlign: 'center',
                }}
              >
                <Bell size={24} style={{ opacity: 0.2, margin: '0 auto 8px' }} />
                <Typography sx={{ fontFamily: FONT, fontSize: '0.85rem', color: 'text.secondary' }}>
                  No notifications yet
                </Typography>
              </Card>
            ) : (
              <Box sx={{ display: 'flex', flexDirection: 'column', gap: 0 }}>
                {notifications.map((notif, i) => (
                  <Box
                    key={notif._id || i}
                    onClick={() => navigate('/dashboard/notifications')}
                    sx={{
                      display: 'flex',
                      alignItems: 'flex-start',
                      gap: 2,
                      py: 2.5,
                      px: 1,
                      cursor: 'pointer',
                      borderBottom: i < notifications.length - 1 ? '1px solid' : 'none',
                      borderColor: 'rgba(0,0,0,0.04)',
                      borderRadius: 2,
                      '&:hover': { bgcolor: 'rgba(0,0,0,0.02)' },
                      transition: 'background 0.15s',
                    }}
                  >
                    <Box
                      sx={{
                        width: 8,
                        height: 8,
                        borderRadius: '50%',
                        bgcolor: notif.read ? '#d4d4d8' : PRIMARY,
                        mt: 0.75,
                        flexShrink: 0,
                        ...(notif.read
                          ? {}
                          : {
                              boxShadow: `0 0 0 3px ${PRIMARY}20`,
                            }),
                      }}
                    />
                    <Box sx={{ flex: 1, minWidth: 0 }}>
                      {notif.type && (
                        <Typography
                          sx={{
                            fontFamily: FONT,
                            fontSize: '0.6rem',
                            fontWeight: 800,
                            textTransform: 'uppercase',
                            letterSpacing: '0.08em',
                            color: PRIMARY,
                            mb: 0.25,
                          }}
                        >
                          {notif.type}
                        </Typography>
                      )}
                      <Typography
                        sx={{
                          fontFamily: FONT,
                          fontSize: '0.85rem',
                          fontWeight: notif.read ? 400 : 600,
                          lineHeight: 1.4,
                          color: 'text.primary',
                        }}
                        noWrap={false}
                      >
                        {notif.title || notif.message}
                      </Typography>
                      {notif.message && notif.title && (
                        <Typography sx={{ fontFamily: FONT, fontSize: '0.8rem', color: 'text.secondary', mt: 0.25 }} noWrap>
                          {notif.message}
                        </Typography>
                      )}
                      <Typography sx={{ fontFamily: FONT, fontSize: '0.65rem', fontWeight: 500, color: 'text.disabled', mt: 0.5 }}>
                        {notif.createdAt
                          ? new Date(notif.createdAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })
                          : ''}
                      </Typography>
                    </Box>
                  </Box>
                ))}
              </Box>
            )}
      </Box>

      {/* ═══ Leader Info Modal (for coordinators) ═══ */}
      <LeaderInfoModal
        leader={selectedLeader}
        onClose={() => setSelectedLeader(null)}
      />

      {/* ═══ Peter Obi Bio Dialog ═══ */}
      <Dialog
        open={peterObiOpen}
        onClose={() => setPeterObiOpen(false)}
        maxWidth="xs"
        fullWidth
        PaperProps={{
          sx: { borderRadius: 5, overflow: 'visible', boxShadow: '0 24px 64px rgba(0,0,0,0.12)' },
        }}
      >
        <Box sx={{ position: 'relative', textAlign: 'center' }}>
          <Box
            sx={{
              height: 96,
              background: `linear-gradient(135deg, ${PRIMARY} 0%, #006b3e 100%)`,
              borderRadius: '20px 20px 0 0',
            }}
          />
          <Button
            onClick={() => setPeterObiOpen(false)}
            sx={{
              position: 'absolute',
              top: 10,
              right: 10,
              minWidth: 0,
              p: 0.75,
              color: '#fff',
              bgcolor: 'rgba(255,255,255,0.15)',
              borderRadius: '50%',
              '&:hover': { bgcolor: 'rgba(255,255,255,0.3)' },
            }}
          >
            <X size={16} />
          </Button>
          <Avatar
            src="/Peter-Obi.webp"
            alt="Peter Obi"
            sx={{
              width: 96,
              height: 96,
              border: '4px solid #fff',
              mx: 'auto',
              mt: -6,
              boxShadow: '0 4px 24px rgba(0,0,0,0.12)',
            }}
          />
          <Box sx={{ px: 3, pb: 3.5, pt: 1.5 }}>
            <Typography
              sx={{
                fontFamily: FONT,
                fontWeight: 800,
                fontSize: '1.2rem',
                color: '#1a1c1c',
                letterSpacing: '-0.01em',
              }}
            >
              Peter Obi
            </Typography>
            <Chip
              label="FOUNDER"
              size="small"
              sx={{
                fontFamily: FONT,
                fontSize: '0.68rem',
                fontWeight: 700,
                height: 28,
                mt: 1,
                bgcolor: `${PRIMARY}14`,
                color: PRIMARY,
                borderRadius: 2,
                textTransform: 'uppercase',
                letterSpacing: '0.08em',
                border: '1px solid',
                borderColor: `${PRIMARY}26`,
              }}
            />
            <Typography
              sx={{
                fontFamily: FONT,
                fontSize: '0.6rem',
                fontWeight: 800,
                letterSpacing: '0.12em',
                color: 'text.secondary',
                textAlign: 'left',
                mt: 3,
                mb: 1.25,
              }}
            >
              ABOUT
            </Typography>
            <Box
              sx={{
                p: 2,
                borderRadius: 3,
                bgcolor: '#f9fafb',
                border: '1px solid rgba(0,0,0,0.05)',
                textAlign: 'left',
              }}
            >
              <Typography
                sx={{
                  fontFamily: FONT,
                  fontSize: '0.82rem',
                  lineHeight: 1.6,
                  color: '#374151',
                }}
              >
                Peter Gregory Obi is a Nigerian businessman and politician who
                served as the Governor of Anambra State from 2006 to 2014. He
                was the Vice Presidential candidate of the PDP in 2019 and the
                Presidential candidate of the Labour Party in the 2023 general
                elections. He is the Founder of the Obidient Movement.
              </Typography>
            </Box>
          </Box>
        </Box>
      </Dialog>

      {/* ═══ ADC Registration Modal ═══ */}
      <Dialog
        open={adcModalOpen}
        onClose={() => setAdcModalOpen(false)}
        maxWidth="xs"
        fullWidth
        PaperProps={{ sx: { borderRadius: 5, overflow: 'hidden' } }}
      >
        {adcStep === 'ask' && (
          <>
            <DialogTitle sx={{ fontFamily: FONT, fontWeight: 700, textAlign: 'center', pt: 3 }}>
              ADC Registration
            </DialogTitle>
            <DialogContent sx={{ textAlign: 'center', pb: 1 }}>
              <Typography sx={{ fontFamily: FONT, fontSize: '0.9rem', color: '#555', mb: 1 }}>
                Have you already registered as an ADC member?
              </Typography>
              {profile?.adcStatus === 'rejected' && (
                <Alert severity="warning" sx={{ mt: 1, fontFamily: FONT, fontSize: '0.8rem', textAlign: 'left' }}>
                  Your previous submission was rejected. Please upload a valid membership card.
                </Alert>
              )}
            </DialogContent>
            <DialogActions sx={{ justifyContent: 'center', gap: 1.5, pb: 3, px: 3 }}>
              <Button
                variant="contained"
                onClick={() => setAdcStep('upload')}
                sx={{
                  fontFamily: FONT,
                  fontWeight: 600,
                  textTransform: 'none',
                  borderRadius: 2,
                  px: 4,
                  bgcolor: PRIMARY,
                  '&:hover': { bgcolor: '#005530' },
                }}
              >
                Yes, Upload Card
              </Button>
              <Button
                variant="outlined"
                component="a"
                href="https://adcregistration.ng/"
                target="_blank"
                rel="noopener noreferrer"
                onClick={() => setAdcModalOpen(false)}
                sx={{
                  fontFamily: FONT,
                  fontWeight: 600,
                  textTransform: 'none',
                  borderRadius: 2,
                  px: 4,
                  color: PRIMARY,
                  borderColor: PRIMARY,
                  '&:hover': { borderColor: '#005530', bgcolor: 'rgba(0,104,55,0.04)' },
                }}
              >
                No, Register Now
              </Button>
            </DialogActions>
          </>
        )}

        {adcStep === 'upload' && (
          <>
            <DialogTitle sx={{ fontFamily: FONT, fontWeight: 700, textAlign: 'center', pt: 3 }}>
              Upload ADC Membership Card
            </DialogTitle>
            <DialogContent sx={{ textAlign: 'center' }}>
              <Typography sx={{ fontFamily: FONT, fontSize: '0.85rem', color: '#666', mb: 2.5 }}>
                Take a clear photo of your ADC membership card and upload it below.
              </Typography>

              {adcPreview ? (
                <Box sx={{ mb: 2 }}>
                  <Box
                    component="img"
                    src={adcPreview}
                    alt="Card preview"
                    sx={{
                      maxWidth: '100%',
                      maxHeight: 220,
                      borderRadius: 2,
                      border: '2px solid',
                      borderColor: 'divider',
                      objectFit: 'contain',
                    }}
                  />
                  <Typography
                    onClick={() => { setAdcPreview(null); setAdcBase64(null); }}
                    sx={{
                      fontFamily: FONT,
                      fontSize: '0.75rem',
                      color: '#d32f2f',
                      mt: 1,
                      cursor: 'pointer',
                      '&:hover': { textDecoration: 'underline' },
                    }}
                  >
                    Remove & re-upload
                  </Typography>
                </Box>
              ) : (
                <Button
                  variant="outlined"
                  component="label"
                  startIcon={<Upload size={18} />}
                  sx={{
                    fontFamily: FONT,
                    fontWeight: 600,
                    textTransform: 'none',
                    borderRadius: 2,
                    px: 4,
                    py: 1.5,
                    mb: 2,
                    width: '100%',
                    borderColor: PRIMARY,
                    color: PRIMARY,
                    borderStyle: 'dashed',
                    '&:hover': { borderColor: '#005530', bgcolor: 'rgba(0,104,55,0.04)' },
                  }}
                >
                  Select Image
                  <input type="file" accept="image/*" hidden onChange={handleAdcFileChange} />
                </Button>
              )}

              {adcError && (
                <Alert severity="error" sx={{ fontFamily: FONT, fontSize: '0.8rem', mb: 1 }}>
                  {adcError}
                </Alert>
              )}
            </DialogContent>
            <DialogActions sx={{ justifyContent: 'center', gap: 1.5, pb: 3, px: 3 }}>
              <Button
                onClick={() => setAdcStep('ask')}
                sx={{ fontFamily: FONT, textTransform: 'none', color: '#666' }}
              >
                Back
              </Button>
              <Button
                variant="contained"
                onClick={handleAdcSubmit}
                disabled={!adcBase64 || adcUploading}
                startIcon={adcUploading ? <CircularProgress size={16} color="inherit" /> : undefined}
                sx={{
                  fontFamily: FONT,
                  fontWeight: 600,
                  textTransform: 'none',
                  borderRadius: 2,
                  px: 4,
                  bgcolor: PRIMARY,
                  '&:hover': { bgcolor: '#005530' },
                }}
              >
                {adcUploading ? 'Uploading...' : 'Submit Card'}
              </Button>
            </DialogActions>
          </>
        )}

        {adcStep === 'done' && (
          <>
            <DialogContent sx={{ textAlign: 'center', py: 4 }}>
              <CheckCircle size={48} color={PRIMARY} style={{ marginBottom: 12 }} />
              <Typography sx={{ fontFamily: FONT, fontWeight: 700, fontSize: '1.1rem', mb: 1 }}>
                Card Submitted!
              </Typography>
              <Typography sx={{ fontFamily: FONT, fontSize: '0.85rem', color: '#666' }}>
                Your ADC membership card is now under review. You'll be notified once it's verified.
              </Typography>
            </DialogContent>
            <DialogActions sx={{ justifyContent: 'center', pb: 3 }}>
              <Button
                variant="contained"
                onClick={() => { setAdcModalOpen(false); window.location.reload(); }}
                sx={{
                  fontFamily: FONT,
                  fontWeight: 600,
                  textTransform: 'none',
                  borderRadius: 2,
                  px: 4,
                  bgcolor: PRIMARY,
                  '&:hover': { bgcolor: '#005530' },
                }}
              >
                Done
              </Button>
            </DialogActions>
          </>
        )}
      </Dialog>
    </Box>
  );
}

/* ─── Leader Card ─── */
interface LeaderCardProps {
  name: string;
  subtitle: string;
  image?: string | null;
  onClick: () => void;
}

function LeaderCard({ name, subtitle, image, onClick }: LeaderCardProps) {
  return (
    <Card
      elevation={0}
      onClick={onClick}
      sx={{
        flexShrink: 0,
        width: { xs: 150, md: 170 },
        borderRadius: 4,
        border: '1px solid rgba(0,0,0,0.06)',
        cursor: 'pointer',
        transition: 'all 0.2s',
        '&:hover': {
          borderColor: `${PRIMARY}40`,
          boxShadow: `0 8px 24px ${PRIMARY}14`,
          transform: 'translateY(-2px)',
        },
      }}
    >
      <Box
        sx={{
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          textAlign: 'center',
          p: { xs: 2, md: 2.5 },
        }}
      >
        <Avatar
          src={image || undefined}
          alt={name}
          imgProps={{ referrerPolicy: 'no-referrer' }}
          sx={{
            width: 72,
            height: 72,
            bgcolor: `${PRIMARY}14`,
            color: PRIMARY,
            fontFamily: FONT,
            fontWeight: 700,
            fontSize: '1.5rem',
            mb: 1.5,
          }}
        >
          {name?.[0]?.toUpperCase()}
        </Avatar>
        <Typography
          sx={{
            fontFamily: FONT,
            fontWeight: 700,
            fontSize: '0.85rem',
            color: '#111827',
            lineHeight: 1.2,
            width: '100%',
            overflow: 'hidden',
            textOverflow: 'ellipsis',
            whiteSpace: 'nowrap',
          }}
        >
          {name}
        </Typography>
        <Typography
          sx={{
            fontFamily: FONT,
            fontSize: '0.6rem',
            fontWeight: 700,
            letterSpacing: '0.08em',
            color: 'text.secondary',
            mt: 0.5,
            width: '100%',
            display: '-webkit-box',
            WebkitLineClamp: 2,
            WebkitBoxOrient: 'vertical',
            overflow: 'hidden',
          }}
        >
          {subtitle}
        </Typography>
      </Box>
    </Card>
  );
}
