import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router';
import { Box, Typography, Button, CircularProgress } from '@mui/material';
import { Users } from 'lucide-react';
import { getOwnedVotingBlocs } from '../../../services/votingBlocService';

const FONT = '"Poppins", sans-serif';

export default function MyVotingBlocRedirect() {
  const navigate = useNavigate();
  const [error, setError] = useState(false);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    getOwnedVotingBlocs()
      .then((data) => {
        const blocs = data.votingBlocs || [];
        const autoBloc = blocs.find((b: any) => b.isAutoGenerated);
        if (autoBloc) {
          navigate(`/dashboard/manage-voting-bloc/${autoBloc._id}`, { replace: true });
        } else if (blocs.length > 0) {
          navigate(`/dashboard/manage-voting-bloc/${blocs[0]._id}`, { replace: true });
        } else {
          setError(true);
          setLoading(false);
        }
      })
      .catch(() => {
        setError(true);
        setLoading(false);
      });
  }, [navigate]);

  if (loading && !error) {
    return (
      <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: 300 }}>
        <CircularProgress sx={{ color: '#006837' }} />
      </Box>
    );
  }

  return (
    <Box
      sx={{
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 400,
        gap: 3,
        textAlign: 'center',
        fontFamily: FONT,
      }}
    >
      <Users size={44} style={{ opacity: 0.25 }} />
      <Typography variant="h6" fontWeight={600} sx={{ fontFamily: FONT }}>
        No Voting Bloc Found
      </Typography>
      <Typography variant="body2" color="text.secondary" sx={{ maxWidth: 400, fontFamily: FONT }}>
        You don't have a voting bloc yet. Create one to start organising your community.
      </Typography>
      <Button
        variant="contained"
        onClick={() => navigate('/dashboard/new-voting-bloc')}
        sx={{
          mt: 2,
          textTransform: 'none',
          fontFamily: FONT,
          fontWeight: 600,
          borderRadius: 2.5,
          px: 4,
          py: 1.25,
          bgcolor: '#006837',
          '&:hover': { bgcolor: '#005030' },
        }}
      >
        Create Voting Bloc
      </Button>
    </Box>
  );
}
