import { Suspense, lazy, useEffect, useMemo, useState } from "react";
import {
  Users,
  MessageSquare,
  UserPlus,
  Activity,
  Eye,
  ArrowRight,
  Info,
  Vote,
  Zap,
  Sparkles,
  Target,
  MapPin,
  Phone,
  Share2,
  User,
} from "lucide-react";
import { useUser } from "../../../context/UserContext";
import { getOwnedVotingBlocs, getJoinedVotingBlocs } from "../../../services/votingBlocService";
import Loading from "../../../components/Loader";

interface DashboardOverviewProps {
  setActivePage: React.Dispatch<React.SetStateAction<string>>;
}

interface VotingBloc {
  _id: string;
  name: string;
  description: string;
  targetCandidate: string;
  location: {
    state: string;
    lga: string;
    ward?: string;
  };
  metrics: {
    totalMembers: number;
    engagementScore: number;
  };
  status: string;
  joinCode?: string;
  isAutoGenerated?: boolean;
}

import { useNavigate } from "react-router";

const ProfileCompletionModal = lazy(() => import("../../../components/ProfileCompletionModal"));
const VotingLocationModal = lazy(() => import("../../../components/VotingLocationModal"));
const EditProfileModal = lazy(() => import("../../profile/EditProfileModal"));
const TwitterFollowModal = lazy(() => import("../../../components/modals/TwitterFollowModal"));

export default function DashboardOverview({ setActivePage }: DashboardOverviewProps) {
  const { profile } = useUser();
  const [ownedVotingBlocs, setOwnedVotingBlocs] = useState<VotingBloc[]>([]);
  const [joinedVotingBlocs, setJoinedVotingBlocs] = useState<VotingBloc[]>([]);
  const [isFetchingBlocs, setIsFetchingBlocs] = useState(true);
  const [profileModalOpen, setProfileModalOpen] = useState(false);
  const [votingLocationModalOpen, setVotingLocationModalOpen] = useState(false);
  const [editProfileModalOpen, setEditProfileModalOpen] = useState(false);
  const [twitterFollowModalOpen, setTwitterFollowModalOpen] = useState(false);
  const [showShareModal, setShowShareModal] = useState(false);
  const navigate = useNavigate();

  const profileFirstName = useMemo(() => {
    if (!profile?.name) {
      return "Friend";
    }
    const [first = "Friend"] = profile.name.split(" ");
    return first || "Friend";
  }, [profile?.name]);

  // Calculate profile completion using the same logic as ProfileCompletionModal
  const calculateProfileCompletion = (profile: any) => {
    if (!profile) return 0;

    // Use the same field logic as ProfileCompletionModal
    const requiredFields = [
      { key: 'userName', label: 'Username', getValue: (p: any) => p.userName || p.personalInfo?.user_name },
      { key: 'gender', label: 'Gender', getValue: (p: any) => p.gender || p.personalInfo?.gender },
      { key: 'ageRange', label: 'Age Range', getValue: (p: any) => p.ageRange || p.personalInfo?.age_range },
      { key: 'stateOfOrigin', label: 'State of Origin', getValue: (p: any) => p.stateOfOrigin || p.personalInfo?.state_of_origin },
      { key: 'votingState', label: 'Voting State', getValue: (p: any) => p.votingState || p.personalInfo?.voting_engagement_state },
      { key: 'votingLGA', label: 'Voting LGA', getValue: (p: any) => p.votingLGA || p.personalInfo?.lga },
      { key: 'votingWard', label: 'Voting Ward', getValue: (p: any) => p.votingWard || p.personalInfo?.ward },
      { key: 'votingPU', label: 'Voting Polling Unit', getValue: (p: any) => p.votingPU || p.personalInfo?.voting_pu },
      { key: 'citizenship', label: 'Citizenship', getValue: (p: any) => p.citizenship || p.personalInfo?.citizenship },
      { key: 'isVoter', label: 'Voter Status', getValue: (p: any) => p.isVoter || p.onboardingData?.votingBehavior?.is_registered },
      { key: 'willVote', label: 'Voting Intention', getValue: (p: any) => p.willVote || p.onboardingData?.votingBehavior?.likely_to_vote },
      { key: 'profileImage', label: 'Profile Image', getValue: (p: any) => p.profileImage }
    ];

    const completedFields = requiredFields.filter(field => {
      const value = field.getValue(profile);
      return value && value.toString().trim() !== '';
    });

    const missingFields = requiredFields.filter(field => {
      const value = field.getValue(profile);
      return !value || value.toString().trim() === '';
    });

    const completionScore = (completedFields.length / requiredFields.length) * 100;

    if (import.meta.env.DEV) {
      console.log('🔍 Profile completion calculation (frontend):', {
        completionScore: completionScore.toFixed(1),
        completedFields: completedFields.length,
        totalFields: requiredFields.length,
        missingFields: missingFields.map(f => f.label),
        fieldValues: requiredFields.map(field => ({
          key: field.key,
          value: field.getValue(profile) || 'MISSING'
        }))
      });
    }

    return completionScore;
  };

  // Check if voting location is complete
  const isVotingLocationComplete = (profile: any) => {
    if (!profile) return false;

    const votingFields = [
      { key: 'votingState', getValue: (p: any) => p.votingState || p.personalInfo?.voting_engagement_state },
      { key: 'votingLGA', getValue: (p: any) => p.votingLGA || p.personalInfo?.lga },
      { key: 'votingWard', getValue: (p: any) => p.votingWard || p.personalInfo?.ward },
      { key: 'votingPU', getValue: (p: any) => p.votingPU || p.personalInfo?.voting_pu }
    ];

    const missingFields = votingFields.filter(field => {
      const value = field.getValue(profile);
      return !value || value.toString().trim() === '';
    });

    if (import.meta.env.DEV) {
      console.log('🔍 Voting location check:', {
        isComplete: missingFields.length === 0,
        missingFields: missingFields.map(f => f.key),
        votingState: votingFields[0].getValue(profile) || 'MISSING',
        votingLGA: votingFields[1].getValue(profile) || 'MISSING',
        votingWard: votingFields[2].getValue(profile) || 'MISSING',
        votingPU: votingFields[3].getValue(profile) || 'MISSING'
      });
    }

    return missingFields.length === 0;
  };

  useEffect(() => {
    let isMounted = true;
    setIsFetchingBlocs(true);

    Promise.all([getOwnedVotingBlocs(), getJoinedVotingBlocs()])
      .then(([ownedData, joinedData]) => {
        if (!isMounted) return;
        setOwnedVotingBlocs(ownedData.votingBlocs || []);
        setJoinedVotingBlocs(joinedData.votingBlocs || []);
      })
      .catch((error) => {
        if (import.meta.env.DEV) {
          console.error("Error fetching dashboard voting bloc data:", error);
        }
      })
      .finally(() => {
        if (isMounted) {
          setIsFetchingBlocs(false);
        }
      });

    return () => {
      isMounted = false;
    };
  }, []);

  // Modal logic: Prioritize voting location completion over general profile completion
  useEffect(() => {
    if (profile && !isFetchingBlocs) {
      const votingLocationComplete = isVotingLocationComplete(profile);
      const completionScore = calculateProfileCompletion(profile);

      // First priority: Voting location completion
      if (!votingLocationComplete) {
        console.log('�️ Voting location incomplete, showing voting location modal in 1.5 seconds...');
        const timer = setTimeout(() => {
          setVotingLocationModalOpen(true);
        }, 1500);
        return () => clearTimeout(timer);
      }
      // Second priority: General profile completion
      else if (completionScore < 100) {
        console.log('🔍 Profile incomplete, showing profile modal in 1.5 seconds...');
        const timer = setTimeout(() => {
          setProfileModalOpen(true);
        }, 1500);
        return () => clearTimeout(timer);
      } else {
        console.log('✅ Profile is 100% complete, not showing modal');
      }
    }
  }, [profile, isFetchingBlocs]);

  // Twitter follow modal logic: Show after completion modals
  useEffect(() => {
    if (profile && !isFetchingBlocs) {
      const votingLocationComplete = isVotingLocationComplete(profile);
      const completionScore = calculateProfileCompletion(profile);
      const lastDismissed = localStorage.getItem('twitter-follow-dismissed');
      const lastShown = localStorage.getItem('twitter-follow-last-shown');
      const currentTime = Date.now();

      // Don't show if dismissed in the last 7 days
      const dismissedRecently = lastDismissed && (currentTime - parseInt(lastDismissed)) < (7 * 24 * 60 * 60 * 1000);

      // Don't show if already shown in the last 24 hours
      const shownRecently = lastShown && (currentTime - parseInt(lastShown)) < (24 * 60 * 60 * 1000);

      if (!dismissedRecently && !shownRecently) {
        // Calculate delay based on what modal is showing first
        let delay = 2000; // Default delay
        if (!votingLocationComplete) {
          delay = 5000; // Show later if voting location modal is shown first
        } else if (completionScore < 100) {
          delay = 4000; // Show later if profile modal is shown first
        }

        const timer = setTimeout(() => {
          setTwitterFollowModalOpen(true);
          localStorage.setItem('twitter-follow-last-shown', currentTime.toString());
        }, delay);
        return () => clearTimeout(timer);
      }
    }
  }, [profile, isFetchingBlocs]);

  // Handler to navigate to auto voting bloc
  function handleVisitAutoVotingBloc() {
    const autoBloc = ownedVotingBlocs.find((bloc: any) => bloc.isAutoGenerated);
    if (autoBloc) {
      navigate(`/dashboard/manage-voting-bloc/${autoBloc._id}`);
    } else {
      alert('No auto-generated voting bloc found for your account.');
    }
  }

  // Handler to open share modal for voting bloc
  const handleShareVotingBloc = () => {
    const autoBloc = ownedVotingBlocs.find((bloc: any) => bloc.isAutoGenerated);
    if (autoBloc) {
      setShowShareModal(true);
    } else {
      alert('No voting bloc found to share. Please create one first.');
    }
  };

  // Share to social media platforms
  const shareToSocialMedia = (platform: string) => {
    const autoBloc = ownedVotingBlocs.find((bloc: any) => bloc.isAutoGenerated);
    if (!autoBloc) return;

    const shareUrl = `${window.location.origin}/voting-bloc/${autoBloc.joinCode}`;
    const shareText = `Join my voting bloc "${autoBloc.name}" to support ${autoBloc.targetCandidate}! Together we can make a difference in ${autoBloc.location?.state || 'Nigeria'}.`;

    const encodedUrl = encodeURIComponent(shareUrl);
    const encodedText = encodeURIComponent(shareText);

    let shareLink = '';

    switch (platform) {
      case 'whatsapp':
        shareLink = `https://wa.me/?text=${encodedText}%20${encodedUrl}`;
        break;
      case 'twitter':
        shareLink = `https://twitter.com/intent/tweet?text=${encodedText}&url=${encodedUrl}`;
        break;
      case 'facebook':
        shareLink = `https://www.facebook.com/sharer/sharer.php?u=${encodedUrl}&quote=${encodedText}`;
        break;
      case 'linkedin':
        shareLink = `https://www.linkedin.com/sharing/share-offsite/?url=${encodedUrl}`;
        break;
      case 'telegram':
        shareLink = `https://t.me/share/url?url=${encodedUrl}&text=${encodedText}`;
        break;
      default:
        return;
    }

    if (shareLink) {
      window.open(shareLink, '_blank', 'noopener,noreferrer');
    }
  };

  // Copy voting bloc link
  const copyBlocLink = () => {
    const autoBloc = ownedVotingBlocs.find((bloc: any) => bloc.isAutoGenerated);
    if (autoBloc) {
      const shareUrl = `${window.location.origin}/voting-bloc/${autoBloc.joinCode}`;
      navigator.clipboard.writeText(shareUrl);
      alert('Voting bloc link copied to clipboard!');
    }
  };

  // Check if user is coordinator or admin
  const isCoordinator = profile?.designation && [
    'National Coordinator',
    'State Coordinator',
    'LGA Coordinator',
    'Ward Coordinator'
  ].includes(profile.designation);

  const canAccessStateDashboard = profile?.role === 'admin' || isCoordinator;

  const totalMembers = useMemo(
    () => ownedVotingBlocs.reduce((sum, bloc) => sum + (bloc.metrics?.totalMembers || 0), 0),
    [ownedVotingBlocs]
  );

  const totalEngagement = useMemo(
    () => ownedVotingBlocs.reduce((sum, bloc) => sum + (bloc.metrics?.engagementScore || 0), 0),
    [ownedVotingBlocs]
  );

  const stats = useMemo(
    () => [
      { label: "Joined Voting Blocs", value: isFetchingBlocs ? "—" : joinedVotingBlocs.length, icon: Users },
      { label: "Created Voting Blocs", value: isFetchingBlocs ? "—" : ownedVotingBlocs.length, icon: Vote },
      { label: "Total Members", value: isFetchingBlocs ? "—" : totalMembers, icon: UserPlus },
      {
        label: "Avg Engagement",
        value:
          isFetchingBlocs || ownedVotingBlocs.length === 0
            ? "—"
            : Math.round(totalEngagement / ownedVotingBlocs.length),
        icon: Activity,
      },
      { label: "Messages Sent", value: 0, icon: MessageSquare },
      { label: "Goals Achieved", value: 0, icon: Target },
    ],
    [isFetchingBlocs, joinedVotingBlocs.length, ownedVotingBlocs.length, totalEngagement, totalMembers]
  );

  // Define feature cards
  const featureCards = [
    {
      title: "Run for Office Hub",
      description: "Resources to help you run for political office.",
      icon: <Activity size={28} />,
      color: "bg-pink-50 text-pink-600",
      page: "Run for Office Hub",
      image: "/215971.jpg",
    },
    {
      title: "Election Monitoring",
      description: "Monitor election activities and report incidents.",
      icon: <Eye size={28} />,
      color: "bg-amber-50 text-amber-600",
      page: "Monitor",
      image: "/15997.jpg",
    },
  ];

  return (
    <div className="max-w-7xl mx-auto p-4 md:p-6 font-poppins space-y-8">
      {/* Welcome Banner */}
      <div className="bg-gradient-to-r from-[#006837] to-[#8cc63f] p-6 md:p-8 rounded-2xl shadow-md text-white">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center">
          <div className="flex items-center gap-6">
            <img
              src={profile?.profileImage || "/default-avatar.png"}
              alt={profile?.name}
              className="w-16 h-16 md:w-20 md:h-20 rounded-full border-2 border-white object-cover shadow-md"
            />
            <div>
              <h1 className="text-xl md:text-2xl font-bold">Welcome back, {profileFirstName}!</h1>
              <p className="text-sm md:text-base text-white/90">
                Make a civic impact today with Obidient Movement.
              </p>
            </div>
          </div>
          <button
            className="mt-4 md:mt-0 px-4 py-2 bg-white text-[#006837] rounded-lg hover:bg-gray-100 transition shadow-sm font-medium flex items-center gap-2"
            onClick={() => setActivePage("My Profile")}
          >
            View Profile <ArrowRight size={16} />
          </button>
        </div>
      </div>

      {/* Quick Actions Section - Key Navigation */}
      <div className="bg-gradient-to-br from-gray-50 to-white rounded-2xl border-2 border-[#8cc63f]/20 p-6 md:p-8">
        <div className="flex items-center gap-3 mb-6">
          <div>
            <h2 className="text-xl md:text-2xl font-bold text-gray-900">Quick Actions</h2>
          </div>
        </div>

        <div className="grid grid-cols-2 md:grid-cols-3 gap-3 md:gap-4">
          {/* Voting Bloc Management */}
          <button
            onClick={handleVisitAutoVotingBloc}
            disabled={isFetchingBlocs}
            className="group relative bg-white border border-gray-200 hover:border-gray-300 rounded-lg p-4 md:p-6 transition-all duration-200 hover:shadow-md disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <div className="flex flex-col items-center text-center gap-3">
              <div className="p-2.5 bg-gray-50 group-hover:bg-gray-100 rounded-lg transition-colors">
                <Vote size={24} className="text-gray-700" />
              </div>
              <div>
                <h3 className="font-semibold text-gray-900 text-sm md:text-base">
                  Voting Bloc
                </h3>
                <p className="text-xs text-gray-500 mt-1">
                  Manage your bloc
                </p>
              </div>
            </div>
          </button>

          {/* Share Voting Bloc */}
          <button
            onClick={handleShareVotingBloc}
            disabled={isFetchingBlocs}
            className="group relative bg-white border border-gray-200 hover:border-gray-300 rounded-lg p-4 md:p-6 transition-all duration-200 hover:shadow-md disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <div className="flex flex-col items-center text-center gap-3">
              <div className="p-2.5 bg-gray-50 group-hover:bg-gray-100 rounded-lg transition-colors">
                <Share2 size={24} className="text-gray-700" />
              </div>
              <div>
                <h3 className="font-semibold text-gray-900 text-sm md:text-base">
                  Share Bloc
                </h3>
                <p className="text-xs text-gray-500 mt-1">
                  Invite members
                </p>
              </div>
            </div>
          </button>

          {/* Monitor Elections */}
          <button
            onClick={() => navigate('/dashboard/elections/monitor')}
            className="group relative bg-white border border-gray-200 hover:border-gray-300 rounded-lg p-4 md:p-6 transition-all duration-200 hover:shadow-md"
          >
            <div className="flex flex-col items-center text-center gap-3">
              <div className="p-2.5 bg-gray-50 group-hover:bg-gray-100 rounded-lg transition-colors">
                <Eye size={24} className="text-gray-700" />
              </div>
              <div>
                <h3 className="font-semibold text-gray-900 text-sm md:text-base">
                  Monitor
                </h3>
                <p className="text-xs text-gray-500 mt-1">
                  Track elections
                </p>
              </div>
            </div>
          </button>

          {/* State Dashboard - Only for coordinators/admins */}
          {canAccessStateDashboard && (
            <button
              onClick={() => setActivePage('State Dashboard')}
              className="group relative bg-white border border-gray-200 hover:border-gray-300 rounded-lg p-4 md:p-6 transition-all duration-200 hover:shadow-md"
            >
              <div className="flex flex-col items-center text-center gap-3">
                <div className="p-2.5 bg-gray-50 group-hover:bg-gray-100 rounded-lg transition-colors">
                  <MapPin size={24} className="text-gray-700" />
                </div>
                <div>
                  <h3 className="font-semibold text-gray-900 text-sm md:text-base">
                    State Dashboard
                  </h3>
                  <p className="text-xs text-gray-500 mt-1">
                    Overview & stats
                  </p>
                </div>
              </div>
            </button>
          )}

          {/* Call Center - Open to all users */}
          <a
            href="/dashboard/call-center/volunteer"
            target="_blank"
            rel="noopener noreferrer"
            className="group relative bg-white border border-gray-200 hover:border-gray-300 rounded-lg p-4 md:p-6 transition-all duration-200 hover:shadow-md"
          >
            <div className="flex flex-col items-center text-center gap-3">
              <div className="p-2.5 bg-gray-50 group-hover:bg-gray-100 rounded-lg transition-colors">
                <Phone size={24} className="text-gray-700" />
              </div>
              <div>
                <h3 className="font-semibold text-gray-900 text-sm md:text-base">
                  Call Center
                </h3>
                <p className="text-xs text-gray-500 mt-1">
                  Volunteer center
                </p>
              </div>
            </div>
          </a>

          {/* My Profile */}
          <button
            onClick={() => setActivePage('My Profile')}
            className="group relative bg-white border border-gray-200 hover:border-gray-300 rounded-lg p-4 md:p-6 transition-all duration-200 hover:shadow-md"
          >
            <div className="flex flex-col items-center text-center gap-3">
              <div className="p-2.5 bg-gray-50 group-hover:bg-gray-100 rounded-lg transition-colors">
                <User size={24} className="text-gray-700" />
              </div>
              <div>
                <h3 className="font-semibold text-gray-900 text-sm md:text-base">
                  My Profile
                </h3>
                <p className="text-xs text-gray-500 mt-1">
                  Edit details
                </p>
              </div>
            </div>
          </button>
        </div>
      </div>

      {/* PVC Campaign Banner */}
      <div className="flex justify-center">
        <a
          href="https://drive.google.com/file/d/13WlMN9-hVm07Nj7u5sWTLHX4VShXPGPl/view?usp=sharing" // Replace with actual YouTube URL
          target="_blank"
          rel="noopener noreferrer"
          className="block hover:scale-105 transition-transform duration-300 shadow-lg hover:shadow-xl rounded-lg overflow-hidden relative group"
        >
          <img
            src="/ObiMERD2.png"
            alt="Get Your PVC & GO MERD - Make Election Rigging Difficult"
            loading="lazy"
            className="w-full max-w-7xl h-auto rounded-lg"
          />
          {/* Overlay Text Pill */}
          <div className="absolute bottom-2 right-2 max-w-xs md:bottom-4 md:right-4 bg-black/30 backdrop-blur-sm text-white px-2 py-1 md:px-4 md:py-2 rounded-full text-[8px] md:text-sm font-medium transition-all duration-300 group-hover:bg-black/80 group-hover:scale-105 flex items-center gap-1 md:gap-2">
            <span>Click here</span>
            <ArrowRight size={8} className="md:hidden group-hover:translate-x-1 transition-transform" />
            <ArrowRight size={14} className="hidden md:block group-hover:translate-x-1 transition-transform" />
          </div>
        </a>
      </div>

      {/* Voting Bloc Call-to-Action Section */}
      <div className="relative bg-gradient-to-br from-gray-800 via-gray-700 to-gray-900 rounded-2xl overflow-hidden shadow-xl">
        <div className="relative p-6 md:p-8 lg:p-10">
          <div className="flex flex-col lg:flex-row items-center gap-8">
            {/* Content */}
            <div className="flex-1 text-center lg:text-left">
              <div className="flex items-center justify-center lg:justify-start gap-2 mb-4">
                <div className="p-2 bg-white/20 rounded-full">
                  <Vote size={24} className="text-white" />
                </div>
                <span className="text-white/90 text-sm font-medium uppercase tracking-wider">
                  Take Action in <span className="text-[#8cc63f]">{profile?.votingState || profile?.personalInfo?.voting_engagement_state || 'Your'} State</span>
                </span>
              </div>

              <h2 className="text-2xl md:text-3xl lg:text-4xl font-bold text-white mb-4 leading-tight">
                Mobilize your <span className="text-[#8cc63f]">Polling Unit</span> in <span className="text-[#8cc63f]">{profile?.votingLGA || profile?.personalInfo?.lga || 'Your'} LGA</span>
                <br />
                <span className="text-lg md:text-xl lg:text-2xl font-normal text-white/90">
                  Unite voices, drive change
                </span>
              </h2>

              <p className="text-white/80 text-base md:text-lg mb-6 max-w-2xl">
                Create a powerful coalition of like-minded citizens. Organize voters,
                build a vote defender squad, and amplify the political impact of the Obidient movement in your community.
              </p>

              {/* Feature Highlights */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8">
                <div className="flex items-center gap-3 text-white/90">
                  <div className="p-2 bg-white/20 rounded-lg">
                    <Users size={18} />
                  </div>
                  <span className="text-sm font-medium">Get Your PVC</span>
                </div>
                <div className="flex items-center gap-3 text-white/90">
                  <div className="p-2 bg-white/20 rounded-lg">
                    <Target size={18} />
                  </div>
                  <span className="text-sm font-medium">Vote Right</span>
                </div>
                <div className="flex items-center gap-3 text-white/90">
                  <div className="p-2 bg-white/20 rounded-lg">
                    <Zap size={18} />
                  </div>
                  <span className="text-sm font-medium">Defend Your Vote</span>
                </div>
              </div>

              {/* CTA Buttons */}
              <div className="flex flex-col sm:flex-row gap-4 justify-center lg:justify-start">
                <button
                  onClick={handleVisitAutoVotingBloc}
                  className="group bg-[#8cc63f] text-white px-6 py-3 rounded-xl font-semibold hover:bg-[#7bb12f] transition-all duration-300 transform hover:scale-105 shadow-lg flex items-center justify-center gap-2"
                >
                  <Sparkles size={20} className="group-hover:rotate-12 transition-transform" />
                  Visit Your Bloc Now
                  <ArrowRight size={18} className="group-hover:translate-x-1 transition-transform" />
                </button>

                <button
                  onClick={() => setActivePage("Leaderboard")}
                  className="group bg-white/10 backdrop-blur-sm text-white border border-white/30 px-6 py-3 rounded-xl font-medium hover:bg-white/20 transition-all duration-300 flex items-center justify-center gap-2"
                >
                  <Eye size={20} />
                  See Leaderboard
                  <ArrowRight size={18} className="group-hover:translate-x-1 transition-transform" />
                </button>
              </div>

              {/* Mobile Founder Motivation */}
              <div className="lg:hidden mt-8 pt-6 border-t border-white/20">
                <div className=" rounded-xl p-8">
                  <div className="flex flex-col items-center text-center gap-6">
                    <div className="relative">
                      <img
                        src="/Peter-Obi.webp"
                        alt="Peter Obi - Founder"
                        loading="lazy"
                        className="w-32 h-32 md:w-36 md:h-36 rounded-full object-cover border-4 border-white/30 shadow-xl"
                      />
                      <div className="absolute -top-2 -right-2 w-8 h-8 bg-[#8cc63f] rounded-full flex items-center justify-center shadow-lg">
                        <Sparkles size={14} className="text-white" />
                      </div>
                    </div>
                    <div className="space-y-3">
                      <p className="text-white text-lg md:text-xl font-semibold leading-relaxed">
                        "Build the movement,<br />unite the people"
                      </p>
                      <p className="text-white/90 text-base font-medium">
                        - Peter Obi, Founder
                      </p>
                      <p className="text-white/70 text-sm max-w-xs mx-auto">
                        Join thousands creating positive change across Nigeria
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Founder Motivation Visual */}
            <div className="flex-shrink-0 hidden lg:block">
              <div className="relative">
                {/* Founder Image with Motivational Design */}
                <div className="w-96 h-9 rounded-3xl p-8 flex flex-col items-center justify-center">
                  <div className="relative mb-6">
                    <img
                      src="/Peter-Obi.webp"
                      alt="Peter Obi - Founder"
                      loading="lazy"
                      className="w-56 h-56 rounded-full object-cover border-4 border-white/30 shadow-2xl"
                    />
                    {/* Simple motivational accent */}
                    <div className="absolute -top-2 -right-2 w-10 h-10 bg-[#8cc63f] rounded-full flex items-center justify-center shadow-xl">
                      <Sparkles size={18} className="text-white" />
                    </div>
                  </div>
                  <div className="text-center space-y-3">
                    <p className="text-white text-xl font-bold leading-relaxed">
                      "Build the movement,<br />unite the people"
                    </p>
                    <p className="text-white/90 text-base font-medium">
                      - Peter Obi, Founder
                    </p>
                    <p className="text-white/70 text-sm max-w-xs">
                      Leading Nigeria's democratic transformation
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Member Actions Promotional Section */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-3 md:gap-4">
        {/* Ready to Serve Card */}
        <div className="bg-white rounded-lg border shadow-sm hover:shadow-md transition p-3 md:p-4">
          <div className="flex items-start gap-3">
            <div className="p-2 bg-green-100 rounded-full flex-shrink-0">
              <Users size={18} className="text-green-600" />
            </div>
            <div className="flex-1 min-w-0">
              <h2 className="text-sm md:text-base font-medium text-gray-800 mb-1">Ready to volunteer in a Directorate?</h2>
              <p className="text-xs md:text-sm font-normal text-gray-600 mb-3">We're looking for committed citizens ready to build a New Nigeria.</p>
              <button
                onClick={() => window.open('https://airtable.com/apppzNRujCOPHOs94/shrFnoRGia5YiQasZ', '_blank')}
                className="inline-flex items-center px-3 py-1.5 bg-gradient-to-r from-green-500 to-green-600 text-white font-medium rounded-md hover:from-green-600 hover:to-green-700 transition-colors duration-200 shadow-sm hover:shadow text-xs"
              >
                <UserPlus size={14} className="mr-1.5" />
                Join a Directorate
                <ArrowRight size={14} className="ml-1.5" />
              </button>
            </div>
          </div>
        </div>

        {/* Ready to Run for Office Card */}
        <div className="bg-white rounded-lg border shadow-sm hover:shadow-md transition p-3 md:p-4">
          <div className="flex items-start gap-3">
            <div className="p-2 bg-blue-100 rounded-full flex-shrink-0">
              <Vote size={18} className="text-blue-600" />
            </div>
            <div className="flex-1 min-w-0">
              <h2 className="text-sm md:text-base font-medium text-gray-800 mb-1">Ready to Run for Public Office in 2027?</h2>
              <p className="text-xs md:text-sm font-normal text-gray-600 mb-3">Submit your interest to run for local, state, or national elective public office.</p>
              <button
                onClick={() => window.open('https://airtable.com/apppzNRujCOPHOs94/shrw5U5T2X5YuzkVo', '_blank')}
                className="inline-flex items-center px-3 py-1.5 bg-gradient-to-r from-blue-500 to-blue-600 text-white font-medium rounded-md hover:from-blue-600 hover:to-blue-700 transition-colors duration-200 shadow-sm hover:shadow text-xs"
              >
                <Vote size={14} className="mr-1.5" />
                Submit your Interest
                <ArrowRight size={14} className="ml-1.5" />
              </button>
            </div>
          </div>
        </div>

        {/* Got Feedback Card */}
        <div className="bg-white rounded-lg border shadow-sm hover:shadow-md transition p-3 md:p-4">
          <div className="flex items-start gap-3">
            <div className="p-2 bg-yellow-100 rounded-full flex-shrink-0">
              <MessageSquare size={18} className="text-yellow-600" />
            </div>
            <div className="flex-1 min-w-0">
              <h2 className="text-sm md:text-base font-medium text-gray-800 mb-1">Got feedback?</h2>
              <p className="text-xs md:text-sm font-normal text-gray-600 mb-3">This is your space to speak up.</p>
              <button
                onClick={() => window.open('https://airtable.com/apppzNRujCOPHOs94/shrKjgILZBOktw58M', '_blank')}
                className="inline-flex items-center px-3 py-1.5 bg-gradient-to-r from-yellow-500 to-yellow-600 text-white font-medium rounded-md hover:from-yellow-600 hover:to-yellow-700 transition-colors duration-200 shadow-sm hover:shadow text-xs"
              >
                <MessageSquare size={14} className="mr-1.5" />
                Drop a feedback
                <ArrowRight size={14} className="ml-1.5" />
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Feature Highlight */}
      <div>
        <div className="flex justify-between items-center mb-4">
          <h2 className="text-lg md:text-xl font-semibold text-gray-800">Explore Features</h2>
          <div className="flex items-center gap-2 bg-blue-50 text-blue-700 px-3 py-1 rounded-full text-xs">
            <Info size={14} />
            <span>Discover what Obidient Movement offers</span>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-6">
          {featureCards.map((feature) => (
            <div
              key={feature.title}
              className="bg-white rounded-xl overflow-hidden shadow-sm border hover:shadow-md transition group cursor-pointer"
              onClick={() => setActivePage(feature.page)}
            >
              {feature.image && (
                <div className="w-full h-36 relative overflow-hidden">
                  <img
                    src={feature.image}
                    alt={feature.title}
                    loading="lazy"
                    className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
                  />
                </div>
              )}
              <div className="p-5">
                <div className="flex items-start gap-3 mb-2">
                  <div className={`p-2 ${feature.color} rounded-lg`}>
                    {feature.icon}
                  </div>
                  <div>
                    <h3 className="font-semibold text-gray-800 group-hover:text-[#006837]">{feature.title}</h3>
                    <p className="text-sm text-gray-600 mt-1">{feature.description}</p>
                  </div>
                </div>
                <div className="mt-4 flex justify-end">
                  <span className="text-xs font-medium flex items-center gap-1 text-[#006837] group-hover:translate-x-1 transition-transform">
                    Explore <ArrowRight size={14} />
                  </span>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Stats Cards */}
      <div>
        <h2 className="text-lg md:text-xl font-semibold text-gray-800 mb-4">Your Activity</h2>
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
          {stats.map(({ label, value, icon: Icon }) => (
            <div
              key={label}
              className="bg-white p-4 rounded-xl shadow-sm border hover:shadow-md transition"
            >
              <div className="flex items-center gap-3 mb-2">
                <div className="p-2 bg-[#006837]/10 rounded-full">
                  <Icon className="w-4 h-4 text-[#006837]" />
                </div>
                <span className="text-sm text-gray-600">{label}</span>
              </div>
              <div className="text-xl font-bold text-gray-800">{value}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Voting Bloc List Section */}
      <div className="bg-white p-4 sm:p-5 rounded-xl shadow-sm border border-gray-100">
        <div className="flex flex-wrap justify-between items-center gap-3 mb-4">
          <div className="flex items-center gap-2">
            <Vote size={18} className="text-[#006837]" />
            <h2 className="text-lg font-medium text-gray-800">Your Voting Blocs</h2>
          </div>
          <button
            onClick={() => setActivePage("Create your Voting Bloc")}
            className="px-3 py-1.5 bg-[#006837] text-white rounded-lg hover:bg-[#004d2a] transition flex items-center gap-1.5 text-sm"
          >
            <Vote size={14} /> Create
          </button>
        </div>

        {isFetchingBlocs ? (
          <div className="py-12 flex justify-center">
            <Loading />
          </div>
        ) : ownedVotingBlocs.length === 0 && joinedVotingBlocs.length === 0 ? (
          <div className="text-center py-8 bg-gray-50 rounded-lg border border-dashed">
            <Vote size={24} className="text-[#006837] mx-auto mb-3" />
            <h3 className="text-base font-medium text-gray-800">No Voting Blocs Yet</h3>
            <p className="text-sm text-gray-500 mt-1 mb-4 max-w-[250px] mx-auto">Start building your political coalition by creating your first voting bloc</p>
            <button
              className="px-4 py-2 bg-[#006837] text-white rounded-lg text-sm flex items-center gap-1.5 mx-auto"
              onClick={() => setActivePage("Create your Voting Bloc")}
            >
              Get Started <ArrowRight size={14} />
            </button>
          </div>
        ) : (
          <div className="space-y-6">
            {/* Owned Voting Blocs */}
            {ownedVotingBlocs.length > 0 && (
              <div>
                <h3 className="text-sm font-medium text-gray-700 mb-3 flex items-center gap-2">
                  <div className="w-2 h-2 bg-[#006837] rounded-full"></div>
                  Created Blocs ({ownedVotingBlocs.length})
                </h3>
                <ul className="space-y-2">
                  {ownedVotingBlocs.map((bloc) => (
                    <li
                      key={bloc._id}
                      className="p-3 rounded-lg border border-gray-100 hover:border-[#006837]/20 hover:bg-[#006837]/5 transition cursor-pointer flex items-center"
                      onClick={handleVisitAutoVotingBloc}
                    >
                      <div className="flex-1 min-w-0 flex items-center gap-3">
                        <div className="rounded-full w-8 h-8 flex-shrink-0 flex items-center justify-center bg-[#006837]/10 text-[#006837] font-medium">
                          {bloc.name.charAt(0).toUpperCase()}
                        </div>
                        <div className="min-w-0 flex-1">
                          <div className="flex items-center gap-2 flex-wrap">
                            <p className="font-medium text-gray-800 truncate">{bloc.name}</p>
                            <span className="inline-flex h-5 items-center px-2 rounded-full text-xs bg-green-100 text-green-800">
                              Creator
                            </span>
                            <span className="inline-flex h-5 items-center px-2 rounded-full text-xs bg-blue-100 text-blue-800">
                              {bloc.metrics?.totalMembers || 0} members
                            </span>
                          </div>
                          <p className="text-xs text-gray-500 line-clamp-1">
                            Target: {bloc.targetCandidate} • {bloc.location.lga}, {bloc.location.state}
                          </p>
                        </div>
                      </div>
                      <ArrowRight size={16} className="text-gray-400 flex-shrink-0" />
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Joined Voting Blocs */}
            {joinedVotingBlocs.length > 0 && (
              <div>
                <h3 className="text-sm font-medium text-gray-700 mb-3 flex items-center gap-2">
                  <div className="w-2 h-2 bg-blue-500 rounded-full"></div>
                  Joined Blocs ({joinedVotingBlocs.length})
                </h3>
                <ul className="space-y-2">
                  {joinedVotingBlocs.map((bloc) => (
                    <li
                      key={bloc._id}
                      className="p-3 rounded-lg border border-gray-100 hover:border-blue-500/20 hover:bg-blue-50/50 transition cursor-pointer flex items-center"
                      onClick={() => setActivePage("Create your Voting Bloc")}
                    >
                      <div className="flex-1 min-w-0 flex items-center gap-3">
                        <div className="rounded-full w-8 h-8 flex-shrink-0 flex items-center justify-center bg-blue-100 text-blue-600 font-medium">
                          {bloc.name.charAt(0).toUpperCase()}
                        </div>
                        <div className="min-w-0 flex-1">
                          <div className="flex items-center gap-2 flex-wrap">
                            <p className="font-medium text-gray-800 truncate">{bloc.name}</p>
                            <span className="inline-flex h-5 items-center px-2 rounded-full text-xs bg-blue-100 text-blue-800">
                              Member
                            </span>
                            <span className="inline-flex h-5 items-center px-2 rounded-full text-xs bg-gray-100 text-gray-600">
                              {bloc.metrics?.totalMembers || 0} members
                            </span>
                          </div>
                          <p className="text-xs text-gray-500 line-clamp-1">
                            Target: {bloc.targetCandidate} • {bloc.location.lga}, {bloc.location.state}
                          </p>
                        </div>
                      </div>
                      <ArrowRight size={16} className="text-gray-400 flex-shrink-0" />
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* View All Button */}
            {(ownedVotingBlocs.length > 0 || joinedVotingBlocs.length > 0) && (
              <div className="text-center">
                <button
                  onClick={handleVisitAutoVotingBloc}
                  className="text-sm text-[#006837] hover:text-[#004d2a] transition flex items-center gap-1 justify-center mx-auto"
                >
                  View Your Voting Bloc <ArrowRight size={14} />
                </button>
              </div>
            )}
          </div>
        )}
      </div>

      {/* Voting Location Modal */}
      {votingLocationModalOpen && (
        <Suspense fallback={null}>
          <VotingLocationModal
            isOpen={votingLocationModalOpen}
            onClose={() => setVotingLocationModalOpen(false)}
            onCompleteProfile={() => {
              setVotingLocationModalOpen(false);
              setEditProfileModalOpen(true);
            }}
          />
        </Suspense>
      )}

      {/* Profile Completion Modal */}
      {profileModalOpen && (
        <Suspense fallback={null}>
          <ProfileCompletionModal
            isOpen={profileModalOpen}
            onClose={() => setProfileModalOpen(false)}
            onCompleteProfile={() => {
              setProfileModalOpen(false);
              setEditProfileModalOpen(true);
            }}
          />
        </Suspense>
      )}

      {/* Edit Profile Modal */}
      {profile && editProfileModalOpen && (
        <Suspense fallback={null}>
          <EditProfileModal
            isOpen={editProfileModalOpen}
            onClose={() => setEditProfileModalOpen(false)}
            profile={profile}
          />
        </Suspense>
      )}

      {/* Twitter Follow Modal */}
      {twitterFollowModalOpen && (
        <Suspense fallback={null}>
          <TwitterFollowModal
            isOpen={twitterFollowModalOpen}
            onClose={() => setTwitterFollowModalOpen(false)}
          />
        </Suspense>
      )}

      {/* Share Voting Bloc Modal */}
      {showShareModal && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-2xl shadow-2xl max-w-md w-full p-6 animate-fade-in">
            <div className="flex items-center justify-between mb-6">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-[#006837]/10 rounded-lg">
                  <Share2 size={24} className="text-[#006837]" />
                </div>
                <div>
                  <h3 className="text-xl font-bold text-gray-900">Share Your Voting Bloc</h3>
                  <p className="text-sm text-gray-600">Invite others to join</p>
                </div>
              </div>
              <button
                onClick={() => setShowShareModal(false)}
                className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
              >
                <Activity size={20} className="text-gray-500 rotate-45" />
              </button>
            </div>

            {/* Social Media Share Buttons */}
            <div className="space-y-3 mb-6">
              <button
                onClick={() => {
                  shareToSocialMedia('whatsapp');
                  setShowShareModal(false);
                }}
                className="w-full flex items-center gap-3 p-4 bg-[#25D366] hover:bg-[#1da851] text-white rounded-xl transition-all duration-300 hover:scale-105 shadow-md"
              >
                <MessageSquare size={24} />
                <span className="font-medium">Share on WhatsApp</span>
              </button>

              <button
                onClick={() => {
                  shareToSocialMedia('twitter');
                  setShowShareModal(false);
                }}
                className="w-full flex items-center gap-3 p-4 bg-[#1DA1F2] hover:bg-[#1a8cd8] text-white rounded-xl transition-all duration-300 hover:scale-105 shadow-md"
              >
                <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
                </svg>
                <span className="font-medium">Share on X (Twitter)</span>
              </button>

              <button
                onClick={() => {
                  shareToSocialMedia('facebook');
                  setShowShareModal(false);
                }}
                className="w-full flex items-center gap-3 p-4 bg-[#1877F2] hover:bg-[#166fe5] text-white rounded-xl transition-all duration-300 hover:scale-105 shadow-md"
              >
                <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z" />
                </svg>
                <span className="font-medium">Share on Facebook</span>
              </button>

              <button
                onClick={() => {
                  shareToSocialMedia('telegram');
                  setShowShareModal(false);
                }}
                className="w-full flex items-center gap-3 p-4 bg-[#0088cc] hover:bg-[#0077b3] text-white rounded-xl transition-all duration-300 hover:scale-105 shadow-md"
              >
                <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M11.944 0A12 12 0 0 0 0 12a12 12 0 0 0 12 12 12 12 0 0 0 12-12A12 12 0 0 0 12 0a12 12 0 0 0-.056 0zm4.962 7.224c.1-.002.321.023.465.14a.506.506 0 0 1 .171.325c.016.093.036.306.02.472-.18 1.898-.962 6.502-1.36 8.627-.168.9-.499 1.201-.82 1.23-.696.065-1.225-.46-1.9-.902-1.056-.693-1.653-1.124-2.678-1.8-1.185-.78-.417-1.21.258-1.91.177-.184 3.247-2.977 3.307-3.23.007-.032.014-.15-.056-.212s-.174-.041-.249-.024c-.106.024-1.793 1.14-5.061 3.345-.48.33-.913.49-1.302.48-.428-.008-1.252-.241-1.865-.44-.752-.245-1.349-.374-1.297-.789.027-.216.325-.437.893-.663 3.498-1.524 5.83-2.529 6.998-3.014 3.332-1.386 4.025-1.627 4.476-1.635z" />
                </svg>
                <span className="font-medium">Share on Telegram</span>
              </button>

              <button
                onClick={() => {
                  shareToSocialMedia('linkedin');
                  setShowShareModal(false);
                }}
                className="w-full flex items-center gap-3 p-4 bg-[#0077B5] hover:bg-[#006396] text-white rounded-xl transition-all duration-300 hover:scale-105 shadow-md"
              >
                <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z" />
                </svg>
                <span className="font-medium">Share on LinkedIn</span>
              </button>
            </div>

            {/* Copy Link Section */}
            <div className="pt-4 border-t border-gray-200">
              <p className="text-sm text-gray-600 mb-3 font-medium">Or copy link</p>
              <button
                onClick={() => {
                  copyBlocLink();
                  setShowShareModal(false);
                }}
                className="w-full flex items-center justify-center gap-2 p-3 bg-gray-100 hover:bg-gray-200 text-gray-800 rounded-lg transition-colors font-medium"
              >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3" />
                </svg>
                Copy Link to Clipboard
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
