// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'voting_bloc.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$VotingBlocImpl _$$VotingBlocImplFromJson(Map<String, dynamic> json) =>
    _$VotingBlocImpl(
      id: json['_id'] as String,
      name: json['name'] as String,
      description: json['description'] as String? ?? '',
      goals:
          (json['goals'] as List<dynamic>?)?.map((e) => e as String).toList() ??
              const [],
      targetCandidate: json['targetCandidate'] as String?,
      scope: json['scope'] as String?,
      location: json['location'] == null
          ? null
          : BlocLocation.fromJson(json['location'] as Map<String, dynamic>),
      bannerImageUrl: json['bannerImageUrl'] as String?,
      richDescription: json['richDescription'] as String?,
      joinCode: json['joinCode'] as String?,
      isAutoGenerated: json['isAutoGenerated'] as bool? ?? false,
      creator: json['creator'] == null
          ? null
          : BlocCreator.fromJson(json['creator'] as Map<String, dynamic>),
      members: (json['members'] as List<dynamic>?)
              ?.map((e) => BlocMemberBasic.fromJson(e as Map<String, dynamic>))
              .toList() ??
          const [],
      manualMembers: (json['manualMembers'] as List<dynamic>?)
              ?.map((e) => BlocManualMember.fromJson(e as Map<String, dynamic>))
              .toList() ??
          const [],
      toolkits: (json['toolkits'] as List<dynamic>?)
              ?.map((e) => BlocToolkit.fromJson(e as Map<String, dynamic>))
              .toList() ??
          const [],
      metrics: json['metrics'] == null
          ? null
          : BlocMetrics.fromJson(json['metrics'] as Map<String, dynamic>),
      status: json['status'] as String? ?? 'active',
      createdAt: json['createdAt'] as String?,
      updatedAt: json['updatedAt'] as String?,
      totalMembers: (json['totalMembers'] as num?)?.toInt(),
      memberCount: (json['memberCount'] as num?)?.toInt(),
    );

Map<String, dynamic> _$$VotingBlocImplToJson(_$VotingBlocImpl instance) =>
    <String, dynamic>{
      '_id': instance.id,
      'name': instance.name,
      'description': instance.description,
      'goals': instance.goals,
      'targetCandidate': instance.targetCandidate,
      'scope': instance.scope,
      'location': instance.location,
      'bannerImageUrl': instance.bannerImageUrl,
      'richDescription': instance.richDescription,
      'joinCode': instance.joinCode,
      'isAutoGenerated': instance.isAutoGenerated,
      'creator': instance.creator,
      'members': instance.members,
      'manualMembers': instance.manualMembers,
      'toolkits': instance.toolkits,
      'metrics': instance.metrics,
      'status': instance.status,
      'createdAt': instance.createdAt,
      'updatedAt': instance.updatedAt,
      'totalMembers': instance.totalMembers,
      'memberCount': instance.memberCount,
    };

_$BlocLocationImpl _$$BlocLocationImplFromJson(Map<String, dynamic> json) =>
    _$BlocLocationImpl(
      state: json['state'] as String? ?? '',
      lga: json['lga'] as String? ?? '',
      ward: json['ward'] as String? ?? '',
    );

Map<String, dynamic> _$$BlocLocationImplToJson(_$BlocLocationImpl instance) =>
    <String, dynamic>{
      'state': instance.state,
      'lga': instance.lga,
      'ward': instance.ward,
    };

_$BlocCreatorImpl _$$BlocCreatorImplFromJson(Map<String, dynamic> json) =>
    _$BlocCreatorImpl(
      id: json['_id'] as String,
      name: json['name'] as String?,
      email: json['email'] as String?,
      profileImage: json['profileImage'] as String?,
    );

Map<String, dynamic> _$$BlocCreatorImplToJson(_$BlocCreatorImpl instance) =>
    <String, dynamic>{
      '_id': instance.id,
      'name': instance.name,
      'email': instance.email,
      'profileImage': instance.profileImage,
    };

_$BlocMemberBasicImpl _$$BlocMemberBasicImplFromJson(
        Map<String, dynamic> json) =>
    _$BlocMemberBasicImpl(
      id: json['_id'] as String,
      name: json['name'] as String?,
      email: json['email'] as String?,
      joinDate: json['joinDate'] as String?,
    );

Map<String, dynamic> _$$BlocMemberBasicImplToJson(
        _$BlocMemberBasicImpl instance) =>
    <String, dynamic>{
      '_id': instance.id,
      'name': instance.name,
      'email': instance.email,
      'joinDate': instance.joinDate,
    };

_$BlocManualMemberImpl _$$BlocManualMemberImplFromJson(
        Map<String, dynamic> json) =>
    _$BlocManualMemberImpl(
      id: json['id'] as String?,
      firstName: json['firstName'] as String?,
      lastName: json['lastName'] as String?,
      phoneNumber: json['phoneNumber'] as String?,
      state: json['state'] as String?,
      lga: json['lga'] as String?,
      ward: json['ward'] as String?,
      addedBy: json['addedBy'] as String?,
      addedAt: json['addedAt'] as String?,
    );

Map<String, dynamic> _$$BlocManualMemberImplToJson(
        _$BlocManualMemberImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'firstName': instance.firstName,
      'lastName': instance.lastName,
      'phoneNumber': instance.phoneNumber,
      'state': instance.state,
      'lga': instance.lga,
      'ward': instance.ward,
      'addedBy': instance.addedBy,
      'addedAt': instance.addedAt,
    };

_$BlocToolkitImpl _$$BlocToolkitImplFromJson(Map<String, dynamic> json) =>
    _$BlocToolkitImpl(
      label: json['label'] as String,
      url: json['url'] as String,
      type: json['type'] as String? ?? 'Toolkit',
    );

Map<String, dynamic> _$$BlocToolkitImplToJson(_$BlocToolkitImpl instance) =>
    <String, dynamic>{
      'label': instance.label,
      'url': instance.url,
      'type': instance.type,
    };

_$BlocMetricsImpl _$$BlocMetricsImplFromJson(Map<String, dynamic> json) =>
    _$BlocMetricsImpl(
      totalMembers: (json['totalMembers'] as num?)?.toInt() ?? 0,
      platformMembers: (json['platformMembers'] as num?)?.toInt() ?? 0,
      manualMembers: (json['manualMembers'] as num?)?.toInt() ?? 0,
      weeklyGrowth: (json['weeklyGrowth'] as num?)?.toInt() ?? 0,
      monthlyGrowth: (json['monthlyGrowth'] as num?)?.toInt() ?? 0,
      engagementScore: (json['engagementScore'] as num?)?.toInt() ?? 0,
      lastUpdated: json['lastUpdated'] as String?,
    );

Map<String, dynamic> _$$BlocMetricsImplToJson(_$BlocMetricsImpl instance) =>
    <String, dynamic>{
      'totalMembers': instance.totalMembers,
      'platformMembers': instance.platformMembers,
      'manualMembers': instance.manualMembers,
      'weeklyGrowth': instance.weeklyGrowth,
      'monthlyGrowth': instance.monthlyGrowth,
      'engagementScore': instance.engagementScore,
      'lastUpdated': instance.lastUpdated,
    };
