import 'package:freezed_annotation/freezed_annotation.dart';

part 'voting_bloc.freezed.dart';
part 'voting_bloc.g.dart';

@freezed
class VotingBloc with _$VotingBloc {
  const factory VotingBloc({
    @JsonKey(name: '_id') required String id,
    required String name,
    @Default('') String description,
    @Default([]) List<String> goals,
    String? targetCandidate,
    String? scope,
    BlocLocation? location,
    String? bannerImageUrl,
    String? richDescription,
    String? joinCode,
    @Default(false) bool isAutoGenerated,
    BlocCreator? creator,
    @Default([]) List<BlocMemberBasic> members,
    @Default([]) List<BlocManualMember> manualMembers,
    @Default([]) List<BlocToolkit> toolkits,
    BlocMetrics? metrics,
    @Default('active') String status,
    String? createdAt,
    String? updatedAt,
    // Flat fields that may come alongside nested ones
    int? totalMembers,
    int? memberCount,
  }) = _VotingBloc;

  factory VotingBloc.fromJson(Map<String, dynamic> json) =>
      _$VotingBlocFromJson(json);
}

@freezed
class BlocLocation with _$BlocLocation {
  const factory BlocLocation({
    @Default('') String state,
    @Default('') String lga,
    @Default('') String ward,
  }) = _BlocLocation;

  factory BlocLocation.fromJson(Map<String, dynamic> json) =>
      _$BlocLocationFromJson(json);
}

@freezed
class BlocCreator with _$BlocCreator {
  const factory BlocCreator({
    @JsonKey(name: '_id') required String id,
    String? name,
    String? email,
    String? profileImage,
  }) = _BlocCreator;

  factory BlocCreator.fromJson(Map<String, dynamic> json) =>
      _$BlocCreatorFromJson(json);
}

@freezed
class BlocMemberBasic with _$BlocMemberBasic {
  const factory BlocMemberBasic({
    @JsonKey(name: '_id') required String id,
    String? name,
    String? email,
    String? joinDate,
  }) = _BlocMemberBasic;

  factory BlocMemberBasic.fromJson(Map<String, dynamic> json) =>
      _$BlocMemberBasicFromJson(json);
}

@freezed
class BlocManualMember with _$BlocManualMember {
  const factory BlocManualMember({
    String? id,
    String? firstName,
    String? lastName,
    String? phoneNumber,
    String? state,
    String? lga,
    String? ward,
    String? addedBy,
    String? addedAt,
  }) = _BlocManualMember;

  factory BlocManualMember.fromJson(Map<String, dynamic> json) =>
      _$BlocManualMemberFromJson(json);
}

@freezed
class BlocToolkit with _$BlocToolkit {
  const factory BlocToolkit({
    required String label,
    required String url,
    @Default('Toolkit') String type,
  }) = _BlocToolkit;

  factory BlocToolkit.fromJson(Map<String, dynamic> json) =>
      _$BlocToolkitFromJson(json);
}

@freezed
class BlocMetrics with _$BlocMetrics {
  const factory BlocMetrics({
    @Default(0) int totalMembers,
    @Default(0) int platformMembers,
    @Default(0) int manualMembers,
    @Default(0) int weeklyGrowth,
    @Default(0) int monthlyGrowth,
    @Default(0) int engagementScore,
    String? lastUpdated,
  }) = _BlocMetrics;

  factory BlocMetrics.fromJson(Map<String, dynamic> json) =>
      _$BlocMetricsFromJson(json);
}
