// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark

part of 'voting_bloc.dart';

// **************************************************************************
// FreezedGenerator
// **************************************************************************

T _$identity<T>(T value) => value;

final _privateConstructorUsedError = UnsupportedError(
    'It seems like you constructed your class using `MyClass._()`. This constructor is only meant to be used by freezed and you are not supposed to need it nor use it.\nPlease check the documentation here for more information: https://github.com/rrousselGit/freezed#adding-getters-and-methods-to-our-models');

VotingBloc _$VotingBlocFromJson(Map<String, dynamic> json) {
  return _VotingBloc.fromJson(json);
}

/// @nodoc
mixin _$VotingBloc {
  @JsonKey(name: '_id')
  String get id => throw _privateConstructorUsedError;
  String get name => throw _privateConstructorUsedError;
  String get description => throw _privateConstructorUsedError;
  List<String> get goals => throw _privateConstructorUsedError;
  String? get targetCandidate => throw _privateConstructorUsedError;
  String? get scope => throw _privateConstructorUsedError;
  BlocLocation? get location => throw _privateConstructorUsedError;
  String? get bannerImageUrl => throw _privateConstructorUsedError;
  String? get richDescription => throw _privateConstructorUsedError;
  String? get joinCode => throw _privateConstructorUsedError;
  bool get isAutoGenerated => throw _privateConstructorUsedError;
  BlocCreator? get creator => throw _privateConstructorUsedError;
  List<BlocMemberBasic> get members => throw _privateConstructorUsedError;
  List<BlocManualMember> get manualMembers =>
      throw _privateConstructorUsedError;
  List<BlocToolkit> get toolkits => throw _privateConstructorUsedError;
  BlocMetrics? get metrics => throw _privateConstructorUsedError;
  String get status => throw _privateConstructorUsedError;
  String? get createdAt => throw _privateConstructorUsedError;
  String? get updatedAt =>
      throw _privateConstructorUsedError; // Flat fields that may come alongside nested ones
  int? get totalMembers => throw _privateConstructorUsedError;
  int? get memberCount => throw _privateConstructorUsedError;

  Map<String, dynamic> toJson() => throw _privateConstructorUsedError;
  @JsonKey(ignore: true)
  $VotingBlocCopyWith<VotingBloc> get copyWith =>
      throw _privateConstructorUsedError;
}

/// @nodoc
abstract class $VotingBlocCopyWith<$Res> {
  factory $VotingBlocCopyWith(
          VotingBloc value, $Res Function(VotingBloc) then) =
      _$VotingBlocCopyWithImpl<$Res, VotingBloc>;
  @useResult
  $Res call(
      {@JsonKey(name: '_id') String id,
      String name,
      String description,
      List<String> goals,
      String? targetCandidate,
      String? scope,
      BlocLocation? location,
      String? bannerImageUrl,
      String? richDescription,
      String? joinCode,
      bool isAutoGenerated,
      BlocCreator? creator,
      List<BlocMemberBasic> members,
      List<BlocManualMember> manualMembers,
      List<BlocToolkit> toolkits,
      BlocMetrics? metrics,
      String status,
      String? createdAt,
      String? updatedAt,
      int? totalMembers,
      int? memberCount});

  $BlocLocationCopyWith<$Res>? get location;
  $BlocCreatorCopyWith<$Res>? get creator;
  $BlocMetricsCopyWith<$Res>? get metrics;
}

/// @nodoc
class _$VotingBlocCopyWithImpl<$Res, $Val extends VotingBloc>
    implements $VotingBlocCopyWith<$Res> {
  _$VotingBlocCopyWithImpl(this._value, this._then);

  // ignore: unused_field
  final $Val _value;
  // ignore: unused_field
  final $Res Function($Val) _then;

  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? id = null,
    Object? name = null,
    Object? description = null,
    Object? goals = null,
    Object? targetCandidate = freezed,
    Object? scope = freezed,
    Object? location = freezed,
    Object? bannerImageUrl = freezed,
    Object? richDescription = freezed,
    Object? joinCode = freezed,
    Object? isAutoGenerated = null,
    Object? creator = freezed,
    Object? members = null,
    Object? manualMembers = null,
    Object? toolkits = null,
    Object? metrics = freezed,
    Object? status = null,
    Object? createdAt = freezed,
    Object? updatedAt = freezed,
    Object? totalMembers = freezed,
    Object? memberCount = freezed,
  }) {
    return _then(_value.copyWith(
      id: null == id
          ? _value.id
          : id // ignore: cast_nullable_to_non_nullable
              as String,
      name: null == name
          ? _value.name
          : name // ignore: cast_nullable_to_non_nullable
              as String,
      description: null == description
          ? _value.description
          : description // ignore: cast_nullable_to_non_nullable
              as String,
      goals: null == goals
          ? _value.goals
          : goals // ignore: cast_nullable_to_non_nullable
              as List<String>,
      targetCandidate: freezed == targetCandidate
          ? _value.targetCandidate
          : targetCandidate // ignore: cast_nullable_to_non_nullable
              as String?,
      scope: freezed == scope
          ? _value.scope
          : scope // ignore: cast_nullable_to_non_nullable
              as String?,
      location: freezed == location
          ? _value.location
          : location // ignore: cast_nullable_to_non_nullable
              as BlocLocation?,
      bannerImageUrl: freezed == bannerImageUrl
          ? _value.bannerImageUrl
          : bannerImageUrl // ignore: cast_nullable_to_non_nullable
              as String?,
      richDescription: freezed == richDescription
          ? _value.richDescription
          : richDescription // ignore: cast_nullable_to_non_nullable
              as String?,
      joinCode: freezed == joinCode
          ? _value.joinCode
          : joinCode // ignore: cast_nullable_to_non_nullable
              as String?,
      isAutoGenerated: null == isAutoGenerated
          ? _value.isAutoGenerated
          : isAutoGenerated // ignore: cast_nullable_to_non_nullable
              as bool,
      creator: freezed == creator
          ? _value.creator
          : creator // ignore: cast_nullable_to_non_nullable
              as BlocCreator?,
      members: null == members
          ? _value.members
          : members // ignore: cast_nullable_to_non_nullable
              as List<BlocMemberBasic>,
      manualMembers: null == manualMembers
          ? _value.manualMembers
          : manualMembers // ignore: cast_nullable_to_non_nullable
              as List<BlocManualMember>,
      toolkits: null == toolkits
          ? _value.toolkits
          : toolkits // ignore: cast_nullable_to_non_nullable
              as List<BlocToolkit>,
      metrics: freezed == metrics
          ? _value.metrics
          : metrics // ignore: cast_nullable_to_non_nullable
              as BlocMetrics?,
      status: null == status
          ? _value.status
          : status // ignore: cast_nullable_to_non_nullable
              as String,
      createdAt: freezed == createdAt
          ? _value.createdAt
          : createdAt // ignore: cast_nullable_to_non_nullable
              as String?,
      updatedAt: freezed == updatedAt
          ? _value.updatedAt
          : updatedAt // ignore: cast_nullable_to_non_nullable
              as String?,
      totalMembers: freezed == totalMembers
          ? _value.totalMembers
          : totalMembers // ignore: cast_nullable_to_non_nullable
              as int?,
      memberCount: freezed == memberCount
          ? _value.memberCount
          : memberCount // ignore: cast_nullable_to_non_nullable
              as int?,
    ) as $Val);
  }

  @override
  @pragma('vm:prefer-inline')
  $BlocLocationCopyWith<$Res>? get location {
    if (_value.location == null) {
      return null;
    }

    return $BlocLocationCopyWith<$Res>(_value.location!, (value) {
      return _then(_value.copyWith(location: value) as $Val);
    });
  }

  @override
  @pragma('vm:prefer-inline')
  $BlocCreatorCopyWith<$Res>? get creator {
    if (_value.creator == null) {
      return null;
    }

    return $BlocCreatorCopyWith<$Res>(_value.creator!, (value) {
      return _then(_value.copyWith(creator: value) as $Val);
    });
  }

  @override
  @pragma('vm:prefer-inline')
  $BlocMetricsCopyWith<$Res>? get metrics {
    if (_value.metrics == null) {
      return null;
    }

    return $BlocMetricsCopyWith<$Res>(_value.metrics!, (value) {
      return _then(_value.copyWith(metrics: value) as $Val);
    });
  }
}

/// @nodoc
abstract class _$$VotingBlocImplCopyWith<$Res>
    implements $VotingBlocCopyWith<$Res> {
  factory _$$VotingBlocImplCopyWith(
          _$VotingBlocImpl value, $Res Function(_$VotingBlocImpl) then) =
      __$$VotingBlocImplCopyWithImpl<$Res>;
  @override
  @useResult
  $Res call(
      {@JsonKey(name: '_id') String id,
      String name,
      String description,
      List<String> goals,
      String? targetCandidate,
      String? scope,
      BlocLocation? location,
      String? bannerImageUrl,
      String? richDescription,
      String? joinCode,
      bool isAutoGenerated,
      BlocCreator? creator,
      List<BlocMemberBasic> members,
      List<BlocManualMember> manualMembers,
      List<BlocToolkit> toolkits,
      BlocMetrics? metrics,
      String status,
      String? createdAt,
      String? updatedAt,
      int? totalMembers,
      int? memberCount});

  @override
  $BlocLocationCopyWith<$Res>? get location;
  @override
  $BlocCreatorCopyWith<$Res>? get creator;
  @override
  $BlocMetricsCopyWith<$Res>? get metrics;
}

/// @nodoc
class __$$VotingBlocImplCopyWithImpl<$Res>
    extends _$VotingBlocCopyWithImpl<$Res, _$VotingBlocImpl>
    implements _$$VotingBlocImplCopyWith<$Res> {
  __$$VotingBlocImplCopyWithImpl(
      _$VotingBlocImpl _value, $Res Function(_$VotingBlocImpl) _then)
      : super(_value, _then);

  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? id = null,
    Object? name = null,
    Object? description = null,
    Object? goals = null,
    Object? targetCandidate = freezed,
    Object? scope = freezed,
    Object? location = freezed,
    Object? bannerImageUrl = freezed,
    Object? richDescription = freezed,
    Object? joinCode = freezed,
    Object? isAutoGenerated = null,
    Object? creator = freezed,
    Object? members = null,
    Object? manualMembers = null,
    Object? toolkits = null,
    Object? metrics = freezed,
    Object? status = null,
    Object? createdAt = freezed,
    Object? updatedAt = freezed,
    Object? totalMembers = freezed,
    Object? memberCount = freezed,
  }) {
    return _then(_$VotingBlocImpl(
      id: null == id
          ? _value.id
          : id // ignore: cast_nullable_to_non_nullable
              as String,
      name: null == name
          ? _value.name
          : name // ignore: cast_nullable_to_non_nullable
              as String,
      description: null == description
          ? _value.description
          : description // ignore: cast_nullable_to_non_nullable
              as String,
      goals: null == goals
          ? _value._goals
          : goals // ignore: cast_nullable_to_non_nullable
              as List<String>,
      targetCandidate: freezed == targetCandidate
          ? _value.targetCandidate
          : targetCandidate // ignore: cast_nullable_to_non_nullable
              as String?,
      scope: freezed == scope
          ? _value.scope
          : scope // ignore: cast_nullable_to_non_nullable
              as String?,
      location: freezed == location
          ? _value.location
          : location // ignore: cast_nullable_to_non_nullable
              as BlocLocation?,
      bannerImageUrl: freezed == bannerImageUrl
          ? _value.bannerImageUrl
          : bannerImageUrl // ignore: cast_nullable_to_non_nullable
              as String?,
      richDescription: freezed == richDescription
          ? _value.richDescription
          : richDescription // ignore: cast_nullable_to_non_nullable
              as String?,
      joinCode: freezed == joinCode
          ? _value.joinCode
          : joinCode // ignore: cast_nullable_to_non_nullable
              as String?,
      isAutoGenerated: null == isAutoGenerated
          ? _value.isAutoGenerated
          : isAutoGenerated // ignore: cast_nullable_to_non_nullable
              as bool,
      creator: freezed == creator
          ? _value.creator
          : creator // ignore: cast_nullable_to_non_nullable
              as BlocCreator?,
      members: null == members
          ? _value._members
          : members // ignore: cast_nullable_to_non_nullable
              as List<BlocMemberBasic>,
      manualMembers: null == manualMembers
          ? _value._manualMembers
          : manualMembers // ignore: cast_nullable_to_non_nullable
              as List<BlocManualMember>,
      toolkits: null == toolkits
          ? _value._toolkits
          : toolkits // ignore: cast_nullable_to_non_nullable
              as List<BlocToolkit>,
      metrics: freezed == metrics
          ? _value.metrics
          : metrics // ignore: cast_nullable_to_non_nullable
              as BlocMetrics?,
      status: null == status
          ? _value.status
          : status // ignore: cast_nullable_to_non_nullable
              as String,
      createdAt: freezed == createdAt
          ? _value.createdAt
          : createdAt // ignore: cast_nullable_to_non_nullable
              as String?,
      updatedAt: freezed == updatedAt
          ? _value.updatedAt
          : updatedAt // ignore: cast_nullable_to_non_nullable
              as String?,
      totalMembers: freezed == totalMembers
          ? _value.totalMembers
          : totalMembers // ignore: cast_nullable_to_non_nullable
              as int?,
      memberCount: freezed == memberCount
          ? _value.memberCount
          : memberCount // ignore: cast_nullable_to_non_nullable
              as int?,
    ));
  }
}

/// @nodoc
@JsonSerializable()
class _$VotingBlocImpl implements _VotingBloc {
  const _$VotingBlocImpl(
      {@JsonKey(name: '_id') required this.id,
      required this.name,
      this.description = '',
      final List<String> goals = const [],
      this.targetCandidate,
      this.scope,
      this.location,
      this.bannerImageUrl,
      this.richDescription,
      this.joinCode,
      this.isAutoGenerated = false,
      this.creator,
      final List<BlocMemberBasic> members = const [],
      final List<BlocManualMember> manualMembers = const [],
      final List<BlocToolkit> toolkits = const [],
      this.metrics,
      this.status = 'active',
      this.createdAt,
      this.updatedAt,
      this.totalMembers,
      this.memberCount})
      : _goals = goals,
        _members = members,
        _manualMembers = manualMembers,
        _toolkits = toolkits;

  factory _$VotingBlocImpl.fromJson(Map<String, dynamic> json) =>
      _$$VotingBlocImplFromJson(json);

  @override
  @JsonKey(name: '_id')
  final String id;
  @override
  final String name;
  @override
  @JsonKey()
  final String description;
  final List<String> _goals;
  @override
  @JsonKey()
  List<String> get goals {
    if (_goals is EqualUnmodifiableListView) return _goals;
    // ignore: implicit_dynamic_type
    return EqualUnmodifiableListView(_goals);
  }

  @override
  final String? targetCandidate;
  @override
  final String? scope;
  @override
  final BlocLocation? location;
  @override
  final String? bannerImageUrl;
  @override
  final String? richDescription;
  @override
  final String? joinCode;
  @override
  @JsonKey()
  final bool isAutoGenerated;
  @override
  final BlocCreator? creator;
  final List<BlocMemberBasic> _members;
  @override
  @JsonKey()
  List<BlocMemberBasic> get members {
    if (_members is EqualUnmodifiableListView) return _members;
    // ignore: implicit_dynamic_type
    return EqualUnmodifiableListView(_members);
  }

  final List<BlocManualMember> _manualMembers;
  @override
  @JsonKey()
  List<BlocManualMember> get manualMembers {
    if (_manualMembers is EqualUnmodifiableListView) return _manualMembers;
    // ignore: implicit_dynamic_type
    return EqualUnmodifiableListView(_manualMembers);
  }

  final List<BlocToolkit> _toolkits;
  @override
  @JsonKey()
  List<BlocToolkit> get toolkits {
    if (_toolkits is EqualUnmodifiableListView) return _toolkits;
    // ignore: implicit_dynamic_type
    return EqualUnmodifiableListView(_toolkits);
  }

  @override
  final BlocMetrics? metrics;
  @override
  @JsonKey()
  final String status;
  @override
  final String? createdAt;
  @override
  final String? updatedAt;
// Flat fields that may come alongside nested ones
  @override
  final int? totalMembers;
  @override
  final int? memberCount;

  @override
  String toString() {
    return 'VotingBloc(id: $id, name: $name, description: $description, goals: $goals, targetCandidate: $targetCandidate, scope: $scope, location: $location, bannerImageUrl: $bannerImageUrl, richDescription: $richDescription, joinCode: $joinCode, isAutoGenerated: $isAutoGenerated, creator: $creator, members: $members, manualMembers: $manualMembers, toolkits: $toolkits, metrics: $metrics, status: $status, createdAt: $createdAt, updatedAt: $updatedAt, totalMembers: $totalMembers, memberCount: $memberCount)';
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is _$VotingBlocImpl &&
            (identical(other.id, id) || other.id == id) &&
            (identical(other.name, name) || other.name == name) &&
            (identical(other.description, description) ||
                other.description == description) &&
            const DeepCollectionEquality().equals(other._goals, _goals) &&
            (identical(other.targetCandidate, targetCandidate) ||
                other.targetCandidate == targetCandidate) &&
            (identical(other.scope, scope) || other.scope == scope) &&
            (identical(other.location, location) ||
                other.location == location) &&
            (identical(other.bannerImageUrl, bannerImageUrl) ||
                other.bannerImageUrl == bannerImageUrl) &&
            (identical(other.richDescription, richDescription) ||
                other.richDescription == richDescription) &&
            (identical(other.joinCode, joinCode) ||
                other.joinCode == joinCode) &&
            (identical(other.isAutoGenerated, isAutoGenerated) ||
                other.isAutoGenerated == isAutoGenerated) &&
            (identical(other.creator, creator) || other.creator == creator) &&
            const DeepCollectionEquality().equals(other._members, _members) &&
            const DeepCollectionEquality()
                .equals(other._manualMembers, _manualMembers) &&
            const DeepCollectionEquality().equals(other._toolkits, _toolkits) &&
            (identical(other.metrics, metrics) || other.metrics == metrics) &&
            (identical(other.status, status) || other.status == status) &&
            (identical(other.createdAt, createdAt) ||
                other.createdAt == createdAt) &&
            (identical(other.updatedAt, updatedAt) ||
                other.updatedAt == updatedAt) &&
            (identical(other.totalMembers, totalMembers) ||
                other.totalMembers == totalMembers) &&
            (identical(other.memberCount, memberCount) ||
                other.memberCount == memberCount));
  }

  @JsonKey(ignore: true)
  @override
  int get hashCode => Object.hashAll([
        runtimeType,
        id,
        name,
        description,
        const DeepCollectionEquality().hash(_goals),
        targetCandidate,
        scope,
        location,
        bannerImageUrl,
        richDescription,
        joinCode,
        isAutoGenerated,
        creator,
        const DeepCollectionEquality().hash(_members),
        const DeepCollectionEquality().hash(_manualMembers),
        const DeepCollectionEquality().hash(_toolkits),
        metrics,
        status,
        createdAt,
        updatedAt,
        totalMembers,
        memberCount
      ]);

  @JsonKey(ignore: true)
  @override
  @pragma('vm:prefer-inline')
  _$$VotingBlocImplCopyWith<_$VotingBlocImpl> get copyWith =>
      __$$VotingBlocImplCopyWithImpl<_$VotingBlocImpl>(this, _$identity);

  @override
  Map<String, dynamic> toJson() {
    return _$$VotingBlocImplToJson(
      this,
    );
  }
}

abstract class _VotingBloc implements VotingBloc {
  const factory _VotingBloc(
      {@JsonKey(name: '_id') required final String id,
      required final String name,
      final String description,
      final List<String> goals,
      final String? targetCandidate,
      final String? scope,
      final BlocLocation? location,
      final String? bannerImageUrl,
      final String? richDescription,
      final String? joinCode,
      final bool isAutoGenerated,
      final BlocCreator? creator,
      final List<BlocMemberBasic> members,
      final List<BlocManualMember> manualMembers,
      final List<BlocToolkit> toolkits,
      final BlocMetrics? metrics,
      final String status,
      final String? createdAt,
      final String? updatedAt,
      final int? totalMembers,
      final int? memberCount}) = _$VotingBlocImpl;

  factory _VotingBloc.fromJson(Map<String, dynamic> json) =
      _$VotingBlocImpl.fromJson;

  @override
  @JsonKey(name: '_id')
  String get id;
  @override
  String get name;
  @override
  String get description;
  @override
  List<String> get goals;
  @override
  String? get targetCandidate;
  @override
  String? get scope;
  @override
  BlocLocation? get location;
  @override
  String? get bannerImageUrl;
  @override
  String? get richDescription;
  @override
  String? get joinCode;
  @override
  bool get isAutoGenerated;
  @override
  BlocCreator? get creator;
  @override
  List<BlocMemberBasic> get members;
  @override
  List<BlocManualMember> get manualMembers;
  @override
  List<BlocToolkit> get toolkits;
  @override
  BlocMetrics? get metrics;
  @override
  String get status;
  @override
  String? get createdAt;
  @override
  String? get updatedAt;
  @override // Flat fields that may come alongside nested ones
  int? get totalMembers;
  @override
  int? get memberCount;
  @override
  @JsonKey(ignore: true)
  _$$VotingBlocImplCopyWith<_$VotingBlocImpl> get copyWith =>
      throw _privateConstructorUsedError;
}

BlocLocation _$BlocLocationFromJson(Map<String, dynamic> json) {
  return _BlocLocation.fromJson(json);
}

/// @nodoc
mixin _$BlocLocation {
  String get state => throw _privateConstructorUsedError;
  String get lga => throw _privateConstructorUsedError;
  String get ward => throw _privateConstructorUsedError;

  Map<String, dynamic> toJson() => throw _privateConstructorUsedError;
  @JsonKey(ignore: true)
  $BlocLocationCopyWith<BlocLocation> get copyWith =>
      throw _privateConstructorUsedError;
}

/// @nodoc
abstract class $BlocLocationCopyWith<$Res> {
  factory $BlocLocationCopyWith(
          BlocLocation value, $Res Function(BlocLocation) then) =
      _$BlocLocationCopyWithImpl<$Res, BlocLocation>;
  @useResult
  $Res call({String state, String lga, String ward});
}

/// @nodoc
class _$BlocLocationCopyWithImpl<$Res, $Val extends BlocLocation>
    implements $BlocLocationCopyWith<$Res> {
  _$BlocLocationCopyWithImpl(this._value, this._then);

  // ignore: unused_field
  final $Val _value;
  // ignore: unused_field
  final $Res Function($Val) _then;

  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? state = null,
    Object? lga = null,
    Object? ward = null,
  }) {
    return _then(_value.copyWith(
      state: null == state
          ? _value.state
          : state // ignore: cast_nullable_to_non_nullable
              as String,
      lga: null == lga
          ? _value.lga
          : lga // ignore: cast_nullable_to_non_nullable
              as String,
      ward: null == ward
          ? _value.ward
          : ward // ignore: cast_nullable_to_non_nullable
              as String,
    ) as $Val);
  }
}

/// @nodoc
abstract class _$$BlocLocationImplCopyWith<$Res>
    implements $BlocLocationCopyWith<$Res> {
  factory _$$BlocLocationImplCopyWith(
          _$BlocLocationImpl value, $Res Function(_$BlocLocationImpl) then) =
      __$$BlocLocationImplCopyWithImpl<$Res>;
  @override
  @useResult
  $Res call({String state, String lga, String ward});
}

/// @nodoc
class __$$BlocLocationImplCopyWithImpl<$Res>
    extends _$BlocLocationCopyWithImpl<$Res, _$BlocLocationImpl>
    implements _$$BlocLocationImplCopyWith<$Res> {
  __$$BlocLocationImplCopyWithImpl(
      _$BlocLocationImpl _value, $Res Function(_$BlocLocationImpl) _then)
      : super(_value, _then);

  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? state = null,
    Object? lga = null,
    Object? ward = null,
  }) {
    return _then(_$BlocLocationImpl(
      state: null == state
          ? _value.state
          : state // ignore: cast_nullable_to_non_nullable
              as String,
      lga: null == lga
          ? _value.lga
          : lga // ignore: cast_nullable_to_non_nullable
              as String,
      ward: null == ward
          ? _value.ward
          : ward // ignore: cast_nullable_to_non_nullable
              as String,
    ));
  }
}

/// @nodoc
@JsonSerializable()
class _$BlocLocationImpl implements _BlocLocation {
  const _$BlocLocationImpl({this.state = '', this.lga = '', this.ward = ''});

  factory _$BlocLocationImpl.fromJson(Map<String, dynamic> json) =>
      _$$BlocLocationImplFromJson(json);

  @override
  @JsonKey()
  final String state;
  @override
  @JsonKey()
  final String lga;
  @override
  @JsonKey()
  final String ward;

  @override
  String toString() {
    return 'BlocLocation(state: $state, lga: $lga, ward: $ward)';
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is _$BlocLocationImpl &&
            (identical(other.state, state) || other.state == state) &&
            (identical(other.lga, lga) || other.lga == lga) &&
            (identical(other.ward, ward) || other.ward == ward));
  }

  @JsonKey(ignore: true)
  @override
  int get hashCode => Object.hash(runtimeType, state, lga, ward);

  @JsonKey(ignore: true)
  @override
  @pragma('vm:prefer-inline')
  _$$BlocLocationImplCopyWith<_$BlocLocationImpl> get copyWith =>
      __$$BlocLocationImplCopyWithImpl<_$BlocLocationImpl>(this, _$identity);

  @override
  Map<String, dynamic> toJson() {
    return _$$BlocLocationImplToJson(
      this,
    );
  }
}

abstract class _BlocLocation implements BlocLocation {
  const factory _BlocLocation(
      {final String state,
      final String lga,
      final String ward}) = _$BlocLocationImpl;

  factory _BlocLocation.fromJson(Map<String, dynamic> json) =
      _$BlocLocationImpl.fromJson;

  @override
  String get state;
  @override
  String get lga;
  @override
  String get ward;
  @override
  @JsonKey(ignore: true)
  _$$BlocLocationImplCopyWith<_$BlocLocationImpl> get copyWith =>
      throw _privateConstructorUsedError;
}

BlocCreator _$BlocCreatorFromJson(Map<String, dynamic> json) {
  return _BlocCreator.fromJson(json);
}

/// @nodoc
mixin _$BlocCreator {
  @JsonKey(name: '_id')
  String get id => throw _privateConstructorUsedError;
  String? get name => throw _privateConstructorUsedError;
  String? get email => throw _privateConstructorUsedError;
  String? get profileImage => throw _privateConstructorUsedError;

  Map<String, dynamic> toJson() => throw _privateConstructorUsedError;
  @JsonKey(ignore: true)
  $BlocCreatorCopyWith<BlocCreator> get copyWith =>
      throw _privateConstructorUsedError;
}

/// @nodoc
abstract class $BlocCreatorCopyWith<$Res> {
  factory $BlocCreatorCopyWith(
          BlocCreator value, $Res Function(BlocCreator) then) =
      _$BlocCreatorCopyWithImpl<$Res, BlocCreator>;
  @useResult
  $Res call(
      {@JsonKey(name: '_id') String id,
      String? name,
      String? email,
      String? profileImage});
}

/// @nodoc
class _$BlocCreatorCopyWithImpl<$Res, $Val extends BlocCreator>
    implements $BlocCreatorCopyWith<$Res> {
  _$BlocCreatorCopyWithImpl(this._value, this._then);

  // ignore: unused_field
  final $Val _value;
  // ignore: unused_field
  final $Res Function($Val) _then;

  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? id = null,
    Object? name = freezed,
    Object? email = freezed,
    Object? profileImage = freezed,
  }) {
    return _then(_value.copyWith(
      id: null == id
          ? _value.id
          : id // ignore: cast_nullable_to_non_nullable
              as String,
      name: freezed == name
          ? _value.name
          : name // ignore: cast_nullable_to_non_nullable
              as String?,
      email: freezed == email
          ? _value.email
          : email // ignore: cast_nullable_to_non_nullable
              as String?,
      profileImage: freezed == profileImage
          ? _value.profileImage
          : profileImage // ignore: cast_nullable_to_non_nullable
              as String?,
    ) as $Val);
  }
}

/// @nodoc
abstract class _$$BlocCreatorImplCopyWith<$Res>
    implements $BlocCreatorCopyWith<$Res> {
  factory _$$BlocCreatorImplCopyWith(
          _$BlocCreatorImpl value, $Res Function(_$BlocCreatorImpl) then) =
      __$$BlocCreatorImplCopyWithImpl<$Res>;
  @override
  @useResult
  $Res call(
      {@JsonKey(name: '_id') String id,
      String? name,
      String? email,
      String? profileImage});
}

/// @nodoc
class __$$BlocCreatorImplCopyWithImpl<$Res>
    extends _$BlocCreatorCopyWithImpl<$Res, _$BlocCreatorImpl>
    implements _$$BlocCreatorImplCopyWith<$Res> {
  __$$BlocCreatorImplCopyWithImpl(
      _$BlocCreatorImpl _value, $Res Function(_$BlocCreatorImpl) _then)
      : super(_value, _then);

  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? id = null,
    Object? name = freezed,
    Object? email = freezed,
    Object? profileImage = freezed,
  }) {
    return _then(_$BlocCreatorImpl(
      id: null == id
          ? _value.id
          : id // ignore: cast_nullable_to_non_nullable
              as String,
      name: freezed == name
          ? _value.name
          : name // ignore: cast_nullable_to_non_nullable
              as String?,
      email: freezed == email
          ? _value.email
          : email // ignore: cast_nullable_to_non_nullable
              as String?,
      profileImage: freezed == profileImage
          ? _value.profileImage
          : profileImage // ignore: cast_nullable_to_non_nullable
              as String?,
    ));
  }
}

/// @nodoc
@JsonSerializable()
class _$BlocCreatorImpl implements _BlocCreator {
  const _$BlocCreatorImpl(
      {@JsonKey(name: '_id') required this.id,
      this.name,
      this.email,
      this.profileImage});

  factory _$BlocCreatorImpl.fromJson(Map<String, dynamic> json) =>
      _$$BlocCreatorImplFromJson(json);

  @override
  @JsonKey(name: '_id')
  final String id;
  @override
  final String? name;
  @override
  final String? email;
  @override
  final String? profileImage;

  @override
  String toString() {
    return 'BlocCreator(id: $id, name: $name, email: $email, profileImage: $profileImage)';
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is _$BlocCreatorImpl &&
            (identical(other.id, id) || other.id == id) &&
            (identical(other.name, name) || other.name == name) &&
            (identical(other.email, email) || other.email == email) &&
            (identical(other.profileImage, profileImage) ||
                other.profileImage == profileImage));
  }

  @JsonKey(ignore: true)
  @override
  int get hashCode => Object.hash(runtimeType, id, name, email, profileImage);

  @JsonKey(ignore: true)
  @override
  @pragma('vm:prefer-inline')
  _$$BlocCreatorImplCopyWith<_$BlocCreatorImpl> get copyWith =>
      __$$BlocCreatorImplCopyWithImpl<_$BlocCreatorImpl>(this, _$identity);

  @override
  Map<String, dynamic> toJson() {
    return _$$BlocCreatorImplToJson(
      this,
    );
  }
}

abstract class _BlocCreator implements BlocCreator {
  const factory _BlocCreator(
      {@JsonKey(name: '_id') required final String id,
      final String? name,
      final String? email,
      final String? profileImage}) = _$BlocCreatorImpl;

  factory _BlocCreator.fromJson(Map<String, dynamic> json) =
      _$BlocCreatorImpl.fromJson;

  @override
  @JsonKey(name: '_id')
  String get id;
  @override
  String? get name;
  @override
  String? get email;
  @override
  String? get profileImage;
  @override
  @JsonKey(ignore: true)
  _$$BlocCreatorImplCopyWith<_$BlocCreatorImpl> get copyWith =>
      throw _privateConstructorUsedError;
}

BlocMemberBasic _$BlocMemberBasicFromJson(Map<String, dynamic> json) {
  return _BlocMemberBasic.fromJson(json);
}

/// @nodoc
mixin _$BlocMemberBasic {
  @JsonKey(name: '_id')
  String get id => throw _privateConstructorUsedError;
  String? get name => throw _privateConstructorUsedError;
  String? get email => throw _privateConstructorUsedError;
  String? get joinDate => throw _privateConstructorUsedError;

  Map<String, dynamic> toJson() => throw _privateConstructorUsedError;
  @JsonKey(ignore: true)
  $BlocMemberBasicCopyWith<BlocMemberBasic> get copyWith =>
      throw _privateConstructorUsedError;
}

/// @nodoc
abstract class $BlocMemberBasicCopyWith<$Res> {
  factory $BlocMemberBasicCopyWith(
          BlocMemberBasic value, $Res Function(BlocMemberBasic) then) =
      _$BlocMemberBasicCopyWithImpl<$Res, BlocMemberBasic>;
  @useResult
  $Res call(
      {@JsonKey(name: '_id') String id,
      String? name,
      String? email,
      String? joinDate});
}

/// @nodoc
class _$BlocMemberBasicCopyWithImpl<$Res, $Val extends BlocMemberBasic>
    implements $BlocMemberBasicCopyWith<$Res> {
  _$BlocMemberBasicCopyWithImpl(this._value, this._then);

  // ignore: unused_field
  final $Val _value;
  // ignore: unused_field
  final $Res Function($Val) _then;

  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? id = null,
    Object? name = freezed,
    Object? email = freezed,
    Object? joinDate = freezed,
  }) {
    return _then(_value.copyWith(
      id: null == id
          ? _value.id
          : id // ignore: cast_nullable_to_non_nullable
              as String,
      name: freezed == name
          ? _value.name
          : name // ignore: cast_nullable_to_non_nullable
              as String?,
      email: freezed == email
          ? _value.email
          : email // ignore: cast_nullable_to_non_nullable
              as String?,
      joinDate: freezed == joinDate
          ? _value.joinDate
          : joinDate // ignore: cast_nullable_to_non_nullable
              as String?,
    ) as $Val);
  }
}

/// @nodoc
abstract class _$$BlocMemberBasicImplCopyWith<$Res>
    implements $BlocMemberBasicCopyWith<$Res> {
  factory _$$BlocMemberBasicImplCopyWith(_$BlocMemberBasicImpl value,
          $Res Function(_$BlocMemberBasicImpl) then) =
      __$$BlocMemberBasicImplCopyWithImpl<$Res>;
  @override
  @useResult
  $Res call(
      {@JsonKey(name: '_id') String id,
      String? name,
      String? email,
      String? joinDate});
}

/// @nodoc
class __$$BlocMemberBasicImplCopyWithImpl<$Res>
    extends _$BlocMemberBasicCopyWithImpl<$Res, _$BlocMemberBasicImpl>
    implements _$$BlocMemberBasicImplCopyWith<$Res> {
  __$$BlocMemberBasicImplCopyWithImpl(
      _$BlocMemberBasicImpl _value, $Res Function(_$BlocMemberBasicImpl) _then)
      : super(_value, _then);

  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? id = null,
    Object? name = freezed,
    Object? email = freezed,
    Object? joinDate = freezed,
  }) {
    return _then(_$BlocMemberBasicImpl(
      id: null == id
          ? _value.id
          : id // ignore: cast_nullable_to_non_nullable
              as String,
      name: freezed == name
          ? _value.name
          : name // ignore: cast_nullable_to_non_nullable
              as String?,
      email: freezed == email
          ? _value.email
          : email // ignore: cast_nullable_to_non_nullable
              as String?,
      joinDate: freezed == joinDate
          ? _value.joinDate
          : joinDate // ignore: cast_nullable_to_non_nullable
              as String?,
    ));
  }
}

/// @nodoc
@JsonSerializable()
class _$BlocMemberBasicImpl implements _BlocMemberBasic {
  const _$BlocMemberBasicImpl(
      {@JsonKey(name: '_id') required this.id,
      this.name,
      this.email,
      this.joinDate});

  factory _$BlocMemberBasicImpl.fromJson(Map<String, dynamic> json) =>
      _$$BlocMemberBasicImplFromJson(json);

  @override
  @JsonKey(name: '_id')
  final String id;
  @override
  final String? name;
  @override
  final String? email;
  @override
  final String? joinDate;

  @override
  String toString() {
    return 'BlocMemberBasic(id: $id, name: $name, email: $email, joinDate: $joinDate)';
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is _$BlocMemberBasicImpl &&
            (identical(other.id, id) || other.id == id) &&
            (identical(other.name, name) || other.name == name) &&
            (identical(other.email, email) || other.email == email) &&
            (identical(other.joinDate, joinDate) ||
                other.joinDate == joinDate));
  }

  @JsonKey(ignore: true)
  @override
  int get hashCode => Object.hash(runtimeType, id, name, email, joinDate);

  @JsonKey(ignore: true)
  @override
  @pragma('vm:prefer-inline')
  _$$BlocMemberBasicImplCopyWith<_$BlocMemberBasicImpl> get copyWith =>
      __$$BlocMemberBasicImplCopyWithImpl<_$BlocMemberBasicImpl>(
          this, _$identity);

  @override
  Map<String, dynamic> toJson() {
    return _$$BlocMemberBasicImplToJson(
      this,
    );
  }
}

abstract class _BlocMemberBasic implements BlocMemberBasic {
  const factory _BlocMemberBasic(
      {@JsonKey(name: '_id') required final String id,
      final String? name,
      final String? email,
      final String? joinDate}) = _$BlocMemberBasicImpl;

  factory _BlocMemberBasic.fromJson(Map<String, dynamic> json) =
      _$BlocMemberBasicImpl.fromJson;

  @override
  @JsonKey(name: '_id')
  String get id;
  @override
  String? get name;
  @override
  String? get email;
  @override
  String? get joinDate;
  @override
  @JsonKey(ignore: true)
  _$$BlocMemberBasicImplCopyWith<_$BlocMemberBasicImpl> get copyWith =>
      throw _privateConstructorUsedError;
}

BlocManualMember _$BlocManualMemberFromJson(Map<String, dynamic> json) {
  return _BlocManualMember.fromJson(json);
}

/// @nodoc
mixin _$BlocManualMember {
  String? get id => throw _privateConstructorUsedError;
  String? get firstName => throw _privateConstructorUsedError;
  String? get lastName => throw _privateConstructorUsedError;
  String? get phoneNumber => throw _privateConstructorUsedError;
  String? get state => throw _privateConstructorUsedError;
  String? get lga => throw _privateConstructorUsedError;
  String? get ward => throw _privateConstructorUsedError;
  String? get addedBy => throw _privateConstructorUsedError;
  String? get addedAt => throw _privateConstructorUsedError;

  Map<String, dynamic> toJson() => throw _privateConstructorUsedError;
  @JsonKey(ignore: true)
  $BlocManualMemberCopyWith<BlocManualMember> get copyWith =>
      throw _privateConstructorUsedError;
}

/// @nodoc
abstract class $BlocManualMemberCopyWith<$Res> {
  factory $BlocManualMemberCopyWith(
          BlocManualMember value, $Res Function(BlocManualMember) then) =
      _$BlocManualMemberCopyWithImpl<$Res, BlocManualMember>;
  @useResult
  $Res call(
      {String? id,
      String? firstName,
      String? lastName,
      String? phoneNumber,
      String? state,
      String? lga,
      String? ward,
      String? addedBy,
      String? addedAt});
}

/// @nodoc
class _$BlocManualMemberCopyWithImpl<$Res, $Val extends BlocManualMember>
    implements $BlocManualMemberCopyWith<$Res> {
  _$BlocManualMemberCopyWithImpl(this._value, this._then);

  // ignore: unused_field
  final $Val _value;
  // ignore: unused_field
  final $Res Function($Val) _then;

  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? id = freezed,
    Object? firstName = freezed,
    Object? lastName = freezed,
    Object? phoneNumber = freezed,
    Object? state = freezed,
    Object? lga = freezed,
    Object? ward = freezed,
    Object? addedBy = freezed,
    Object? addedAt = freezed,
  }) {
    return _then(_value.copyWith(
      id: freezed == id
          ? _value.id
          : id // ignore: cast_nullable_to_non_nullable
              as String?,
      firstName: freezed == firstName
          ? _value.firstName
          : firstName // ignore: cast_nullable_to_non_nullable
              as String?,
      lastName: freezed == lastName
          ? _value.lastName
          : lastName // ignore: cast_nullable_to_non_nullable
              as String?,
      phoneNumber: freezed == phoneNumber
          ? _value.phoneNumber
          : phoneNumber // ignore: cast_nullable_to_non_nullable
              as String?,
      state: freezed == state
          ? _value.state
          : state // ignore: cast_nullable_to_non_nullable
              as String?,
      lga: freezed == lga
          ? _value.lga
          : lga // ignore: cast_nullable_to_non_nullable
              as String?,
      ward: freezed == ward
          ? _value.ward
          : ward // ignore: cast_nullable_to_non_nullable
              as String?,
      addedBy: freezed == addedBy
          ? _value.addedBy
          : addedBy // ignore: cast_nullable_to_non_nullable
              as String?,
      addedAt: freezed == addedAt
          ? _value.addedAt
          : addedAt // ignore: cast_nullable_to_non_nullable
              as String?,
    ) as $Val);
  }
}

/// @nodoc
abstract class _$$BlocManualMemberImplCopyWith<$Res>
    implements $BlocManualMemberCopyWith<$Res> {
  factory _$$BlocManualMemberImplCopyWith(_$BlocManualMemberImpl value,
          $Res Function(_$BlocManualMemberImpl) then) =
      __$$BlocManualMemberImplCopyWithImpl<$Res>;
  @override
  @useResult
  $Res call(
      {String? id,
      String? firstName,
      String? lastName,
      String? phoneNumber,
      String? state,
      String? lga,
      String? ward,
      String? addedBy,
      String? addedAt});
}

/// @nodoc
class __$$BlocManualMemberImplCopyWithImpl<$Res>
    extends _$BlocManualMemberCopyWithImpl<$Res, _$BlocManualMemberImpl>
    implements _$$BlocManualMemberImplCopyWith<$Res> {
  __$$BlocManualMemberImplCopyWithImpl(_$BlocManualMemberImpl _value,
      $Res Function(_$BlocManualMemberImpl) _then)
      : super(_value, _then);

  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? id = freezed,
    Object? firstName = freezed,
    Object? lastName = freezed,
    Object? phoneNumber = freezed,
    Object? state = freezed,
    Object? lga = freezed,
    Object? ward = freezed,
    Object? addedBy = freezed,
    Object? addedAt = freezed,
  }) {
    return _then(_$BlocManualMemberImpl(
      id: freezed == id
          ? _value.id
          : id // ignore: cast_nullable_to_non_nullable
              as String?,
      firstName: freezed == firstName
          ? _value.firstName
          : firstName // ignore: cast_nullable_to_non_nullable
              as String?,
      lastName: freezed == lastName
          ? _value.lastName
          : lastName // ignore: cast_nullable_to_non_nullable
              as String?,
      phoneNumber: freezed == phoneNumber
          ? _value.phoneNumber
          : phoneNumber // ignore: cast_nullable_to_non_nullable
              as String?,
      state: freezed == state
          ? _value.state
          : state // ignore: cast_nullable_to_non_nullable
              as String?,
      lga: freezed == lga
          ? _value.lga
          : lga // ignore: cast_nullable_to_non_nullable
              as String?,
      ward: freezed == ward
          ? _value.ward
          : ward // ignore: cast_nullable_to_non_nullable
              as String?,
      addedBy: freezed == addedBy
          ? _value.addedBy
          : addedBy // ignore: cast_nullable_to_non_nullable
              as String?,
      addedAt: freezed == addedAt
          ? _value.addedAt
          : addedAt // ignore: cast_nullable_to_non_nullable
              as String?,
    ));
  }
}

/// @nodoc
@JsonSerializable()
class _$BlocManualMemberImpl implements _BlocManualMember {
  const _$BlocManualMemberImpl(
      {this.id,
      this.firstName,
      this.lastName,
      this.phoneNumber,
      this.state,
      this.lga,
      this.ward,
      this.addedBy,
      this.addedAt});

  factory _$BlocManualMemberImpl.fromJson(Map<String, dynamic> json) =>
      _$$BlocManualMemberImplFromJson(json);

  @override
  final String? id;
  @override
  final String? firstName;
  @override
  final String? lastName;
  @override
  final String? phoneNumber;
  @override
  final String? state;
  @override
  final String? lga;
  @override
  final String? ward;
  @override
  final String? addedBy;
  @override
  final String? addedAt;

  @override
  String toString() {
    return 'BlocManualMember(id: $id, firstName: $firstName, lastName: $lastName, phoneNumber: $phoneNumber, state: $state, lga: $lga, ward: $ward, addedBy: $addedBy, addedAt: $addedAt)';
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is _$BlocManualMemberImpl &&
            (identical(other.id, id) || other.id == id) &&
            (identical(other.firstName, firstName) ||
                other.firstName == firstName) &&
            (identical(other.lastName, lastName) ||
                other.lastName == lastName) &&
            (identical(other.phoneNumber, phoneNumber) ||
                other.phoneNumber == phoneNumber) &&
            (identical(other.state, state) || other.state == state) &&
            (identical(other.lga, lga) || other.lga == lga) &&
            (identical(other.ward, ward) || other.ward == ward) &&
            (identical(other.addedBy, addedBy) || other.addedBy == addedBy) &&
            (identical(other.addedAt, addedAt) || other.addedAt == addedAt));
  }

  @JsonKey(ignore: true)
  @override
  int get hashCode => Object.hash(runtimeType, id, firstName, lastName,
      phoneNumber, state, lga, ward, addedBy, addedAt);

  @JsonKey(ignore: true)
  @override
  @pragma('vm:prefer-inline')
  _$$BlocManualMemberImplCopyWith<_$BlocManualMemberImpl> get copyWith =>
      __$$BlocManualMemberImplCopyWithImpl<_$BlocManualMemberImpl>(
          this, _$identity);

  @override
  Map<String, dynamic> toJson() {
    return _$$BlocManualMemberImplToJson(
      this,
    );
  }
}

abstract class _BlocManualMember implements BlocManualMember {
  const factory _BlocManualMember(
      {final String? id,
      final String? firstName,
      final String? lastName,
      final String? phoneNumber,
      final String? state,
      final String? lga,
      final String? ward,
      final String? addedBy,
      final String? addedAt}) = _$BlocManualMemberImpl;

  factory _BlocManualMember.fromJson(Map<String, dynamic> json) =
      _$BlocManualMemberImpl.fromJson;

  @override
  String? get id;
  @override
  String? get firstName;
  @override
  String? get lastName;
  @override
  String? get phoneNumber;
  @override
  String? get state;
  @override
  String? get lga;
  @override
  String? get ward;
  @override
  String? get addedBy;
  @override
  String? get addedAt;
  @override
  @JsonKey(ignore: true)
  _$$BlocManualMemberImplCopyWith<_$BlocManualMemberImpl> get copyWith =>
      throw _privateConstructorUsedError;
}

BlocToolkit _$BlocToolkitFromJson(Map<String, dynamic> json) {
  return _BlocToolkit.fromJson(json);
}

/// @nodoc
mixin _$BlocToolkit {
  String get label => throw _privateConstructorUsedError;
  String get url => throw _privateConstructorUsedError;
  String get type => throw _privateConstructorUsedError;

  Map<String, dynamic> toJson() => throw _privateConstructorUsedError;
  @JsonKey(ignore: true)
  $BlocToolkitCopyWith<BlocToolkit> get copyWith =>
      throw _privateConstructorUsedError;
}

/// @nodoc
abstract class $BlocToolkitCopyWith<$Res> {
  factory $BlocToolkitCopyWith(
          BlocToolkit value, $Res Function(BlocToolkit) then) =
      _$BlocToolkitCopyWithImpl<$Res, BlocToolkit>;
  @useResult
  $Res call({String label, String url, String type});
}

/// @nodoc
class _$BlocToolkitCopyWithImpl<$Res, $Val extends BlocToolkit>
    implements $BlocToolkitCopyWith<$Res> {
  _$BlocToolkitCopyWithImpl(this._value, this._then);

  // ignore: unused_field
  final $Val _value;
  // ignore: unused_field
  final $Res Function($Val) _then;

  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? label = null,
    Object? url = null,
    Object? type = null,
  }) {
    return _then(_value.copyWith(
      label: null == label
          ? _value.label
          : label // ignore: cast_nullable_to_non_nullable
              as String,
      url: null == url
          ? _value.url
          : url // ignore: cast_nullable_to_non_nullable
              as String,
      type: null == type
          ? _value.type
          : type // ignore: cast_nullable_to_non_nullable
              as String,
    ) as $Val);
  }
}

/// @nodoc
abstract class _$$BlocToolkitImplCopyWith<$Res>
    implements $BlocToolkitCopyWith<$Res> {
  factory _$$BlocToolkitImplCopyWith(
          _$BlocToolkitImpl value, $Res Function(_$BlocToolkitImpl) then) =
      __$$BlocToolkitImplCopyWithImpl<$Res>;
  @override
  @useResult
  $Res call({String label, String url, String type});
}

/// @nodoc
class __$$BlocToolkitImplCopyWithImpl<$Res>
    extends _$BlocToolkitCopyWithImpl<$Res, _$BlocToolkitImpl>
    implements _$$BlocToolkitImplCopyWith<$Res> {
  __$$BlocToolkitImplCopyWithImpl(
      _$BlocToolkitImpl _value, $Res Function(_$BlocToolkitImpl) _then)
      : super(_value, _then);

  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? label = null,
    Object? url = null,
    Object? type = null,
  }) {
    return _then(_$BlocToolkitImpl(
      label: null == label
          ? _value.label
          : label // ignore: cast_nullable_to_non_nullable
              as String,
      url: null == url
          ? _value.url
          : url // ignore: cast_nullable_to_non_nullable
              as String,
      type: null == type
          ? _value.type
          : type // ignore: cast_nullable_to_non_nullable
              as String,
    ));
  }
}

/// @nodoc
@JsonSerializable()
class _$BlocToolkitImpl implements _BlocToolkit {
  const _$BlocToolkitImpl(
      {required this.label, required this.url, this.type = 'Toolkit'});

  factory _$BlocToolkitImpl.fromJson(Map<String, dynamic> json) =>
      _$$BlocToolkitImplFromJson(json);

  @override
  final String label;
  @override
  final String url;
  @override
  @JsonKey()
  final String type;

  @override
  String toString() {
    return 'BlocToolkit(label: $label, url: $url, type: $type)';
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is _$BlocToolkitImpl &&
            (identical(other.label, label) || other.label == label) &&
            (identical(other.url, url) || other.url == url) &&
            (identical(other.type, type) || other.type == type));
  }

  @JsonKey(ignore: true)
  @override
  int get hashCode => Object.hash(runtimeType, label, url, type);

  @JsonKey(ignore: true)
  @override
  @pragma('vm:prefer-inline')
  _$$BlocToolkitImplCopyWith<_$BlocToolkitImpl> get copyWith =>
      __$$BlocToolkitImplCopyWithImpl<_$BlocToolkitImpl>(this, _$identity);

  @override
  Map<String, dynamic> toJson() {
    return _$$BlocToolkitImplToJson(
      this,
    );
  }
}

abstract class _BlocToolkit implements BlocToolkit {
  const factory _BlocToolkit(
      {required final String label,
      required final String url,
      final String type}) = _$BlocToolkitImpl;

  factory _BlocToolkit.fromJson(Map<String, dynamic> json) =
      _$BlocToolkitImpl.fromJson;

  @override
  String get label;
  @override
  String get url;
  @override
  String get type;
  @override
  @JsonKey(ignore: true)
  _$$BlocToolkitImplCopyWith<_$BlocToolkitImpl> get copyWith =>
      throw _privateConstructorUsedError;
}

BlocMetrics _$BlocMetricsFromJson(Map<String, dynamic> json) {
  return _BlocMetrics.fromJson(json);
}

/// @nodoc
mixin _$BlocMetrics {
  int get totalMembers => throw _privateConstructorUsedError;
  int get platformMembers => throw _privateConstructorUsedError;
  int get manualMembers => throw _privateConstructorUsedError;
  int get weeklyGrowth => throw _privateConstructorUsedError;
  int get monthlyGrowth => throw _privateConstructorUsedError;
  int get engagementScore => throw _privateConstructorUsedError;
  String? get lastUpdated => throw _privateConstructorUsedError;

  Map<String, dynamic> toJson() => throw _privateConstructorUsedError;
  @JsonKey(ignore: true)
  $BlocMetricsCopyWith<BlocMetrics> get copyWith =>
      throw _privateConstructorUsedError;
}

/// @nodoc
abstract class $BlocMetricsCopyWith<$Res> {
  factory $BlocMetricsCopyWith(
          BlocMetrics value, $Res Function(BlocMetrics) then) =
      _$BlocMetricsCopyWithImpl<$Res, BlocMetrics>;
  @useResult
  $Res call(
      {int totalMembers,
      int platformMembers,
      int manualMembers,
      int weeklyGrowth,
      int monthlyGrowth,
      int engagementScore,
      String? lastUpdated});
}

/// @nodoc
class _$BlocMetricsCopyWithImpl<$Res, $Val extends BlocMetrics>
    implements $BlocMetricsCopyWith<$Res> {
  _$BlocMetricsCopyWithImpl(this._value, this._then);

  // ignore: unused_field
  final $Val _value;
  // ignore: unused_field
  final $Res Function($Val) _then;

  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? totalMembers = null,
    Object? platformMembers = null,
    Object? manualMembers = null,
    Object? weeklyGrowth = null,
    Object? monthlyGrowth = null,
    Object? engagementScore = null,
    Object? lastUpdated = freezed,
  }) {
    return _then(_value.copyWith(
      totalMembers: null == totalMembers
          ? _value.totalMembers
          : totalMembers // ignore: cast_nullable_to_non_nullable
              as int,
      platformMembers: null == platformMembers
          ? _value.platformMembers
          : platformMembers // ignore: cast_nullable_to_non_nullable
              as int,
      manualMembers: null == manualMembers
          ? _value.manualMembers
          : manualMembers // ignore: cast_nullable_to_non_nullable
              as int,
      weeklyGrowth: null == weeklyGrowth
          ? _value.weeklyGrowth
          : weeklyGrowth // ignore: cast_nullable_to_non_nullable
              as int,
      monthlyGrowth: null == monthlyGrowth
          ? _value.monthlyGrowth
          : monthlyGrowth // ignore: cast_nullable_to_non_nullable
              as int,
      engagementScore: null == engagementScore
          ? _value.engagementScore
          : engagementScore // ignore: cast_nullable_to_non_nullable
              as int,
      lastUpdated: freezed == lastUpdated
          ? _value.lastUpdated
          : lastUpdated // ignore: cast_nullable_to_non_nullable
              as String?,
    ) as $Val);
  }
}

/// @nodoc
abstract class _$$BlocMetricsImplCopyWith<$Res>
    implements $BlocMetricsCopyWith<$Res> {
  factory _$$BlocMetricsImplCopyWith(
          _$BlocMetricsImpl value, $Res Function(_$BlocMetricsImpl) then) =
      __$$BlocMetricsImplCopyWithImpl<$Res>;
  @override
  @useResult
  $Res call(
      {int totalMembers,
      int platformMembers,
      int manualMembers,
      int weeklyGrowth,
      int monthlyGrowth,
      int engagementScore,
      String? lastUpdated});
}

/// @nodoc
class __$$BlocMetricsImplCopyWithImpl<$Res>
    extends _$BlocMetricsCopyWithImpl<$Res, _$BlocMetricsImpl>
    implements _$$BlocMetricsImplCopyWith<$Res> {
  __$$BlocMetricsImplCopyWithImpl(
      _$BlocMetricsImpl _value, $Res Function(_$BlocMetricsImpl) _then)
      : super(_value, _then);

  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? totalMembers = null,
    Object? platformMembers = null,
    Object? manualMembers = null,
    Object? weeklyGrowth = null,
    Object? monthlyGrowth = null,
    Object? engagementScore = null,
    Object? lastUpdated = freezed,
  }) {
    return _then(_$BlocMetricsImpl(
      totalMembers: null == totalMembers
          ? _value.totalMembers
          : totalMembers // ignore: cast_nullable_to_non_nullable
              as int,
      platformMembers: null == platformMembers
          ? _value.platformMembers
          : platformMembers // ignore: cast_nullable_to_non_nullable
              as int,
      manualMembers: null == manualMembers
          ? _value.manualMembers
          : manualMembers // ignore: cast_nullable_to_non_nullable
              as int,
      weeklyGrowth: null == weeklyGrowth
          ? _value.weeklyGrowth
          : weeklyGrowth // ignore: cast_nullable_to_non_nullable
              as int,
      monthlyGrowth: null == monthlyGrowth
          ? _value.monthlyGrowth
          : monthlyGrowth // ignore: cast_nullable_to_non_nullable
              as int,
      engagementScore: null == engagementScore
          ? _value.engagementScore
          : engagementScore // ignore: cast_nullable_to_non_nullable
              as int,
      lastUpdated: freezed == lastUpdated
          ? _value.lastUpdated
          : lastUpdated // ignore: cast_nullable_to_non_nullable
              as String?,
    ));
  }
}

/// @nodoc
@JsonSerializable()
class _$BlocMetricsImpl implements _BlocMetrics {
  const _$BlocMetricsImpl(
      {this.totalMembers = 0,
      this.platformMembers = 0,
      this.manualMembers = 0,
      this.weeklyGrowth = 0,
      this.monthlyGrowth = 0,
      this.engagementScore = 0,
      this.lastUpdated});

  factory _$BlocMetricsImpl.fromJson(Map<String, dynamic> json) =>
      _$$BlocMetricsImplFromJson(json);

  @override
  @JsonKey()
  final int totalMembers;
  @override
  @JsonKey()
  final int platformMembers;
  @override
  @JsonKey()
  final int manualMembers;
  @override
  @JsonKey()
  final int weeklyGrowth;
  @override
  @JsonKey()
  final int monthlyGrowth;
  @override
  @JsonKey()
  final int engagementScore;
  @override
  final String? lastUpdated;

  @override
  String toString() {
    return 'BlocMetrics(totalMembers: $totalMembers, platformMembers: $platformMembers, manualMembers: $manualMembers, weeklyGrowth: $weeklyGrowth, monthlyGrowth: $monthlyGrowth, engagementScore: $engagementScore, lastUpdated: $lastUpdated)';
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is _$BlocMetricsImpl &&
            (identical(other.totalMembers, totalMembers) ||
                other.totalMembers == totalMembers) &&
            (identical(other.platformMembers, platformMembers) ||
                other.platformMembers == platformMembers) &&
            (identical(other.manualMembers, manualMembers) ||
                other.manualMembers == manualMembers) &&
            (identical(other.weeklyGrowth, weeklyGrowth) ||
                other.weeklyGrowth == weeklyGrowth) &&
            (identical(other.monthlyGrowth, monthlyGrowth) ||
                other.monthlyGrowth == monthlyGrowth) &&
            (identical(other.engagementScore, engagementScore) ||
                other.engagementScore == engagementScore) &&
            (identical(other.lastUpdated, lastUpdated) ||
                other.lastUpdated == lastUpdated));
  }

  @JsonKey(ignore: true)
  @override
  int get hashCode => Object.hash(runtimeType, totalMembers, platformMembers,
      manualMembers, weeklyGrowth, monthlyGrowth, engagementScore, lastUpdated);

  @JsonKey(ignore: true)
  @override
  @pragma('vm:prefer-inline')
  _$$BlocMetricsImplCopyWith<_$BlocMetricsImpl> get copyWith =>
      __$$BlocMetricsImplCopyWithImpl<_$BlocMetricsImpl>(this, _$identity);

  @override
  Map<String, dynamic> toJson() {
    return _$$BlocMetricsImplToJson(
      this,
    );
  }
}

abstract class _BlocMetrics implements BlocMetrics {
  const factory _BlocMetrics(
      {final int totalMembers,
      final int platformMembers,
      final int manualMembers,
      final int weeklyGrowth,
      final int monthlyGrowth,
      final int engagementScore,
      final String? lastUpdated}) = _$BlocMetricsImpl;

  factory _BlocMetrics.fromJson(Map<String, dynamic> json) =
      _$BlocMetricsImpl.fromJson;

  @override
  int get totalMembers;
  @override
  int get platformMembers;
  @override
  int get manualMembers;
  @override
  int get weeklyGrowth;
  @override
  int get monthlyGrowth;
  @override
  int get engagementScore;
  @override
  String? get lastUpdated;
  @override
  @JsonKey(ignore: true)
  _$$BlocMetricsImplCopyWith<_$BlocMetricsImpl> get copyWith =>
      throw _privateConstructorUsedError;
}
