// central place for all your static select options

export type OptionType = { id: number; label: string; value: string };

// gender
export const genderOptions: OptionType[] = [
  { id: 1, label: "Male",   value: "Male"   },
  { id: 2, label: "Female", value: "Female" },
];

// age ranges
export const ageRangeOptions: OptionType[] = [
  { id: 1, label: "13-17 (Teenager)",  value: "13-17 (Teenager)"  },
  { id: 2, label: "18-24 (Young Adult)",  value: "18-24 (Young Adult)"  },
  { id: 3, label: "25-34 (Adult)",  value: "25-34 (Adult)"  },
  { id: 4, label: "35-44 (Middle-Aged Adult)",  value: "35-44 (Middle-Aged Adult)"  },
  { id: 5, label: "45-54 (Older Adult)",    value: "45-54 (Older Adult)"    },
  { id: 6, label: "55-64 (Senior Adult)",    value: "55-64 (Senior Adult)"    },
  { id: 7, label: "65+ (Elderly)",    value: "65+ (Elderly)"    },
];

// political parties
export const politicalPartyOptions: OptionType[] = [
  { id: 1, label: "None", value: "None" },
  { id: 2, label: "All Progressives Congress (APC)", value: "APC" },
  { id: 3, label: "Peoples Democratic Party (PDP)", value: "PDP" },
  { id: 4, label: "Labour Party (LP)", value: "LP" },
  { id: 5, label: "All Progressives Grand Alliance (APGA)", value: "APGA" },
  { id: 6, label: "New Nigeria People's Party (NNPP)", value: "NNPP" },
  { id: 7, label: "Young Progressives Party (YPP)", value: "YPP" },
  { id: 8, label: "Social Democratic Party (SDP)", value: "SDP" },
  { id: 9, label: "African Democratic Congress (ADC)", value: "ADC" },
  { id: 10, label: "Accord (A)", value: "A" },
  { id: 11, label: "Action Alliance (AA)", value: "AA" },
  { id: 12, label: "Action Democratic Party (ADP)", value: "ADP" },
  { id: 13, label: "Action Peoples Party (APP)", value: "APP" },
  { id: 14, label: "African Action Congress (AAC)", value: "AAC" },
  { id: 15, label: "Allied Peoples Movement (APM)", value: "APM" },
  { id: 16, label: "Boot Party (BP)", value: "BP" },
  { id: 17, label: "National Rescue Movement (NRM)", value: "NRM" },
  { id: 18, label: "Peoples Redemption Party (PRP)", value: "PRP" },
  { id: 19, label: "YOUTH PARTY (YP)", value: "YP" },
  { id: 20, label: "Zenith Labour Party (ZLP)", value: "ZLP" },
];

// political issues
export const politicalIssueOptions: OptionType[] = [
  { id: 1, label: "Corruption and lack of accountability in governance", value: "Corruption and lack of accountability in governance" },
  { id: 2, label: "Electoral irregularities", value: "Electoral irregularities" },
  { id: 3, label: "Insecurity", value: "Insecurity" },
  { id: 4, label: "Ethnic and religious tensions", value: "Ethnic and religious tensions" },
  { id: 5, label: "Unemployment", value: "Unemployment" },
  { id: 6, label: "Poor infrastructure", value: "Poor infrastructure" },
  { id: 7, label: "Education system crisis", value: "Education system crisis" },
  { id: 8, label: "Weak judiciary and rule of law", value: "Weak judiciary and rule of law" },
  { id: 9, label: "Oil dependency and economic diversification challenges", value: "Oil dependency and economic diversification challenges" },
  { id: 10, label: "Poverty and widening inequality", value: "Poverty and widening inequality" },
  { id: 11, label: "Environmental degradation", value: "Environmental degradation" },
  { id: 12, label: "Human rights violations and police brutality", value: "Human rights violations and police brutality" },
  { id: 13, label: "Insufficient healthcare system", value: "Insufficient healthcare system" },
  { id: 14, label: "Gender inequality", value: "Gender inequality" },
  { id: 15, label: "Weak legislative oversight", value: "Weak legislative oversight" },
];

// occupation categories
export const occupationCategoryOptions: OptionType[] = [
  { id: 1, label: "Management Occupations", value: "Management Occupations" },
  { id: 2, label: "Business and Financial Operations Occupations", value: "Business and Financial Operations Occupations" },
  { id: 3, label: "Computer and Mathematical Occupations", value: "Computer and Mathematical Occupations" },
  { id: 4, label: "Architecture and Engineering Occupations", value: "Architecture and Engineering Occupations" },
  { id: 5, label: "Life, Physical, and Social Science Occupations", value: "Life, Physical, and Social Science Occupations" },
  { id: 6, label: "Community and Social Service Occupations", value: "Community and Social Service Occupations" },
  { id: 7, label: "Legal Occupations", value: "Legal Occupations" },
  { id: 8, label: "Educational Instruction and Library Occupations", value: "Educational Instruction and Library Occupations" },
  { id: 9, label: "Arts, Design, Entertainment, Sports, and Media Occupations", value: "Arts, Design, Entertainment, Sports, and Media Occupations" },
  { id: 10, label: "Healthcare Practitioners and Technical Occupations", value: "Healthcare Practitioners and Technical Occupations" },
  { id: 11, label: "Healthcare Support Occupations", value: "Healthcare Support Occupations" },
  { id: 12, label: "Protective Service Occupations", value: "Protective Service Occupations" },
  { id: 13, label: "Food Preparation and Serving Related Occupations", value: "Food Preparation and Serving Related Occupations" },
  { id: 14, label: "Building and Grounds Cleaning and Maintenance Occupations", value: "Building and Grounds Cleaning and Maintenance Occupations" },
  { id: 15, label: "Personal Care and Service Occupations", value: "Personal Care and Service Occupations" },
  { id: 16, label: "Sales and Related Occupations", value: "Sales and Related Occupations" },
  { id: 17, label: "Office and Administrative Support Occupations", value: "Office and Administrative Support Occupations" },
  { id: 18, label: "Farming, Fishing, and Forestry Occupations", value: "Farming, Fishing, and Forestry Occupations" },
  { id: 19, label: "Construction and Extraction Occupations", value: "Construction and Extraction Occupations" },
  { id: 20, label: "Installation, Maintenance, and Repair Occupations", value: "Installation, Maintenance, and Repair Occupations" },
  { id: 21, label: "Production Occupations", value: "Production Occupations" },
  { id: 22, label: "Transportation and Material Moving Occupations", value: "Transportation and Material Moving Occupations" },
  { id: 23, label: "others", value: "others" },
];

// marital status
export const maritalStatusOptions: OptionType[] = [
  { id: 1, label: "Single", value: "Single" },
  { id: 2, label: "Married", value: "Married" },
  { id: 3, label: "Divorced", value: "Divorced" },
  { id: 4, label: "Widowed", value: "Widowed" },
  { id: 5, label: "Separated", value: "Separated" },
  { id: 6, label: "In a Relationship", value: "In a Relationship" },
];

// level of education
export const levelOfEducationOptions: OptionType[] = [
  { id: 1, label: "No Formal Education", value: "No Formal Education" },
  { id: 2, label: "Primary Education", value: "Primary Education" },
  { id: 3, label: "Secondary Education", value: "Secondary Education" },
  { id: 4, label: "Vocational Training", value: "Vocational Training" },
  { id: 5, label: "Bachelor's Degree", value: "Bachelor's Degree" },
  { id: 6, label: "Master's Degree", value: "Master's Degree" },
  { id: 7, label: "Doctorate (Ph.D.)", value: "Doctorate (Ph.D.)" },
  { id: 8, label: "Other", value: "Other" },
];

// income bracket
export const incomeBracketOptions: OptionType[] = [
  { id: 1, label: "Less than ₦100,000/month", value: "Less than ₦100,000/month" },
  { id: 2, label: "₦100,000 - ₦500,000/month", value: "₦100,000 - ₦500,000/month" },
  { id: 3, label: "₦500,000 - ₦1,000,000/month", value: "₦500,000 - ₦1,000,000/month" },
  { id: 4, label: "₦1,000,000 - ₦5,000,000/month", value: "₦1,000,000 - ₦5,000,000/month" },
  { id: 5, label: "Over ₦5,000,000/month", value: "Over ₦5,000,000/month" },
];

// household size
export const householdSizeOptions: OptionType[] = [
  { id: 1, label: "1 (Living Alone)", value: "1 (Living Alone)" },
  { id: 2, label: "2 (Small Household)", value: "2 (Small Household)" },
  { id: 3, label: "3 - 4 (Medium Household)", value: "3 - 4 (Medium Household)" },
  { id: 4, label: "5 - 6 (Large Household)", value: "5 - 6 (Large Household)" },
  { id: 5, label: "7+ (Very Large Household)", value: "7+ (Very Large Household)" },
];

// ethnic groups
export const ethnicGroupOptions: OptionType[] = [
  { id: 1, label: "Abayon", value: "Abayon" },
  { id: 2, label: "Abua (Odual)", value: "Abua (Odual)" },
  { id: 3, label: "Achipa (Achipawa)", value: "Achipa (Achipawa)" },
  { id: 4, label: "Adara (Kadara)", value: "Adara (Kadara)" },
  { id: 5, label: "Affade", value: "Affade" },
  { id: 6, label: "Afizere", value: "Afizere" },
  { id: 7, label: "Afo (Eloyi)", value: "Afo (Eloyi)" },
  { id: 8, label: "Agbo", value: "Agbo" },
  { id: 9, label: "Akaju-Ndem (Akajuk)", value: "Akaju-Ndem (Akajuk)" },
  { id: 10, label: "Akweya-Yachi", value: "Akweya-Yachi" },
  { id: 11, label: "Alago (Arago)", value: "Alago (Arago)" },
  { id: 12, label: "Amo", value: "Amo" },
  { id: 13, label: "Anaguta", value: "Anaguta" },
  { id: 14, label: "Anang", value: "Anang" },
  { id: 15, label: "Andoni", value: "Andoni" },
  { id: 16, label: "Ankwei", value: "Ankwei" },
  { id: 17, label: "Anyima", value: "Anyima" },
  { id: 18, label: "Atyap (Kataf/Katab, Attakar, Kagoro, Kafanchan, Marwa/Manchok)", value: "Atyap (Kataf/Katab, Attakar, Kagoro, Kafanchan, Marwa/Manchok)" },
  { id: 19, label: "Auyoka (Sub-Hausa)", value: "Auyoka (Sub-Hausa)" },
  { id: 20, label: "Awori", value: "Awori" },
  { id: 21, label: "Ayu", value: "Ayu" },
  { id: 22, label: "Bura-Pabir", value: "Bura-Pabir" },
  { id: 23, label: "Bachama", value: "Bachama" },
  { id: 24, label: "Bachere", value: "Bachere" },
  { id: 25, label: "Bada", value: "Bada" },
  { id: 26, label: "Bade", value: "Bade" },
  { id: 27, label: "Bahumono", value: "Bahumono" },
  { id: 28, label: "Bakulung", value: "Bakulung" },
  { id: 29, label: "Bali", value: "Bali" },
  { id: 30, label: "Bambora (Bambarawa)", value: "Bambora (Bambarawa)" },
  { id: 31, label: "Bambuko", value: "Bambuko" },
  { id: 32, label: "Bajju (Kaje, Kajji)", value: "Bajju (Kaje, Kajji)" },
  { id: 33, label: "Banda (Bandawa)", value: "Banda (Bandawa)" },
  { id: 34, label: "Banka (Bankalawa)", value: "Banka (Bankalawa)" },
  { id: 35, label: "Banso (Panso)", value: "Banso (Panso)" },
  { id: 36, label: "Bara (Barawa)", value: "Bara (Barawa)" },
  { id: 37, label: "Barke", value: "Barke" },
  { id: 38, label: "Baruba (Batonu)", value: "Baruba (Batonu)" },
  { id: 39, label: "Bashiri (Bashirawa)", value: "Bashiri (Bashirawa)" },
  { id: 40, label: "Bassa", value: "Bassa" },
  { id: 41, label: "Batta", value: "Batta" },
  { id: 42, label: "Baushi", value: "Baushi" },
  { id: 43, label: "Baya", value: "Baya" },
  { id: 44, label: "Bekwarra", value: "Bekwarra" },
  { id: 45, label: "Bele (Buli, Belewa)", value: "Bele (Buli, Belewa)" },
  { id: 46, label: "Berom (Birom)", value: "Berom (Birom)" },
  { id: 47, label: "Betso (Bete)", value: "Betso (Bete)" },
  { id: 48, label: "Bette", value: "Bette" },
  { id: 49, label: "Bille", value: "Bille" },
  { id: 50, label: "Bina (Binawa)", value: "Bina (Binawa)" },
  { id: 51, label: "Bini (Edo)", value: "Bini (Edo)" },
  { id: 52, label: "Bobua", value: "Bobua" },
  { id: 53, label: "Boki (Nki)", value: "Boki (Nki)" },
  { id: 54, label: "Bokkos", value: "Bokkos" },
  { id: 55, label: "Boko (Bussawa, Bargawa)", value: "Boko (Bussawa, Bargawa)" },
  { id: 56, label: "Bole (Bolewa)", value: "Bole (Bolewa)" },
  { id: 57, label: "Botlere", value: "Botlere" },
  { id: 58, label: "Boma (Bomawa, Burmano)", value: "Boma (Bomawa, Burmano)" },
  { id: 59, label: "Bomboro", value: "Bomboro" },
  { id: 60, label: "Buduma", value: "Buduma" },
  { id: 61, label: "Buji", value: "Buji" },
  { id: 62, label: "Buli", value: "Buli" },
  { id: 63, label: "Bunu", value: "Bunu" },
  { id: 64, label: "Burak", value: "Burak" },
  { id: 65, label: "Burma (Burmawa)", value: "Burma (Burmawa)" },
  { id: 66, label: "Buru", value: "Buru" },
  { id: 67, label: "Buta (Butawa)", value: "Buta (Butawa)" },
  { id: 68, label: "Bwall", value: "Bwall" },
  { id: 69, label: "Bwatiye", value: "Bwatiye" },
  { id: 70, label: "Bwazza", value: "Bwazza" },
  { id: 71, label: "Challa", value: "Challa" },
  { id: 72, label: "Chama (Chamawa Fitilai)", value: "Chama (Chamawa Fitilai)" },
  { id: 73, label: "Chamba", value: "Chamba" },
  { id: 74, label: "Chamo", value: "Chamo" },
  { id: 75, label: "Chibok (Kibaku people)", value: "Chibok (Kibaku people)" },
  { id: 76, label: "Chinine", value: "Chinine" },
  { id: 77, label: "Chip", value: "Chip" },
  { id: 78, label: "Chokobo", value: "Chokobo" },
  { id: 79, label: "Chukkol", value: "Chukkol" },
  { id: 80, label: "Daba", value: "Daba" },
  { id: 81, label: "Dadiya", value: "Dadiya" },
  { id: 82, label: "Daka", value: "Daka" },
  { id: 83, label: "Dakarkari", value: "Dakarkari" },
  { id: 84, label: "Danda (Dandawa)", value: "Danda (Dandawa)" },
  { id: 85, label: "Dangsa", value: "Dangsa" },
  { id: 86, label: "Daza (Dere, Derewa)", value: "Daza (Dere, Derewa)" },
  { id: 87, label: "Deno (Denawa)", value: "Deno (Denawa)" },
  { id: 88, label: "Dghwede", value: "Dghwede" },
  { id: 89, label: "Diba", value: "Diba" },
  { id: 90, label: "Doemak (Dumuk)", value: "Doemak (Dumuk)" },
  { id: 91, label: "Ouguri", value: "Ouguri" },
  { id: 92, label: "Duka (Dukawa)", value: "Duka (Dukawa)" },
  { id: 93, label: "Dundudun (Dunka)", value: "Dundudun (Dunka)" },
  { id: 94, label: "Duma (Dumawa)", value: "Duma (Dumawa)" },
  { id: 95, label: "Ebana (Ebani)", value: "Ebana (Ebani)" },
  { id: 96, label: "Ebira", value: "Ebira" },
  { id: 97, label: "Ebu", value: "Ebu" },
  { id: 98, label: "Efik", value: "Efik" },
  { id: 99, label: "Egede (Igede)", value: "Egede (Igede)" },
  { id: 100, label: "Eggon", value: "Eggon" },
  { id: 101, label: "Egun (Gu)", value: "Egun (Gu)" },
  { id: 102, label: "Ejagham", value: "Ejagham" },
  { id: 103, label: "Ekajuk", value: "Ekajuk" },
  { id: 104, label: "Eket", value: "Eket" },
  { id: 105, label: "Ekoi", value: "Ekoi" },
  { id: 106, label: "Engenni (Ngene)", value: "Engenni (Ngene)" },
  { id: 107, label: "Epie", value: "Epie" },
  { id: 108, label: "Esan (Ishan)", value: "Esan (Ishan)" },
  { id: 109, label: "Esit Ekid", value: "Esit Ekid" },
  { id: 110, label: "Etolu (Etilo)", value: "Etolu (Etilo)" },
  { id: 111, label: "Etsako", value: "Etsako" },
  { id: 112, label: "Etung", value: "Etung" },
  { id: 113, label: "Etuno", value: "Etuno" },
  { id: 114, label: "Palli", value: "Palli" },
  { id: 115, label: "Fulani (Fulbe)", value: "Fulani (Fulbe)" },
  { id: 116, label: "Fyam (Fyem)", value: "Fyam (Fyem)" },
  { id: 117, label: "Fyer (Fer)", value: "Fyer (Fer)" },
  { id: 118, label: "Ga'anda", value: "Ga'anda" },
  { id: 119, label: "Gade people", value: "Gade people" },
  { id: 120, label: "Galambi", value: "Galambi" },
  { id: 121, label: "Gamergu-Mulgwa", value: "Gamergu-Mulgwa" },
  { id: 122, label: "Gavako", value: "Gavako" },
  { id: 123, label: "Gbedde", value: "Gbedde" },
  { id: 124, label: "Gengle", value: "Gengle" },
  { id: 125, label: "Geji", value: "Geji" },
  { id: 126, label: "Gera (Gere, Gerawa)", value: "Gera (Gere, Gerawa)" },
  { id: 127, label: "Geruma (Gerumawa)", value: "Geruma (Gerumawa)" },
  { id: 128, label: "Gingwak", value: "Gingwak" },
  { id: 129, label: "Gira", value: "Gira" },
  { id: 130, label: "Gizigz", value: "Gizigz" },
  { id: 131, label: "Goemai", value: "Goemai" },
  { id: 132, label: "Gokana (Kana)", value: "Gokana (Kana)" },
  { id: 133, label: "Gombi", value: "Gombi" },
  { id: 134, label: "Gornun (Gmun)", value: "Gornun (Gmun)" },
  { id: 135, label: "Gonia", value: "Gonia" },
  { id: 136, label: "Gubi (Gubawa)", value: "Gubi (Gubawa)" },
  { id: 137, label: "Gude", value: "Gude" },
  { id: 138, label: "Gudu", value: "Gudu" },
  { id: 139, label: "Gure", value: "Gure" },
  { id: 140, label: "Gurmana", value: "Gurmana" },
  { id: 141, label: "Gururntum", value: "Gururntum" },
  { id: 142, label: "Gusu", value: "Gusu" },
  { id: 143, label: "Gwa (Gurawa)", value: "Gwa (Gurawa)" },
  { id: 144, label: "Gwamba", value: "Gwamba" },
  { id: 145, label: "Gwandara", value: "Gwandara" },
  { id: 146, label: "Gwari (Gbagyi)", value: "Gwari (Gbagyi)" },
  { id: 147, label: "Gwong (Kagoma)", value: "Gwong (Kagoma)" },
  { id: 148, label: "Gwom", value: "Gwom" },
  { id: 149, label: "Gwoza (Waha)", value: "Gwoza (Waha)" },
  { id: 150, label: "Gyem", value: "Gyem" },
  { id: 151, label: "Ham (Hyam, Jaba, Jabba)", value: "Ham (Hyam, Jaba, Jabba)" },
  { id: 152, label: "Hausa", value: "Hausa" },
  { id: 153, label: "Holma", value: "Holma" },
  { id: 154, label: "Hona", value: "Hona" },
  { id: 155, label: "Ibani", value: "Ibani" },
  { id: 156, label: "Ibeno", value: "Ibeno" },
  { id: 157, label: "Ibibio", value: "Ibibio" },
  { id: 158, label: "Ichen", value: "Ichen" },
  { id: 159, label: "Idoma", value: "Idoma" },
  { id: 160, label: "Igala", value: "Igala" },
  { id: 161, label: "Igbira", value: "Igbira" },
  { id: 162, label: "Igbo", value: "Igbo" },
  { id: 163, label: "Igede", value: "Igede" },
  { id: 164, label: "Ijumu", value: "Ijumu" },
  { id: 165, label: "Ika", value: "Ika" },
  { id: 166, label: "Ikom", value: "Ikom" },
  { id: 167, label: "Irigwe", value: "Irigwe" },
  { id: 168, label: "Iman", value: "Iman" },
  { id: 169, label: "Isoko", value: "Isoko" },
  { id: 170, label: "Itsekiri (Isekiri)", value: "Itsekiri (Isekiri)" },
  { id: 171, label: "Itu", value: "Itu" },
  { id: 172, label: "Itu Mbon Uso", value: "Itu Mbon Uso" },
  { id: 173, label: "Iyala (Iyalla)", value: "Iyala (Iyalla)" },
  { id: 174, label: "Izon (Ijaw)", value: "Izon (Ijaw)" },
  { id: 175, label: "Jahuna (Jahunawa)", value: "Jahuna (Jahunawa)" },
  { id: 176, label: "Jaku", value: "Jaku" },
  { id: 177, label: "Jara (Jaar Jarawa Jarawa-Dutse)", value: "Jara (Jaar Jarawa Jarawa-Dutse)" },
  { id: 178, label: "Jere (Jare, Jera, Jera, Jerawa)", value: "Jere (Jare, Jera, Jera, Jerawa)" },
  { id: 179, label: "Jero", value: "Jero" },
  { id: 180, label: "Jibu", value: "Jibu" },
  { id: 181, label: "Jidda-Abu", value: "Jidda-Abu" },
  { id: 182, label: "Jimbin (Jimbinawa)", value: "Jimbin (Jimbinawa)" },
  { id: 183, label: "Jipal", value: "Jipal" },
  { id: 184, label: "Jirai", value: "Jirai" },
  { id: 185, label: "Joinkrama", value: "Joinkrama" },
  { id: 186, label: "Jonjo (Jenjo)", value: "Jonjo (Jenjo)" },
  { id: 187, label: "Jukun", value: "Jukun" },
  { id: 188, label: "Kaba (Kabawa)", value: "Kaba (Kabawa)" },
  { id: 189, label: "Kalabari", value: "Kalabari" },
  { id: 190, label: "Kajuru (Kajurawa)", value: "Kajuru (Kajurawa)" },
  { id: 191, label: "Kaka", value: "Kaka" },
  { id: 192, label: "Kamaku (Karnukawa)", value: "Kamaku (Karnukawa)" },
  { id: 193, label: "Kambari", value: "Kambari" },
  { id: 194, label: "Kambu", value: "Kambu" },
  { id: 195, label: "Kamwe", value: "Kamwe" },
  { id: 196, label: "Kanakuru (Dera)", value: "Kanakuru (Dera)" },
  { id: 197, label: "Kanembu", value: "Kanembu" },
  { id: 198, label: "Kanikon", value: "Kanikon" },
  { id: 199, label: "Kantana", value: "Kantana" },
  { id: 200, label: "Kanuri", value: "Kanuri" },
  { id: 201, label: "Karai-karai (Karekare)", value: "Karai-karai (Karekare)" },
  { id: 202, label: "Karimjo", value: "Karimjo" },
  { id: 203, label: "Kariya", value: "Kariya" },
  { id: 204, label: "Ke", value: "Ke" },
  { id: 205, label: "Kenern (Koenoem)", value: "Kenern (Koenoem)" },
  { id: 206, label: "Kenton", value: "Kenton" },
  { id: 207, label: "Kiballo (Kiwollo)", value: "Kiballo (Kiwollo)" },
  { id: 208, label: "Kilba", value: "Kilba" },
  { id: 209, label: "Kirfi (Kirfawa)", value: "Kirfi (Kirfawa)" },
  { id: 210, label: "Kodei", value: "Kodei" },
  { id: 211, label: "Kona", value: "Kona" },
  { id: 212, label: "Kono", value: "Kono" },
  { id: 213, label: "Koro (Kwaro)", value: "Koro (Kwaro)" },
  { id: 214, label: "Kubi (Kubawa)", value: "Kubi (Kubawa)" },
  { id: 215, label: "Kudachano (Kudawa)", value: "Kudachano (Kudawa)" },
  { id: 216, label: "Kugama", value: "Kugama" },
  { id: 217, label: "Kugbo", value: "Kugbo" },
  { id: 218, label: "Kulere (Kaler)", value: "Kulere (Kaler)" },
  { id: 219, label: "Kunini", value: "Kunini" },
  { id: 220, label: "Kurama (Akurmi)", value: "Kurama (Akurmi)" },
  { id: 221, label: "Kurdul", value: "Kurdul" },
  { id: 222, label: "Kushi", value: "Kushi" },
  { id: 223, label: "Kuteb", value: "Kuteb" },
  { id: 224, label: "Kutin", value: "Kutin" },
  { id: 225, label: "Kwalla", value: "Kwalla" },
  { id: 226, label: "Kwale", value: "Kwale" },
  { id: 227, label: "Kwami (Kwom)", value: "Kwami (Kwom)" },
  { id: 228, label: "Kwanchi", value: "Kwanchi" },
  { id: 229, label: "Kadung", value: "Kadung" },
  { id: 230, label: "Kwaro", value: "Kwaro" },
  { id: 231, label: "Kwato", value: "Kwato" },
  { id: 232, label: "Kyenga (Kengawa)", value: "Kyenga (Kengawa)" },
  { id: 233, label: "Laaru (Larawa)", value: "Laaru (Larawa)" },
  { id: 234, label: "Lakka", value: "Lakka" },
  { id: 235, label: "Lala", value: "Lala" },
  { id: 236, label: "Lama", value: "Lama" },
  { id: 237, label: "Lamja", value: "Lamja" },
  { id: 238, label: "Lau", value: "Lau" },
  { id: 239, label: "Limono", value: "Limono" },
  { id: 240, label: "Lopa (Lupa, Lopawa)", value: "Lopa (Lupa, Lopawa)" },
  { id: 241, label: "Longuda (Lunguda)", value: "Longuda (Lunguda)" },
  { id: 242, label: "Mabo", value: "Mabo" },
  { id: 243, label: "Mada", value: "Mada" },
  { id: 244, label: "Mama", value: "Mama" },
  { id: 245, label: "Mambilla", value: "Mambilla" },
  { id: 246, label: "Mandara (Wandala)", value: "Mandara (Wandala)" },
  { id: 247, label: "Manga (Mangawa)", value: "Manga (Mangawa)" },
  { id: 248, label: "Margi (Marghi)", value: "Margi (Marghi)" },
  { id: 249, label: "Mafa", value: "Mafa" },
  { id: 250, label: "Mbembe", value: "Mbembe" },
  { id: 251, label: "Mbol", value: "Mbol" },
  { id: 252, label: "Mbube", value: "Mbube" },
  { id: 253, label: "Mbula", value: "Mbula" },
  { id: 254, label: "Mbum", value: "Mbum" },
  { id: 255, label: "Memyang (Meryan)", value: "Memyang (Meryan)" },
  { id: 256, label: "Milighili (Mighili)", value: "Milighili (Mighili)" },
  { id: 257, label: "Miya (Miyawa)", value: "Miya (Miyawa)" },
  { id: 258, label: "Mobber", value: "Mobber" },
  { id: 259, label: "Montol", value: "Montol" },
  { id: 260, label: "Moruwa (Moro'a, Morwa)", value: "Moruwa (Moro'a, Morwa)" },
  { id: 261, label: "Muchaila", value: "Muchaila" },
  { id: 262, label: "Mumuye", value: "Mumuye" },
  { id: 263, label: "Mundang", value: "Mundang" },
  { id: 264, label: "Munga (Lelau)", value: "Munga (Lelau)" },
  { id: 265, label: "Munga (Mupang)", value: "Munga (Mupang)" },
  { id: 266, label: "Mupun", value: "Mupun" },
  { id: 267, label: "Mushere", value: "Mushere" },
  { id: 268, label: "Mwahavul (Mwaghavul)", value: "Mwahavul (Mwaghavul)" },
  { id: 269, label: "Ndoro", value: "Ndoro" },
  { id: 270, label: "Ngas (Angas)", value: "Ngas (Angas)" },
  { id: 271, label: "Ngizim", value: "Ngizim" },
  { id: 272, label: "Ngweshe (Ndhang.Ngoshe-Ndhang)", value: "Ngweshe (Ndhang.Ngoshe-Ndhang)" },
  { id: 273, label: "Nyiffon", value: "Nyiffon" },
  { id: 274, label: "Ningi (Ningawa)", value: "Ningi (Ningawa)" },
  { id: 275, label: "Njayi", value: "Njayi" },
  { id: 276, label: "Nkim", value: "Nkim" },
  { id: 277, label: "Nkum", value: "Nkum" },
  { id: 278, label: "Nokere (Nakere)", value: "Nokere (Nakere)" },
  { id: 279, label: "Nunku", value: "Nunku" },
  { id: 280, label: "Nupe", value: "Nupe" },
  { id: 281, label: "Nyam", value: "Nyam" },
  { id: 282, label: "Nyandang", value: "Nyandang" },
  { id: 283, label: "Obolo", value: "Obolo" },
  { id: 284, label: "Ododop", value: "Ododop" },
  { id: 285, label: "Ogba", value: "Ogba" },
  { id: 286, label: "Ogori", value: "Ogori" },
  { id: 287, label: "Okobo (Okkobor)", value: "Okobo (Okkobor)" },
  { id: 288, label: "Okirika", value: "Okirika" },
  { id: 289, label: "Okpamheri", value: "Okpamheri" },
  { id: 290, label: "Olukumi", value: "Olukumi" },
  { id: 291, label: "Oron", value: "Oron" },
  { id: 292, label: "Ososo", value: "Ososo" },
  { id: 293, label: "Owan", value: "Owan" },
  { id: 294, label: "Owe", value: "Owe" },
  { id: 295, label: "Oworo", value: "Oworo" },
  { id: 296, label: "Pa'a (Pa'awa Afawa)", value: "Pa'a (Pa'awa Afawa)" },
  { id: 297, label: "Pai", value: "Pai" },
  { id: 298, label: "Panyam", value: "Panyam" },
  { id: 299, label: "Pero", value: "Pero" },
  { id: 300, label: "Pire", value: "Pire" },
  { id: 301, label: "Pkanzom", value: "Pkanzom" },
  { id: 302, label: "Poll", value: "Poll" },
  { id: 303, label: "Polchi Habe", value: "Polchi Habe" },
  { id: 304, label: "Pongo (Pongu)", value: "Pongo (Pongu)" },
  { id: 305, label: "Potopo", value: "Potopo" },
  { id: 306, label: "Pyapun (Piapung)", value: "Pyapun (Piapung)" },
  { id: 307, label: "Qua", value: "Qua" },
  { id: 308, label: "Rebina (Rebinawa)", value: "Rebina (Rebinawa)" },
  { id: 309, label: "Reshe", value: "Reshe" },
  { id: 310, label: "Rindire (Rendre)", value: "Rindire (Rendre)" },
  { id: 311, label: "Rishuwa", value: "Rishuwa" },
  { id: 312, label: "Ron", value: "Ron" },
  { id: 313, label: "Rubu", value: "Rubu" },
  { id: 314, label: "Rukuba", value: "Rukuba" },
  { id: 315, label: "Rumada", value: "Rumada" },
  { id: 316, label: "Rumaya", value: "Rumaya" },
  { id: 317, label: "Sakbe", value: "Sakbe" },
  { id: 318, label: "Sanga", value: "Sanga" },
  { id: 319, label: "Sate", value: "Sate" },
  { id: 320, label: "Saya (Sayawa Za'ar)", value: "Saya (Sayawa Za'ar)" },
  { id: 321, label: "Segidi (Sigidawa)", value: "Segidi (Sigidawa)" },
  { id: 322, label: "Shanga (Shangawa)", value: "Shanga (Shangawa)" },
  { id: 323, label: "Shangawa (ShanKadunagau)", value: "Shangawa (ShanKadunagau)" },
  { id: 324, label: "Shan-Shan", value: "Shan-Shan" },
  { id: 325, label: "Shira (Shira )", value: "Shira (Shira )" },
  { id: 326, label: "Shomo", value: "Shomo" },
  { id: 327, label: "Shuwa (Baggara Arabs)", value: "Shuwa (Baggara Arabs)" },
  { id: 328, label: "Sikdi", value: "Sikdi" },
  { id: 329, label: "Siri (Sirawa)", value: "Siri (Sirawa)" },
  { id: 330, label: "Srubu (Surubu)", value: "Srubu (Surubu)" },
  { id: 331, label: "Sukur", value: "Sukur" },
  { id: 332, label: "Sura", value: "Sura" },
  { id: 333, label: "Tangale", value: "Tangale" },
  { id: 334, label: "Tarok (Yergam)", value: "Tarok (Yergam)" },
  { id: 335, label: "Teme", value: "Teme" },
  { id: 336, label: "Tera (Terawa)", value: "Tera (Terawa)" },
  { id: 337, label: "Teshena (Teshenawa)", value: "Teshena (Teshenawa)" },
  { id: 338, label: "Tigon", value: "Tigon" },
  { id: 339, label: "Tikar", value: "Tikar" },
  { id: 340, label: "Tiv", value: "Tiv" },
  { id: 341, label: "Tula", value: "Tula" },
  { id: 342, label: "Tur", value: "Tur" },
  { id: 343, label: "Ubbo", value: "Ubbo" },
  { id: 344, label: "Udekeama", value: "Udekeama" },
  { id: 345, label: "Ufia", value: "Ufia" },
  { id: 346, label: "Ukelle", value: "Ukelle" },
  { id: 347, label: "Uncinda", value: "Uncinda" },
  { id: 348, label: "Uneme (Ineme)", value: "Uneme (Ineme)" },
  { id: 349, label: "Ura (Ula)", value: "Ura (Ula)" },
  { id: 350, label: "Urhobo", value: "Urhobo" },
  { id: 351, label: "Utonkong", value: "Utonkong" },
  { id: 352, label: "Uwanno (Weppa-Wanno)", value: "Uwanno (Weppa-Wanno)" },
  { id: 353, label: "Uyanga", value: "Uyanga" },
  { id: 354, label: "Vemgo", value: "Vemgo" },
  { id: 355, label: "Verre", value: "Verre" },
  { id: 356, label: "Vommi", value: "Vommi" },
  { id: 357, label: "Wagga", value: "Wagga" },
  { id: 358, label: "Waja", value: "Waja" },
  { id: 359, label: "Waka", value: "Waka" },
  { id: 360, label: "Warja (Warja)", value: "Warja (Warja)" },
  { id: 361, label: "Warji", value: "Warji" },
  { id: 362, label: "Wurbo", value: "Wurbo" },
  { id: 363, label: "Wurkun", value: "Wurkun" },
  { id: 364, label: "Yache", value: "Yache" },
  { id: 365, label: "Yagba", value: "Yagba" },
  { id: 366, label: "Yakurr (Yako)", value: "Yakurr (Yako)" },
  { id: 367, label: "Yalla", value: "Yalla" },
  { id: 368, label: "Yandang", value: "Yandang" },
  { id: 369, label: "Yoruba", value: "Yoruba" },
  { id: 370, label: "Yott", value: "Yott" },
  { id: 371, label: "Yumu", value: "Yumu" },
  { id: 372, label: "Yungur", value: "Yungur" },
  { id: 373, label: "Yuom", value: "Yuom" },
  { id: 374, label: "Zabara", value: "Zabara" },
  { id: 375, label: "Zaranda", value: "Zaranda" },
  { id: 376, label: "Zarma (Zarmawa)", value: "Zarma (Zarmawa)" },
  { id: 377, label: "Zayam (Zeam)", value: "Zayam (Zeam)" },
  { id: 378, label: "Zul (Zulawa)", value: "Zul (Zulawa)" },
];

// religion
export const religionOptions: OptionType[] = [
  { id: 1, label: "Christianity", value: "Christianity" },
  { id: 2, label: "African religion", value: "African religion" },
  { id: 3, label: "Islam", value: "Islam" },
  { id: 4, label: "Judaism", value: "Judaism" },
  { id: 5, label: "Hinduism", value: "Hinduism" },
  { id: 6, label: "Others", value: "Others" },
];

// preferred social media
export const preferredSocialMediaOptions: OptionType[] = [
  { id: 1, label: "Facebook", value: "Facebook" },
  { id: 2, label: "Twitter", value: "Twitter" },
  { id: 3, label: "Instagram", value: "Instagram" },
  { id: 4, label: "LinkedIn", value: "LinkedIn" },
  { id: 5, label: "WhatsApp", value: "WhatsApp" },
  { id: 6, label: "YouTube", value: "YouTube" },
  { id: 7, label: "TikTok", value: "TikTok" },
  { id: 8, label: "Snapchat", value: "Snapchat" },
  { id: 9, label: "Telegram", value: "Telegram" },
  { id: 10, label: "Reddit", value: "Reddit" },
];

// registration status
export const registrationStatusOptions: OptionType[] = [
  { id: 1, label: "Registered", value: "Registered" },
  { id: 2, label: "Not Registered", value: "Not Registered" },
  { id: 3, label: "Pending Verification", value: "Pending Verification" },
  { id: 4, label: "Ineligible", value: "Ineligible" },
  { id: 5, label: "Registration Expired", value: "Registration Expired" },
];

// election concerns
export const electionConcernOptions: OptionType[] = [
  { id: 1, label: "Electoral Fraud", value: "Electoral Fraud" },
  { id: 2, label: "Voter Intimidation", value: "Voter Intimidation" },
  { id: 3, label: "Logistical Delays", value: "Logistical Delays" },
  { id: 4, label: "Lack of Transparency", value: "Lack of Transparency" },
  { id: 5, label: "Security Concerns at Polling Units", value: "Security Concerns at Polling Units" },
  { id: 6, label: "Bias in the Electoral Commission", value: "Bias in the Electoral Commission" },
  { id: 7, label: "Vote Buying", value: "Vote Buying" },
  { id: 8, label: "Access to Voter Education", value: "Access to Voter Education" },
  { id: 9, label: "Disenfranchisement of Eligible Voters", value: "Disenfranchisement of Eligible Voters" },
  { id: 10, label: "Counting and Collation Errors", value: "Counting and Collation Errors" },
];

export { statesLGAWardList } from "./StateLGAWard";